/*
 * Cobrança Bancária
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.CobrancaV3.Model;
using Sicoob.CobrancaV3.Client;
using System.Reflection;

namespace Sicoob.CobrancaV3.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner
        //private WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner instance;

        public WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInnerTests()
        {
            // TODO uncomment below to create an instance of WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner
            //instance = new WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner
        /// </summary>
        [Fact]
        public void WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner
            //Assert.IsType<WebhookSolicitacoesWebhookSolicitacoesInnerWebhookNotificacoesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'DataHoraInicio'
        /// </summary>
        [Fact]
        public void DataHoraInicioTest()
        {
            // TODO unit test for the property 'DataHoraInicio'
        }

        /// <summary>
        /// Test the property 'DataHoraFim'
        /// </summary>
        [Fact]
        public void DataHoraFimTest()
        {
            // TODO unit test for the property 'DataHoraFim'
        }

        /// <summary>
        /// Test the property 'TempoComunicao'
        /// </summary>
        [Fact]
        public void TempoComunicaoTest()
        {
            // TODO unit test for the property 'TempoComunicao'
        }

        /// <summary>
        /// Test the property 'CodigoStatusRequisicao'
        /// </summary>
        [Fact]
        public void CodigoStatusRequisicaoTest()
        {
            // TODO unit test for the property 'CodigoStatusRequisicao'
        }

        /// <summary>
        /// Test the property 'DescricaoCodigoStatusRequisicao'
        /// </summary>
        [Fact]
        public void DescricaoCodigoStatusRequisicaoTest()
        {
            // TODO unit test for the property 'DescricaoCodigoStatusRequisicao'
        }
    }
}
