/*
 * Pagamentos PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix-pagamentos/v2 ]</pre> API de pagamentos.
 *
 * The version of the OpenAPI document: 2.0.24.6
 * Contact: eduardod.silva@fornecedores.sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.PagamentosPix.Model;
using Sicoob.PagamentosPix.Client;
using System.Reflection;

namespace Sicoob.PagamentosPix.Test.Model
{
    /// <summary>
    ///  Class for testing PagamentosWebhookPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PagamentosWebhookPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PagamentosWebhookPostRequest
        //private PagamentosWebhookPostRequest instance;

        public PagamentosWebhookPostRequestTests()
        {
            // TODO uncomment below to create an instance of PagamentosWebhookPostRequest
            //instance = new PagamentosWebhookPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PagamentosWebhookPostRequest
        /// </summary>
        [Fact]
        public void PagamentosWebhookPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PagamentosWebhookPostRequest
            //Assert.IsType<PagamentosWebhookPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
    }
}
