// <auto-generated>
/*
 * Cobrança Bancária Pagamentos
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pagamentos/v3 ]</pre> Esta API disponibiliza funcionalidades para realização de pagamentos de boletos de Cobrança Bancária.
 *
 * The version of the OpenAPI document: 3.0.2.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.PagamentosV3.Client;

namespace Sicoob.PagamentosV3.Model
{
    /// <summary>
    /// ComprovantePagamento
    /// </summary>
    public partial class ComprovantePagamento : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComprovantePagamento" /> class.
        /// </summary>
        /// <param name="nomeAgencia">Nome da agência onde o pagamento foi realizado.</param>
        /// <param name="numeroLinhaDigitavel">Número da linha digitável do boleto formatado com 47 posições e 54 caracteres.</param>
        /// <param name="numeroInstituicaoEmissora">Número da instituição financeira emissora do boleto.</param>
        /// <param name="nomeInstituicaoEmissora">Nome da instituição financeira emissora do boleto.</param>
        /// <param name="dataVencimento">Data de vencimento do boleto. Formato: yyyy-MM-dd </param>
        /// <param name="valorBoleto">Valor nominal do boleto.</param>
        /// <param name="valorAbatimentoDesconto">Valor de abatimento e de desconto do boleto</param>
        /// <param name="valorMultaMora">Valor da multa e de juros/mora do boleto.</param>
        /// <param name="valorPagamento">Valor do pagamento do boleto.</param>
        /// <param name="dataPagamento">Data da efetivação do pagamento. Formato: yyyy-MM-dd </param>
        /// <param name="situacaoPagamento">Situação do pagamento do boleto.  - Rejeitado - Agendado - Efetivado </param>
        /// <param name="descricaoDetalheSituacao">Descrição detalhada da situação do pagamento.</param>
        /// <param name="dataHoraCadastro">Data e hora de cadastro do agendamento/pagamento. Formato: yyyy-MM-ddTHH:mm:ss.SSSZ (Conforme especificação RFC-3339 com uso de timezone UTC) </param>
        /// <param name="aceitaValorDivergente">Entre o agendamento e o pagamento, o boleto poderá sofrer alterações pelo benificiário. Autoriza o pagamento com o valor divergente do agendado?</param>
        /// <param name="descricaoOuvidoria">Descrição das informações da ouvidoria do Sicoob.</param>
        /// <param name="descricaoTituloComprovante">Descreve o boleto que deve ser utilizado no comprovante.  - AGENDAMENTO DE BOLETO - PAGAMENTO DE BOLETO - PAGAMENTO REJEITADO - PAGAMENTO CANCELADO - AGENDAMENTO DE BOLETO VLB - PAGAMENTO DE BOLETO VLB - PAGAMENTO VLB REJEITADO - PAGAMENTO VLB CANCELADO </param>
        /// <param name="idPagamento">Número de identificação do agendamento no SISBR.</param>
        /// <param name="numeroAgencia">Número da agência onde o pagamento foi realizado.</param>
        /// <param name="numeroConta">Número da Conta onde será realizado o débito para o pagamento.</param>
        /// <param name="nomeProprietarioContaCorrente">Nome do propietário da conta onde o pagamento foi ou será debitado.</param>
        /// <param name="numeroCpfCnpjBeneficiario">Número do CPF/CNPJ do beneficiário do boleto.</param>
        /// <param name="nomeRazaoSocialBeneficiario">Nome Razão Social do beneficiário do boleto.</param>
        /// <param name="nomeFantasiaBeneficiario">Nome Fantasia do beneficiário do boleto.</param>
        /// <param name="numeroCpfCnpjBeneficiarioFinal">Número do CPF/CNPJ do beneficiário final (antigo sacador avalista) do boleto.</param>
        /// <param name="nomeRazaoSocialBeneficiarioFinal">Nome Razão Social do beneficiário final (antigo sacador avalista) do boleto.</param>
        /// <param name="nomeFantasiaBeneficiarioFinal">Nome Fantasia do beneficiário final (antigo sacador avalista) do boleto.</param>
        /// <param name="numeroCpfCnpjPagador">Número do CPF/CNPJ do pagador do boleto.</param>
        /// <param name="nomeRazaoSocialPagador">Razão Social do Pagador do boleto</param>
        /// <param name="nomeFantasiaPagador">Nome Fantasia do pagador do boleto.</param>
        /// <param name="nossoNumero">Número identificador do boleto.</param>
        /// <param name="numeroDocumento">Número identificador do boleto no sistema do beneficiário.</param>
        /// <param name="descricaoObservacao">Descrição da observação informada no pagamento.</param>
        /// <param name="numeroAutenticacaoPagamento">Identificador único de autenticação do pagamento no SISBR.</param>
        [JsonConstructor]
        public ComprovantePagamento(string nomeAgencia, string numeroLinhaDigitavel, decimal numeroInstituicaoEmissora, string nomeInstituicaoEmissora, DateOnly dataVencimento, double valorBoleto, double valorAbatimentoDesconto, double valorMultaMora, double valorPagamento, DateOnly dataPagamento, string situacaoPagamento, string descricaoDetalheSituacao, DateTime dataHoraCadastro, bool aceitaValorDivergente, string descricaoOuvidoria, string descricaoTituloComprovante, long idPagamento, Option<string?> numeroAgencia = default, Option<long?> numeroConta = default, Option<string?> nomeProprietarioContaCorrente = default, Option<string?> numeroCpfCnpjBeneficiario = default, Option<string?> nomeRazaoSocialBeneficiario = default, Option<string?> nomeFantasiaBeneficiario = default, Option<string?> numeroCpfCnpjBeneficiarioFinal = default, Option<string?> nomeRazaoSocialBeneficiarioFinal = default, Option<string?> nomeFantasiaBeneficiarioFinal = default, Option<string?> numeroCpfCnpjPagador = default, Option<string?> nomeRazaoSocialPagador = default, Option<string?> nomeFantasiaPagador = default, Option<string?> nossoNumero = default, Option<string?> numeroDocumento = default, Option<string?> descricaoObservacao = default, Option<string?> numeroAutenticacaoPagamento = default)
        {
            NomeAgencia = nomeAgencia;
            NumeroLinhaDigitavel = numeroLinhaDigitavel;
            NumeroInstituicaoEmissora = numeroInstituicaoEmissora;
            NomeInstituicaoEmissora = nomeInstituicaoEmissora;
            DataVencimento = dataVencimento;
            ValorBoleto = valorBoleto;
            ValorAbatimentoDesconto = valorAbatimentoDesconto;
            ValorMultaMora = valorMultaMora;
            ValorPagamento = valorPagamento;
            DataPagamento = dataPagamento;
            SituacaoPagamento = situacaoPagamento;
            DescricaoDetalheSituacao = descricaoDetalheSituacao;
            DataHoraCadastro = dataHoraCadastro;
            AceitaValorDivergente = aceitaValorDivergente;
            DescricaoOuvidoria = descricaoOuvidoria;
            DescricaoTituloComprovante = descricaoTituloComprovante;
            IdPagamento = idPagamento;
            NumeroAgenciaOption = numeroAgencia;
            NumeroContaOption = numeroConta;
            NomeProprietarioContaCorrenteOption = nomeProprietarioContaCorrente;
            NumeroCpfCnpjBeneficiarioOption = numeroCpfCnpjBeneficiario;
            NomeRazaoSocialBeneficiarioOption = nomeRazaoSocialBeneficiario;
            NomeFantasiaBeneficiarioOption = nomeFantasiaBeneficiario;
            NumeroCpfCnpjBeneficiarioFinalOption = numeroCpfCnpjBeneficiarioFinal;
            NomeRazaoSocialBeneficiarioFinalOption = nomeRazaoSocialBeneficiarioFinal;
            NomeFantasiaBeneficiarioFinalOption = nomeFantasiaBeneficiarioFinal;
            NumeroCpfCnpjPagadorOption = numeroCpfCnpjPagador;
            NomeRazaoSocialPagadorOption = nomeRazaoSocialPagador;
            NomeFantasiaPagadorOption = nomeFantasiaPagador;
            NossoNumeroOption = nossoNumero;
            NumeroDocumentoOption = numeroDocumento;
            DescricaoObservacaoOption = descricaoObservacao;
            NumeroAutenticacaoPagamentoOption = numeroAutenticacaoPagamento;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Nome da agência onde o pagamento foi realizado.
        /// </summary>
        /// <value>Nome da agência onde o pagamento foi realizado.</value>
        /* <example>Agência Sede</example> */
        [JsonPropertyName("nomeAgencia")]
        public string NomeAgencia { get; set; }

        /// <summary>
        /// Número da linha digitável do boleto formatado com 47 posições e 54 caracteres.
        /// </summary>
        /// <value>Número da linha digitável do boleto formatado com 47 posições e 54 caracteres.</value>
        [JsonPropertyName("numeroLinhaDigitavel")]
        public string NumeroLinhaDigitavel { get; set; }

        /// <summary>
        /// Número da instituição financeira emissora do boleto.
        /// </summary>
        /// <value>Número da instituição financeira emissora do boleto.</value>
        /* <example>756.0</example> */
        [JsonPropertyName("numeroInstituicaoEmissora")]
        public decimal NumeroInstituicaoEmissora { get; set; }

        /// <summary>
        /// Nome da instituição financeira emissora do boleto.
        /// </summary>
        /// <value>Nome da instituição financeira emissora do boleto.</value>
        /* <example>Banco Cooperativo do Brasil</example> */
        [JsonPropertyName("nomeInstituicaoEmissora")]
        public string NomeInstituicaoEmissora { get; set; }

        /// <summary>
        /// Data de vencimento do boleto. Formato: yyyy-MM-dd 
        /// </summary>
        /// <value>Data de vencimento do boleto. Formato: yyyy-MM-dd </value>
        /* <example>Wed Sep 19 21:00:00 BRT 2018</example> */
        [JsonPropertyName("dataVencimento")]
        public DateOnly DataVencimento { get; set; }

        /// <summary>
        /// Valor nominal do boleto.
        /// </summary>
        /// <value>Valor nominal do boleto.</value>
        /* <example>100.36</example> */
        [JsonPropertyName("valorBoleto")]
        public double ValorBoleto { get; set; }

        /// <summary>
        /// Valor de abatimento e de desconto do boleto
        /// </summary>
        /// <value>Valor de abatimento e de desconto do boleto</value>
        /* <example>0.0</example> */
        [JsonPropertyName("valorAbatimentoDesconto")]
        public double ValorAbatimentoDesconto { get; set; }

        /// <summary>
        /// Valor da multa e de juros/mora do boleto.
        /// </summary>
        /// <value>Valor da multa e de juros/mora do boleto.</value>
        /* <example>60.36</example> */
        [JsonPropertyName("valorMultaMora")]
        public double ValorMultaMora { get; set; }

        /// <summary>
        /// Valor do pagamento do boleto.
        /// </summary>
        /// <value>Valor do pagamento do boleto.</value>
        /* <example>255.63</example> */
        [JsonPropertyName("valorPagamento")]
        public double ValorPagamento { get; set; }

        /// <summary>
        /// Data da efetivação do pagamento. Formato: yyyy-MM-dd 
        /// </summary>
        /// <value>Data da efetivação do pagamento. Formato: yyyy-MM-dd </value>
        /* <example>Sat Oct 19 21:00:00 BRT 2019</example> */
        [JsonPropertyName("dataPagamento")]
        public DateOnly DataPagamento { get; set; }

        /// <summary>
        /// Situação do pagamento do boleto.  - Rejeitado - Agendado - Efetivado 
        /// </summary>
        /// <value>Situação do pagamento do boleto.  - Rejeitado - Agendado - Efetivado </value>
        /* <example>Efetivado</example> */
        [JsonPropertyName("situacaoPagamento")]
        public string SituacaoPagamento { get; set; }

        /// <summary>
        /// Descrição detalhada da situação do pagamento.
        /// </summary>
        /// <value>Descrição detalhada da situação do pagamento.</value>
        /* <example>Saldo no momento da rejeição em 10/03/2021 às 22:01:10: R$ 343,05.</example> */
        [JsonPropertyName("descricaoDetalheSituacao")]
        public string DescricaoDetalheSituacao { get; set; }

        /// <summary>
        /// Data e hora de cadastro do agendamento/pagamento. Formato: yyyy-MM-ddTHH:mm:ss.SSSZ (Conforme especificação RFC-3339 com uso de timezone UTC) 
        /// </summary>
        /// <value>Data e hora de cadastro do agendamento/pagamento. Formato: yyyy-MM-ddTHH:mm:ss.SSSZ (Conforme especificação RFC-3339 com uso de timezone UTC) </value>
        /* <example>2019-10-20T12:30:22Z</example> */
        [JsonPropertyName("dataHoraCadastro")]
        public DateTime DataHoraCadastro { get; set; }

        /// <summary>
        /// Entre o agendamento e o pagamento, o boleto poderá sofrer alterações pelo benificiário. Autoriza o pagamento com o valor divergente do agendado?
        /// </summary>
        /// <value>Entre o agendamento e o pagamento, o boleto poderá sofrer alterações pelo benificiário. Autoriza o pagamento com o valor divergente do agendado?</value>
        /* <example>true</example> */
        [JsonPropertyName("aceitaValorDivergente")]
        public bool AceitaValorDivergente { get; set; }

        /// <summary>
        /// Descrição das informações da ouvidoria do Sicoob.
        /// </summary>
        /// <value>Descrição das informações da ouvidoria do Sicoob.</value>
        /* <example>OUVIDORIA AGIBANK: 08007250996</example> */
        [JsonPropertyName("descricaoOuvidoria")]
        public string DescricaoOuvidoria { get; set; }

        /// <summary>
        /// Descreve o boleto que deve ser utilizado no comprovante.  - AGENDAMENTO DE BOLETO - PAGAMENTO DE BOLETO - PAGAMENTO REJEITADO - PAGAMENTO CANCELADO - AGENDAMENTO DE BOLETO VLB - PAGAMENTO DE BOLETO VLB - PAGAMENTO VLB REJEITADO - PAGAMENTO VLB CANCELADO 
        /// </summary>
        /// <value>Descreve o boleto que deve ser utilizado no comprovante.  - AGENDAMENTO DE BOLETO - PAGAMENTO DE BOLETO - PAGAMENTO REJEITADO - PAGAMENTO CANCELADO - AGENDAMENTO DE BOLETO VLB - PAGAMENTO DE BOLETO VLB - PAGAMENTO VLB REJEITADO - PAGAMENTO VLB CANCELADO </value>
        /* <example>PAGAMENTO DE BOLETO</example> */
        [JsonPropertyName("descricaoTituloComprovante")]
        public string DescricaoTituloComprovante { get; set; }

        /// <summary>
        /// Número de identificação do agendamento no SISBR.
        /// </summary>
        /// <value>Número de identificação do agendamento no SISBR.</value>
        /* <example>1983450</example> */
        [JsonPropertyName("idPagamento")]
        public long IdPagamento { get; set; }

        /// <summary>
        /// Used to track the state of NumeroAgencia
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumeroAgenciaOption { get; private set; }

        /// <summary>
        /// Número da agência onde o pagamento foi realizado.
        /// </summary>
        /// <value>Número da agência onde o pagamento foi realizado.</value>
        /* <example>0001-9</example> */
        [JsonPropertyName("numeroAgencia")]
        public string? NumeroAgencia { get { return this.NumeroAgenciaOption.Value; } set { this.NumeroAgenciaOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumeroConta
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> NumeroContaOption { get; private set; }

        /// <summary>
        /// Número da Conta onde será realizado o débito para o pagamento.
        /// </summary>
        /// <value>Número da Conta onde será realizado o débito para o pagamento.</value>
        /* <example>1234569</example> */
        [JsonPropertyName("numeroConta")]
        public long? NumeroConta { get { return this.NumeroContaOption.Value; } set { this.NumeroContaOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeProprietarioContaCorrente
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeProprietarioContaCorrenteOption { get; private set; }

        /// <summary>
        /// Nome do propietário da conta onde o pagamento foi ou será debitado.
        /// </summary>
        /// <value>Nome do propietário da conta onde o pagamento foi ou será debitado.</value>
        /* <example>José da Silva</example> */
        [JsonPropertyName("nomeProprietarioContaCorrente")]
        public string? NomeProprietarioContaCorrente { get { return this.NomeProprietarioContaCorrenteOption.Value; } set { this.NomeProprietarioContaCorrenteOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumeroCpfCnpjBeneficiario
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumeroCpfCnpjBeneficiarioOption { get; private set; }

        /// <summary>
        /// Número do CPF/CNPJ do beneficiário do boleto.
        /// </summary>
        /// <value>Número do CPF/CNPJ do beneficiário do boleto.</value>
        /* <example>12345678900</example> */
        [JsonPropertyName("numeroCpfCnpjBeneficiario")]
        public string? NumeroCpfCnpjBeneficiario { get { return this.NumeroCpfCnpjBeneficiarioOption.Value; } set { this.NumeroCpfCnpjBeneficiarioOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeRazaoSocialBeneficiario
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeRazaoSocialBeneficiarioOption { get; private set; }

        /// <summary>
        /// Nome Razão Social do beneficiário do boleto.
        /// </summary>
        /// <value>Nome Razão Social do beneficiário do boleto.</value>
        /* <example>José da Silva</example> */
        [JsonPropertyName("nomeRazaoSocialBeneficiario")]
        public string? NomeRazaoSocialBeneficiario { get { return this.NomeRazaoSocialBeneficiarioOption.Value; } set { this.NomeRazaoSocialBeneficiarioOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeFantasiaBeneficiario
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeFantasiaBeneficiarioOption { get; private set; }

        /// <summary>
        /// Nome Fantasia do beneficiário do boleto.
        /// </summary>
        /// <value>Nome Fantasia do beneficiário do boleto.</value>
        /* <example>Estilo Tech</example> */
        [JsonPropertyName("nomeFantasiaBeneficiario")]
        public string? NomeFantasiaBeneficiario { get { return this.NomeFantasiaBeneficiarioOption.Value; } set { this.NomeFantasiaBeneficiarioOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumeroCpfCnpjBeneficiarioFinal
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumeroCpfCnpjBeneficiarioFinalOption { get; private set; }

        /// <summary>
        /// Número do CPF/CNPJ do beneficiário final (antigo sacador avalista) do boleto.
        /// </summary>
        /// <value>Número do CPF/CNPJ do beneficiário final (antigo sacador avalista) do boleto.</value>
        /* <example>12345678900</example> */
        [JsonPropertyName("numeroCpfCnpjBeneficiarioFinal")]
        public string? NumeroCpfCnpjBeneficiarioFinal { get { return this.NumeroCpfCnpjBeneficiarioFinalOption.Value; } set { this.NumeroCpfCnpjBeneficiarioFinalOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeRazaoSocialBeneficiarioFinal
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeRazaoSocialBeneficiarioFinalOption { get; private set; }

        /// <summary>
        /// Nome Razão Social do beneficiário final (antigo sacador avalista) do boleto.
        /// </summary>
        /// <value>Nome Razão Social do beneficiário final (antigo sacador avalista) do boleto.</value>
        /* <example>João das Flores</example> */
        [JsonPropertyName("nomeRazaoSocialBeneficiarioFinal")]
        public string? NomeRazaoSocialBeneficiarioFinal { get { return this.NomeRazaoSocialBeneficiarioFinalOption.Value; } set { this.NomeRazaoSocialBeneficiarioFinalOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeFantasiaBeneficiarioFinal
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeFantasiaBeneficiarioFinalOption { get; private set; }

        /// <summary>
        /// Nome Fantasia do beneficiário final (antigo sacador avalista) do boleto.
        /// </summary>
        /// <value>Nome Fantasia do beneficiário final (antigo sacador avalista) do boleto.</value>
        /* <example>Quinatda dojão</example> */
        [JsonPropertyName("nomeFantasiaBeneficiarioFinal")]
        public string? NomeFantasiaBeneficiarioFinal { get { return this.NomeFantasiaBeneficiarioFinalOption.Value; } set { this.NomeFantasiaBeneficiarioFinalOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumeroCpfCnpjPagador
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumeroCpfCnpjPagadorOption { get; private set; }

        /// <summary>
        /// Número do CPF/CNPJ do pagador do boleto.
        /// </summary>
        /// <value>Número do CPF/CNPJ do pagador do boleto.</value>
        /* <example>12345678900</example> */
        [JsonPropertyName("numeroCpfCnpjPagador")]
        public string? NumeroCpfCnpjPagador { get { return this.NumeroCpfCnpjPagadorOption.Value; } set { this.NumeroCpfCnpjPagadorOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeRazaoSocialPagador
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeRazaoSocialPagadorOption { get; private set; }

        /// <summary>
        /// Razão Social do Pagador do boleto
        /// </summary>
        /// <value>Razão Social do Pagador do boleto</value>
        /* <example>Maria José</example> */
        [JsonPropertyName("nomeRazaoSocialPagador")]
        public string? NomeRazaoSocialPagador { get { return this.NomeRazaoSocialPagadorOption.Value; } set { this.NomeRazaoSocialPagadorOption = new(value); } }

        /// <summary>
        /// Used to track the state of NomeFantasiaPagador
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NomeFantasiaPagadorOption { get; private set; }

        /// <summary>
        /// Nome Fantasia do pagador do boleto.
        /// </summary>
        /// <value>Nome Fantasia do pagador do boleto.</value>
        /* <example>Rosa Maria da Silva</example> */
        [JsonPropertyName("nomeFantasiaPagador")]
        public string? NomeFantasiaPagador { get { return this.NomeFantasiaPagadorOption.Value; } set { this.NomeFantasiaPagadorOption = new(value); } }

        /// <summary>
        /// Used to track the state of NossoNumero
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NossoNumeroOption { get; private set; }

        /// <summary>
        /// Número identificador do boleto.
        /// </summary>
        /// <value>Número identificador do boleto.</value>
        /* <example>756</example> */
        [JsonPropertyName("nossoNumero")]
        public string? NossoNumero { get { return this.NossoNumeroOption.Value; } set { this.NossoNumeroOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumeroDocumento
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumeroDocumentoOption { get; private set; }

        /// <summary>
        /// Número identificador do boleto no sistema do beneficiário.
        /// </summary>
        /// <value>Número identificador do boleto no sistema do beneficiário.</value>
        /* <example>123456</example> */
        [JsonPropertyName("numeroDocumento")]
        public string? NumeroDocumento { get { return this.NumeroDocumentoOption.Value; } set { this.NumeroDocumentoOption = new(value); } }

        /// <summary>
        /// Used to track the state of DescricaoObservacao
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescricaoObservacaoOption { get; private set; }

        /// <summary>
        /// Descrição da observação informada no pagamento.
        /// </summary>
        /// <value>Descrição da observação informada no pagamento.</value>
        /* <example>Boleto da Escola</example> */
        [JsonPropertyName("descricaoObservacao")]
        public string? DescricaoObservacao { get { return this.DescricaoObservacaoOption.Value; } set { this.DescricaoObservacaoOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumeroAutenticacaoPagamento
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumeroAutenticacaoPagamentoOption { get; private set; }

        /// <summary>
        /// Identificador único de autenticação do pagamento no SISBR.
        /// </summary>
        /// <value>Identificador único de autenticação do pagamento no SISBR.</value>
        /* <example>89C3E9FD-1A37-40BE-A85B-69AF118D336A</example> */
        [JsonPropertyName("numeroAutenticacaoPagamento")]
        public string? NumeroAutenticacaoPagamento { get { return this.NumeroAutenticacaoPagamentoOption.Value; } set { this.NumeroAutenticacaoPagamentoOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ComprovantePagamento {\n");
            sb.Append("  NomeAgencia: ").Append(NomeAgencia).Append("\n");
            sb.Append("  NumeroLinhaDigitavel: ").Append(NumeroLinhaDigitavel).Append("\n");
            sb.Append("  NumeroInstituicaoEmissora: ").Append(NumeroInstituicaoEmissora).Append("\n");
            sb.Append("  NomeInstituicaoEmissora: ").Append(NomeInstituicaoEmissora).Append("\n");
            sb.Append("  DataVencimento: ").Append(DataVencimento).Append("\n");
            sb.Append("  ValorBoleto: ").Append(ValorBoleto).Append("\n");
            sb.Append("  ValorAbatimentoDesconto: ").Append(ValorAbatimentoDesconto).Append("\n");
            sb.Append("  ValorMultaMora: ").Append(ValorMultaMora).Append("\n");
            sb.Append("  ValorPagamento: ").Append(ValorPagamento).Append("\n");
            sb.Append("  DataPagamento: ").Append(DataPagamento).Append("\n");
            sb.Append("  SituacaoPagamento: ").Append(SituacaoPagamento).Append("\n");
            sb.Append("  DescricaoDetalheSituacao: ").Append(DescricaoDetalheSituacao).Append("\n");
            sb.Append("  DataHoraCadastro: ").Append(DataHoraCadastro).Append("\n");
            sb.Append("  AceitaValorDivergente: ").Append(AceitaValorDivergente).Append("\n");
            sb.Append("  DescricaoOuvidoria: ").Append(DescricaoOuvidoria).Append("\n");
            sb.Append("  DescricaoTituloComprovante: ").Append(DescricaoTituloComprovante).Append("\n");
            sb.Append("  IdPagamento: ").Append(IdPagamento).Append("\n");
            sb.Append("  NumeroAgencia: ").Append(NumeroAgencia).Append("\n");
            sb.Append("  NumeroConta: ").Append(NumeroConta).Append("\n");
            sb.Append("  NomeProprietarioContaCorrente: ").Append(NomeProprietarioContaCorrente).Append("\n");
            sb.Append("  NumeroCpfCnpjBeneficiario: ").Append(NumeroCpfCnpjBeneficiario).Append("\n");
            sb.Append("  NomeRazaoSocialBeneficiario: ").Append(NomeRazaoSocialBeneficiario).Append("\n");
            sb.Append("  NomeFantasiaBeneficiario: ").Append(NomeFantasiaBeneficiario).Append("\n");
            sb.Append("  NumeroCpfCnpjBeneficiarioFinal: ").Append(NumeroCpfCnpjBeneficiarioFinal).Append("\n");
            sb.Append("  NomeRazaoSocialBeneficiarioFinal: ").Append(NomeRazaoSocialBeneficiarioFinal).Append("\n");
            sb.Append("  NomeFantasiaBeneficiarioFinal: ").Append(NomeFantasiaBeneficiarioFinal).Append("\n");
            sb.Append("  NumeroCpfCnpjPagador: ").Append(NumeroCpfCnpjPagador).Append("\n");
            sb.Append("  NomeRazaoSocialPagador: ").Append(NomeRazaoSocialPagador).Append("\n");
            sb.Append("  NomeFantasiaPagador: ").Append(NomeFantasiaPagador).Append("\n");
            sb.Append("  NossoNumero: ").Append(NossoNumero).Append("\n");
            sb.Append("  NumeroDocumento: ").Append(NumeroDocumento).Append("\n");
            sb.Append("  DescricaoObservacao: ").Append(DescricaoObservacao).Append("\n");
            sb.Append("  NumeroAutenticacaoPagamento: ").Append(NumeroAutenticacaoPagamento).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ComprovantePagamento" />
    /// </summary>
    public class ComprovantePagamentoJsonConverter : JsonConverter<ComprovantePagamento>
    {
        /// <summary>
        /// The format to use to serialize DataVencimento
        /// </summary>
        public static string DataVencimentoFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize DataPagamento
        /// </summary>
        public static string DataPagamentoFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize DataHoraCadastro
        /// </summary>
        public static string DataHoraCadastroFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ComprovantePagamento" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ComprovantePagamento Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> nomeAgencia = default;
            Option<string?> numeroLinhaDigitavel = default;
            Option<decimal?> numeroInstituicaoEmissora = default;
            Option<string?> nomeInstituicaoEmissora = default;
            Option<DateOnly?> dataVencimento = default;
            Option<double?> valorBoleto = default;
            Option<double?> valorAbatimentoDesconto = default;
            Option<double?> valorMultaMora = default;
            Option<double?> valorPagamento = default;
            Option<DateOnly?> dataPagamento = default;
            Option<string?> situacaoPagamento = default;
            Option<string?> descricaoDetalheSituacao = default;
            Option<DateTime?> dataHoraCadastro = default;
            Option<bool?> aceitaValorDivergente = default;
            Option<string?> descricaoOuvidoria = default;
            Option<string?> descricaoTituloComprovante = default;
            Option<long?> idPagamento = default;
            Option<string?> numeroAgencia = default;
            Option<long?> numeroConta = default;
            Option<string?> nomeProprietarioContaCorrente = default;
            Option<string?> numeroCpfCnpjBeneficiario = default;
            Option<string?> nomeRazaoSocialBeneficiario = default;
            Option<string?> nomeFantasiaBeneficiario = default;
            Option<string?> numeroCpfCnpjBeneficiarioFinal = default;
            Option<string?> nomeRazaoSocialBeneficiarioFinal = default;
            Option<string?> nomeFantasiaBeneficiarioFinal = default;
            Option<string?> numeroCpfCnpjPagador = default;
            Option<string?> nomeRazaoSocialPagador = default;
            Option<string?> nomeFantasiaPagador = default;
            Option<string?> nossoNumero = default;
            Option<string?> numeroDocumento = default;
            Option<string?> descricaoObservacao = default;
            Option<string?> numeroAutenticacaoPagamento = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nomeAgencia":
                            nomeAgencia = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroLinhaDigitavel":
                            numeroLinhaDigitavel = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroInstituicaoEmissora":
                            numeroInstituicaoEmissora = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "nomeInstituicaoEmissora":
                            nomeInstituicaoEmissora = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dataVencimento":
                            dataVencimento = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "valorBoleto":
                            valorBoleto = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "valorAbatimentoDesconto":
                            valorAbatimentoDesconto = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "valorMultaMora":
                            valorMultaMora = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "valorPagamento":
                            valorPagamento = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "dataPagamento":
                            dataPagamento = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "situacaoPagamento":
                            situacaoPagamento = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "descricaoDetalheSituacao":
                            descricaoDetalheSituacao = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dataHoraCadastro":
                            dataHoraCadastro = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "aceitaValorDivergente":
                            aceitaValorDivergente = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "descricaoOuvidoria":
                            descricaoOuvidoria = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "descricaoTituloComprovante":
                            descricaoTituloComprovante = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "idPagamento":
                            idPagamento = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "numeroAgencia":
                            numeroAgencia = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroConta":
                            numeroConta = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "nomeProprietarioContaCorrente":
                            nomeProprietarioContaCorrente = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroCpfCnpjBeneficiario":
                            numeroCpfCnpjBeneficiario = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nomeRazaoSocialBeneficiario":
                            nomeRazaoSocialBeneficiario = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nomeFantasiaBeneficiario":
                            nomeFantasiaBeneficiario = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroCpfCnpjBeneficiarioFinal":
                            numeroCpfCnpjBeneficiarioFinal = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nomeRazaoSocialBeneficiarioFinal":
                            nomeRazaoSocialBeneficiarioFinal = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nomeFantasiaBeneficiarioFinal":
                            nomeFantasiaBeneficiarioFinal = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroCpfCnpjPagador":
                            numeroCpfCnpjPagador = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nomeRazaoSocialPagador":
                            nomeRazaoSocialPagador = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nomeFantasiaPagador":
                            nomeFantasiaPagador = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nossoNumero":
                            nossoNumero = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroDocumento":
                            numeroDocumento = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "descricaoObservacao":
                            descricaoObservacao = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "numeroAutenticacaoPagamento":
                            numeroAutenticacaoPagamento = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!nomeAgencia.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(nomeAgencia));

            if (!numeroLinhaDigitavel.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(numeroLinhaDigitavel));

            if (!numeroInstituicaoEmissora.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(numeroInstituicaoEmissora));

            if (!nomeInstituicaoEmissora.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(nomeInstituicaoEmissora));

            if (!dataVencimento.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(dataVencimento));

            if (!valorBoleto.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(valorBoleto));

            if (!valorAbatimentoDesconto.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(valorAbatimentoDesconto));

            if (!valorMultaMora.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(valorMultaMora));

            if (!valorPagamento.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(valorPagamento));

            if (!dataPagamento.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(dataPagamento));

            if (!situacaoPagamento.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(situacaoPagamento));

            if (!descricaoDetalheSituacao.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(descricaoDetalheSituacao));

            if (!dataHoraCadastro.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(dataHoraCadastro));

            if (!aceitaValorDivergente.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(aceitaValorDivergente));

            if (!descricaoOuvidoria.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(descricaoOuvidoria));

            if (!descricaoTituloComprovante.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(descricaoTituloComprovante));

            if (!idPagamento.IsSet)
                throw new ArgumentException("Property is required for class ComprovantePagamento.", nameof(idPagamento));

            if (nomeAgencia.IsSet && nomeAgencia.Value == null)
                throw new ArgumentNullException(nameof(nomeAgencia), "Property is not nullable for class ComprovantePagamento.");

            if (numeroLinhaDigitavel.IsSet && numeroLinhaDigitavel.Value == null)
                throw new ArgumentNullException(nameof(numeroLinhaDigitavel), "Property is not nullable for class ComprovantePagamento.");

            if (numeroInstituicaoEmissora.IsSet && numeroInstituicaoEmissora.Value == null)
                throw new ArgumentNullException(nameof(numeroInstituicaoEmissora), "Property is not nullable for class ComprovantePagamento.");

            if (nomeInstituicaoEmissora.IsSet && nomeInstituicaoEmissora.Value == null)
                throw new ArgumentNullException(nameof(nomeInstituicaoEmissora), "Property is not nullable for class ComprovantePagamento.");

            if (dataVencimento.IsSet && dataVencimento.Value == null)
                throw new ArgumentNullException(nameof(dataVencimento), "Property is not nullable for class ComprovantePagamento.");

            if (valorBoleto.IsSet && valorBoleto.Value == null)
                throw new ArgumentNullException(nameof(valorBoleto), "Property is not nullable for class ComprovantePagamento.");

            if (valorAbatimentoDesconto.IsSet && valorAbatimentoDesconto.Value == null)
                throw new ArgumentNullException(nameof(valorAbatimentoDesconto), "Property is not nullable for class ComprovantePagamento.");

            if (valorMultaMora.IsSet && valorMultaMora.Value == null)
                throw new ArgumentNullException(nameof(valorMultaMora), "Property is not nullable for class ComprovantePagamento.");

            if (valorPagamento.IsSet && valorPagamento.Value == null)
                throw new ArgumentNullException(nameof(valorPagamento), "Property is not nullable for class ComprovantePagamento.");

            if (dataPagamento.IsSet && dataPagamento.Value == null)
                throw new ArgumentNullException(nameof(dataPagamento), "Property is not nullable for class ComprovantePagamento.");

            if (situacaoPagamento.IsSet && situacaoPagamento.Value == null)
                throw new ArgumentNullException(nameof(situacaoPagamento), "Property is not nullable for class ComprovantePagamento.");

            if (descricaoDetalheSituacao.IsSet && descricaoDetalheSituacao.Value == null)
                throw new ArgumentNullException(nameof(descricaoDetalheSituacao), "Property is not nullable for class ComprovantePagamento.");

            if (dataHoraCadastro.IsSet && dataHoraCadastro.Value == null)
                throw new ArgumentNullException(nameof(dataHoraCadastro), "Property is not nullable for class ComprovantePagamento.");

            if (aceitaValorDivergente.IsSet && aceitaValorDivergente.Value == null)
                throw new ArgumentNullException(nameof(aceitaValorDivergente), "Property is not nullable for class ComprovantePagamento.");

            if (descricaoOuvidoria.IsSet && descricaoOuvidoria.Value == null)
                throw new ArgumentNullException(nameof(descricaoOuvidoria), "Property is not nullable for class ComprovantePagamento.");

            if (descricaoTituloComprovante.IsSet && descricaoTituloComprovante.Value == null)
                throw new ArgumentNullException(nameof(descricaoTituloComprovante), "Property is not nullable for class ComprovantePagamento.");

            if (idPagamento.IsSet && idPagamento.Value == null)
                throw new ArgumentNullException(nameof(idPagamento), "Property is not nullable for class ComprovantePagamento.");

            if (numeroAgencia.IsSet && numeroAgencia.Value == null)
                throw new ArgumentNullException(nameof(numeroAgencia), "Property is not nullable for class ComprovantePagamento.");

            if (numeroConta.IsSet && numeroConta.Value == null)
                throw new ArgumentNullException(nameof(numeroConta), "Property is not nullable for class ComprovantePagamento.");

            if (nomeProprietarioContaCorrente.IsSet && nomeProprietarioContaCorrente.Value == null)
                throw new ArgumentNullException(nameof(nomeProprietarioContaCorrente), "Property is not nullable for class ComprovantePagamento.");

            if (numeroCpfCnpjBeneficiario.IsSet && numeroCpfCnpjBeneficiario.Value == null)
                throw new ArgumentNullException(nameof(numeroCpfCnpjBeneficiario), "Property is not nullable for class ComprovantePagamento.");

            if (nomeRazaoSocialBeneficiario.IsSet && nomeRazaoSocialBeneficiario.Value == null)
                throw new ArgumentNullException(nameof(nomeRazaoSocialBeneficiario), "Property is not nullable for class ComprovantePagamento.");

            if (nomeFantasiaBeneficiario.IsSet && nomeFantasiaBeneficiario.Value == null)
                throw new ArgumentNullException(nameof(nomeFantasiaBeneficiario), "Property is not nullable for class ComprovantePagamento.");

            if (numeroCpfCnpjBeneficiarioFinal.IsSet && numeroCpfCnpjBeneficiarioFinal.Value == null)
                throw new ArgumentNullException(nameof(numeroCpfCnpjBeneficiarioFinal), "Property is not nullable for class ComprovantePagamento.");

            if (nomeRazaoSocialBeneficiarioFinal.IsSet && nomeRazaoSocialBeneficiarioFinal.Value == null)
                throw new ArgumentNullException(nameof(nomeRazaoSocialBeneficiarioFinal), "Property is not nullable for class ComprovantePagamento.");

            if (nomeFantasiaBeneficiarioFinal.IsSet && nomeFantasiaBeneficiarioFinal.Value == null)
                throw new ArgumentNullException(nameof(nomeFantasiaBeneficiarioFinal), "Property is not nullable for class ComprovantePagamento.");

            if (numeroCpfCnpjPagador.IsSet && numeroCpfCnpjPagador.Value == null)
                throw new ArgumentNullException(nameof(numeroCpfCnpjPagador), "Property is not nullable for class ComprovantePagamento.");

            if (nomeRazaoSocialPagador.IsSet && nomeRazaoSocialPagador.Value == null)
                throw new ArgumentNullException(nameof(nomeRazaoSocialPagador), "Property is not nullable for class ComprovantePagamento.");

            if (nomeFantasiaPagador.IsSet && nomeFantasiaPagador.Value == null)
                throw new ArgumentNullException(nameof(nomeFantasiaPagador), "Property is not nullable for class ComprovantePagamento.");

            if (nossoNumero.IsSet && nossoNumero.Value == null)
                throw new ArgumentNullException(nameof(nossoNumero), "Property is not nullable for class ComprovantePagamento.");

            if (numeroDocumento.IsSet && numeroDocumento.Value == null)
                throw new ArgumentNullException(nameof(numeroDocumento), "Property is not nullable for class ComprovantePagamento.");

            if (descricaoObservacao.IsSet && descricaoObservacao.Value == null)
                throw new ArgumentNullException(nameof(descricaoObservacao), "Property is not nullable for class ComprovantePagamento.");

            if (numeroAutenticacaoPagamento.IsSet && numeroAutenticacaoPagamento.Value == null)
                throw new ArgumentNullException(nameof(numeroAutenticacaoPagamento), "Property is not nullable for class ComprovantePagamento.");

            return new ComprovantePagamento(nomeAgencia.Value!, numeroLinhaDigitavel.Value!, numeroInstituicaoEmissora.Value!.Value!, nomeInstituicaoEmissora.Value!, dataVencimento.Value!.Value!, valorBoleto.Value!.Value!, valorAbatimentoDesconto.Value!.Value!, valorMultaMora.Value!.Value!, valorPagamento.Value!.Value!, dataPagamento.Value!.Value!, situacaoPagamento.Value!, descricaoDetalheSituacao.Value!, dataHoraCadastro.Value!.Value!, aceitaValorDivergente.Value!.Value!, descricaoOuvidoria.Value!, descricaoTituloComprovante.Value!, idPagamento.Value!.Value!, numeroAgencia, numeroConta, nomeProprietarioContaCorrente, numeroCpfCnpjBeneficiario, nomeRazaoSocialBeneficiario, nomeFantasiaBeneficiario, numeroCpfCnpjBeneficiarioFinal, nomeRazaoSocialBeneficiarioFinal, nomeFantasiaBeneficiarioFinal, numeroCpfCnpjPagador, nomeRazaoSocialPagador, nomeFantasiaPagador, nossoNumero, numeroDocumento, descricaoObservacao, numeroAutenticacaoPagamento);
        }

        /// <summary>
        /// Serializes a <see cref="ComprovantePagamento" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="comprovantePagamento"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ComprovantePagamento comprovantePagamento, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, comprovantePagamento, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ComprovantePagamento" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="comprovantePagamento"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ComprovantePagamento comprovantePagamento, JsonSerializerOptions jsonSerializerOptions)
        {
            if (comprovantePagamento.NomeAgencia == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeAgencia), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroLinhaDigitavel == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroLinhaDigitavel), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeInstituicaoEmissora == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeInstituicaoEmissora), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.SituacaoPagamento == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.SituacaoPagamento), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.DescricaoDetalheSituacao == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.DescricaoDetalheSituacao), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.DescricaoOuvidoria == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.DescricaoOuvidoria), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.DescricaoTituloComprovante == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.DescricaoTituloComprovante), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroAgenciaOption.IsSet && comprovantePagamento.NumeroAgencia == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroAgencia), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeProprietarioContaCorrenteOption.IsSet && comprovantePagamento.NomeProprietarioContaCorrente == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeProprietarioContaCorrente), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroCpfCnpjBeneficiarioOption.IsSet && comprovantePagamento.NumeroCpfCnpjBeneficiario == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroCpfCnpjBeneficiario), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeRazaoSocialBeneficiarioOption.IsSet && comprovantePagamento.NomeRazaoSocialBeneficiario == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeRazaoSocialBeneficiario), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeFantasiaBeneficiarioOption.IsSet && comprovantePagamento.NomeFantasiaBeneficiario == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeFantasiaBeneficiario), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroCpfCnpjBeneficiarioFinalOption.IsSet && comprovantePagamento.NumeroCpfCnpjBeneficiarioFinal == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroCpfCnpjBeneficiarioFinal), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeRazaoSocialBeneficiarioFinalOption.IsSet && comprovantePagamento.NomeRazaoSocialBeneficiarioFinal == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeRazaoSocialBeneficiarioFinal), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeFantasiaBeneficiarioFinalOption.IsSet && comprovantePagamento.NomeFantasiaBeneficiarioFinal == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeFantasiaBeneficiarioFinal), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroCpfCnpjPagadorOption.IsSet && comprovantePagamento.NumeroCpfCnpjPagador == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroCpfCnpjPagador), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeRazaoSocialPagadorOption.IsSet && comprovantePagamento.NomeRazaoSocialPagador == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeRazaoSocialPagador), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NomeFantasiaPagadorOption.IsSet && comprovantePagamento.NomeFantasiaPagador == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NomeFantasiaPagador), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NossoNumeroOption.IsSet && comprovantePagamento.NossoNumero == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NossoNumero), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroDocumentoOption.IsSet && comprovantePagamento.NumeroDocumento == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroDocumento), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.DescricaoObservacaoOption.IsSet && comprovantePagamento.DescricaoObservacao == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.DescricaoObservacao), "Property is required for class ComprovantePagamento.");

            if (comprovantePagamento.NumeroAutenticacaoPagamentoOption.IsSet && comprovantePagamento.NumeroAutenticacaoPagamento == null)
                throw new ArgumentNullException(nameof(comprovantePagamento.NumeroAutenticacaoPagamento), "Property is required for class ComprovantePagamento.");

            writer.WriteString("nomeAgencia", comprovantePagamento.NomeAgencia);

            writer.WriteString("numeroLinhaDigitavel", comprovantePagamento.NumeroLinhaDigitavel);

            writer.WriteNumber("numeroInstituicaoEmissora", comprovantePagamento.NumeroInstituicaoEmissora);

            writer.WriteString("nomeInstituicaoEmissora", comprovantePagamento.NomeInstituicaoEmissora);

            writer.WriteString("dataVencimento", comprovantePagamento.DataVencimento.ToString(DataVencimentoFormat));

            writer.WriteNumber("valorBoleto", comprovantePagamento.ValorBoleto);

            writer.WriteNumber("valorAbatimentoDesconto", comprovantePagamento.ValorAbatimentoDesconto);

            writer.WriteNumber("valorMultaMora", comprovantePagamento.ValorMultaMora);

            writer.WriteNumber("valorPagamento", comprovantePagamento.ValorPagamento);

            writer.WriteString("dataPagamento", comprovantePagamento.DataPagamento.ToString(DataPagamentoFormat));

            writer.WriteString("situacaoPagamento", comprovantePagamento.SituacaoPagamento);

            writer.WriteString("descricaoDetalheSituacao", comprovantePagamento.DescricaoDetalheSituacao);

            writer.WriteString("dataHoraCadastro", comprovantePagamento.DataHoraCadastro.ToString(DataHoraCadastroFormat));

            writer.WriteBoolean("aceitaValorDivergente", comprovantePagamento.AceitaValorDivergente);

            writer.WriteString("descricaoOuvidoria", comprovantePagamento.DescricaoOuvidoria);

            writer.WriteString("descricaoTituloComprovante", comprovantePagamento.DescricaoTituloComprovante);

            writer.WriteNumber("idPagamento", comprovantePagamento.IdPagamento);

            if (comprovantePagamento.NumeroAgenciaOption.IsSet)
                writer.WriteString("numeroAgencia", comprovantePagamento.NumeroAgencia);

            if (comprovantePagamento.NumeroContaOption.IsSet)
                writer.WriteNumber("numeroConta", comprovantePagamento.NumeroContaOption.Value!.Value);

            if (comprovantePagamento.NomeProprietarioContaCorrenteOption.IsSet)
                writer.WriteString("nomeProprietarioContaCorrente", comprovantePagamento.NomeProprietarioContaCorrente);

            if (comprovantePagamento.NumeroCpfCnpjBeneficiarioOption.IsSet)
                writer.WriteString("numeroCpfCnpjBeneficiario", comprovantePagamento.NumeroCpfCnpjBeneficiario);

            if (comprovantePagamento.NomeRazaoSocialBeneficiarioOption.IsSet)
                writer.WriteString("nomeRazaoSocialBeneficiario", comprovantePagamento.NomeRazaoSocialBeneficiario);

            if (comprovantePagamento.NomeFantasiaBeneficiarioOption.IsSet)
                writer.WriteString("nomeFantasiaBeneficiario", comprovantePagamento.NomeFantasiaBeneficiario);

            if (comprovantePagamento.NumeroCpfCnpjBeneficiarioFinalOption.IsSet)
                writer.WriteString("numeroCpfCnpjBeneficiarioFinal", comprovantePagamento.NumeroCpfCnpjBeneficiarioFinal);

            if (comprovantePagamento.NomeRazaoSocialBeneficiarioFinalOption.IsSet)
                writer.WriteString("nomeRazaoSocialBeneficiarioFinal", comprovantePagamento.NomeRazaoSocialBeneficiarioFinal);

            if (comprovantePagamento.NomeFantasiaBeneficiarioFinalOption.IsSet)
                writer.WriteString("nomeFantasiaBeneficiarioFinal", comprovantePagamento.NomeFantasiaBeneficiarioFinal);

            if (comprovantePagamento.NumeroCpfCnpjPagadorOption.IsSet)
                writer.WriteString("numeroCpfCnpjPagador", comprovantePagamento.NumeroCpfCnpjPagador);

            if (comprovantePagamento.NomeRazaoSocialPagadorOption.IsSet)
                writer.WriteString("nomeRazaoSocialPagador", comprovantePagamento.NomeRazaoSocialPagador);

            if (comprovantePagamento.NomeFantasiaPagadorOption.IsSet)
                writer.WriteString("nomeFantasiaPagador", comprovantePagamento.NomeFantasiaPagador);

            if (comprovantePagamento.NossoNumeroOption.IsSet)
                writer.WriteString("nossoNumero", comprovantePagamento.NossoNumero);

            if (comprovantePagamento.NumeroDocumentoOption.IsSet)
                writer.WriteString("numeroDocumento", comprovantePagamento.NumeroDocumento);

            if (comprovantePagamento.DescricaoObservacaoOption.IsSet)
                writer.WriteString("descricaoObservacao", comprovantePagamento.DescricaoObservacao);

            if (comprovantePagamento.NumeroAutenticacaoPagamentoOption.IsSet)
                writer.WriteString("numeroAutenticacaoPagamento", comprovantePagamento.NumeroAutenticacaoPagamento);
        }
    }
}
