/*
 * Investimentos
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Sicoob.Investimentos.Api;
using Sicoob.Investimentos.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Sicoob.Investimentos.Test.Api
{
    /// <summary>
    ///  Class for testing ResgateApi
    /// </summary>
    public sealed class ResgateApiTests : ApiTestsBase
    {
        private readonly IResgateApi _instance;

        public ResgateApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IResgateApi>();
        }

        /// <summary>
        /// Test RendaFixaResgatesPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RendaFixaResgatesPostAsyncTest()
        {
            string clientId = default!;
            ResgateInteligenteCapRem resgateInteligenteCapRem = default!;
            var response = await _instance.RendaFixaResgatesPostAsync(clientId, resgateInteligenteCapRem);
            var model = response.Ok();
            Assert.IsType<RendaFixaResgatesPost200Response>(model);
        }
    }
}
