/*
 * Poupança
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/poupanca/v3 ]</pre> # Poupança API Sistema que faz a gestão das contas de poupança através de transãções como Aplicação, Resgate, Saldo, Extrato e Controle de Rentabilidade. 
 *
 * The version of the OpenAPI document: 3.0.4.0
 * Contact: marco.martins@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.Poupanca.Model;
using Sicoob.Poupanca.Client;
using System.Reflection;

namespace Sicoob.Poupanca.Test.Model
{
    /// <summary>
    ///  Class for testing TransferenciaDebtorAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferenciaDebtorAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransferenciaDebtorAccount
        //private TransferenciaDebtorAccount instance;

        public TransferenciaDebtorAccountTests()
        {
            // TODO uncomment below to create an instance of TransferenciaDebtorAccount
            //instance = new TransferenciaDebtorAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferenciaDebtorAccount
        /// </summary>
        [Fact]
        public void TransferenciaDebtorAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransferenciaDebtorAccount
            //Assert.IsType<TransferenciaDebtorAccount>(instance);
        }

        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

        /// <summary>
        /// Test the property 'PersonType'
        /// </summary>
        [Fact]
        public void PersonTypeTest()
        {
            // TODO unit test for the property 'PersonType'
        }
    }
}
