/*
 *  Open Finance - Iniciação de Pagamento 
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/payments/v2/itp ]</pre> A API tem como propósito viabiliza a criação, consulta e autorização dos consentimentos para pagamento entre bancos, instituições financeiras e é acessível também à estabelecimentos comerciais participantes do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.1.2.0
 * Contact: tiago.santos@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Sicoob.OpenFinance.Api;
using Sicoob.OpenFinance.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Sicoob.OpenFinance.Test.Api
{
    /// <summary>
    ///  Class for testing IniciadorDeTransaesDePagamentoApi
    /// </summary>
    public sealed class IniciadorDeTransaesDePagamentoApiTests : ApiTestsBase
    {
        private readonly IIniciadorDeTransaesDePagamentoApi _instance;

        public IniciadorDeTransaesDePagamentoApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IIniciadorDeTransaesDePagamentoApi>();
        }

        /// <summary>
        /// Test BuscarConsentimentoExternoIniciadoraUsingGET
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BuscarConsentimentoExternoIniciadoraUsingGETAsyncTest()
        {
            string cpf = default!;
            string consentId = default!;
            string clientId = default!;
            Client.Option<string> cnpj = default!;
            var response = await _instance.BuscarConsentimentoExternoIniciadoraUsingGETAsync(cpf, consentId, clientId, cnpj);
            var model = response.Ok();
            Assert.IsType<ConsentimentoPagamentoIniciacao>(model);
        }

        /// <summary>
        /// Test CriarConsentimentoUsingPOST1
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CriarConsentimentoUsingPOST1AsyncTest()
        {
            string clientId = default!;
            ConsentimentoSolicitacaoIniciacao solicitacao = default!;
            var response = await _instance.CriarConsentimentoUsingPOST1Async(clientId, solicitacao);
            var model = response.Created();
            Assert.IsType<RetornoConsentimentoPagamentoIniciadoraIniciacao>(model);
        }

        /// <summary>
        /// Test ListarUsingGET3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListarUsingGET3AsyncTest()
        {
            string cpf = default!;
            string status = default!;
            string clientId = default!;
            Client.Option<string> cnpj = default!;
            Client.Option<string> accountNumbe = default!;
            Client.Option<int> page = default!;
            Client.Option<int> pageSize = default!;
            var response = await _instance.ListarUsingGET3Async(cpf, status, clientId, cnpj, accountNumbe, page, pageSize);
            var model = response.Ok();
            Assert.IsType<PageConsentimentoPagamentoIniciacao>(model);
        }

        /// <summary>
        /// Test RetornoAutorizacaoUsingPOST1
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RetornoAutorizacaoUsingPOST1AsyncTest()
        {
            string clientId = default!;
            CallbackDataRequest callbackDataRequest = default!;
            var response = await _instance.RetornoAutorizacaoUsingPOST1Async(clientId, callbackDataRequest);
            var model = response.Ok();
            Assert.IsType<ConsentimentoPagamentoIniciacaoRetorno>(model);
        }
    }
}
