// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// Os campos aninhados sob o identificador calendário organizam informações a respeito de controle de tempo da cobrança.
    /// </summary>
    public partial class CalendRio : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CalendRio" /> class.
        /// </summary>
        /// <param name="criacao">Timestamp que indica o momento em que foi criada a cobrança. Respeita o formato definido na RFC 3339.</param>
        /// <param name="expiracao">Tempo de vida da cobrança, especificado em segundos a partir da data de criação (Calendario.criacao) </param>
        [JsonConstructor]
        public CalendRio(DateTime criacao, int expiracao)
        {
            Criacao = criacao;
            Expiracao = expiracao;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Timestamp que indica o momento em que foi criada a cobrança. Respeita o formato definido na RFC 3339.
        /// </summary>
        /// <value>Timestamp que indica o momento em que foi criada a cobrança. Respeita o formato definido na RFC 3339.</value>
        [JsonPropertyName("criacao")]
        public DateTime Criacao { get; set; }

        /// <summary>
        /// Tempo de vida da cobrança, especificado em segundos a partir da data de criação (Calendario.criacao) 
        /// </summary>
        /// <value>Tempo de vida da cobrança, especificado em segundos a partir da data de criação (Calendario.criacao) </value>
        /* <example>3600</example> */
        [JsonPropertyName("expiracao")]
        public int Expiracao { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CalendRio {\n");
            sb.Append("  Criacao: ").Append(Criacao).Append("\n");
            sb.Append("  Expiracao: ").Append(Expiracao).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Expiracao (int) minimum
            if (this.Expiracao < (int)1)
            {
                yield return new ValidationResult("Invalid value for Expiracao, must be a value greater than or equal to 1.", new [] { "Expiracao" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CalendRio" />
    /// </summary>
    public class CalendRioJsonConverter : JsonConverter<CalendRio>
    {
        /// <summary>
        /// The format to use to serialize Criacao
        /// </summary>
        public static string CriacaoFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="CalendRio" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CalendRio Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> criacao = default;
            Option<int?> expiracao = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "criacao":
                            criacao = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "expiracao":
                            expiracao = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!criacao.IsSet)
                throw new ArgumentException("Property is required for class CalendRio.", nameof(criacao));

            if (!expiracao.IsSet)
                throw new ArgumentException("Property is required for class CalendRio.", nameof(expiracao));

            if (criacao.IsSet && criacao.Value == null)
                throw new ArgumentNullException(nameof(criacao), "Property is not nullable for class CalendRio.");

            if (expiracao.IsSet && expiracao.Value == null)
                throw new ArgumentNullException(nameof(expiracao), "Property is not nullable for class CalendRio.");

            return new CalendRio(criacao.Value!.Value!, expiracao.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CalendRio" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="calendRio"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CalendRio calendRio, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, calendRio, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CalendRio" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="calendRio"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CalendRio calendRio, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("criacao", calendRio.Criacao.ToString(CriacaoFormat));

            writer.WriteNumber("expiracao", calendRio.Expiracao);
        }
    }
}
