// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// CobsVConsultadas
    /// </summary>
    public partial class CobsVConsultadas : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CobsVConsultadas" /> class.
        /// </summary>
        /// <param name="parametros">parametros</param>
        /// <param name="cobs">cobs</param>
        [JsonConstructor]
        public CobsVConsultadas(ParametrosConsultaCob parametros, List<CobVCompleta> cobs)
        {
            Parametros = parametros;
            Cobs = cobs;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Parametros
        /// </summary>
        [JsonPropertyName("parametros")]
        public ParametrosConsultaCob Parametros { get; set; }

        /// <summary>
        /// Gets or Sets Cobs
        /// </summary>
        [JsonPropertyName("cobs")]
        public List<CobVCompleta> Cobs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CobsVConsultadas {\n");
            sb.Append("  Parametros: ").Append(Parametros).Append("\n");
            sb.Append("  Cobs: ").Append(Cobs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CobsVConsultadas" />
    /// </summary>
    public class CobsVConsultadasJsonConverter : JsonConverter<CobsVConsultadas>
    {
        /// <summary>
        /// Deserializes json to <see cref="CobsVConsultadas" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CobsVConsultadas Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ParametrosConsultaCob?> parametros = default;
            Option<List<CobVCompleta>?> cobs = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "parametros":
                            parametros = new Option<ParametrosConsultaCob?>(JsonSerializer.Deserialize<ParametrosConsultaCob>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cobs":
                            cobs = new Option<List<CobVCompleta>?>(JsonSerializer.Deserialize<List<CobVCompleta>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!parametros.IsSet)
                throw new ArgumentException("Property is required for class CobsVConsultadas.", nameof(parametros));

            if (!cobs.IsSet)
                throw new ArgumentException("Property is required for class CobsVConsultadas.", nameof(cobs));

            if (parametros.IsSet && parametros.Value == null)
                throw new ArgumentNullException(nameof(parametros), "Property is not nullable for class CobsVConsultadas.");

            if (cobs.IsSet && cobs.Value == null)
                throw new ArgumentNullException(nameof(cobs), "Property is not nullable for class CobsVConsultadas.");

            return new CobsVConsultadas(parametros.Value!, cobs.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CobsVConsultadas" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cobsVConsultadas"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CobsVConsultadas cobsVConsultadas, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, cobsVConsultadas, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CobsVConsultadas" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cobsVConsultadas"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CobsVConsultadas cobsVConsultadas, JsonSerializerOptions jsonSerializerOptions)
        {
            if (cobsVConsultadas.Parametros == null)
                throw new ArgumentNullException(nameof(cobsVConsultadas.Parametros), "Property is required for class CobsVConsultadas.");

            if (cobsVConsultadas.Cobs == null)
                throw new ArgumentNullException(nameof(cobsVConsultadas.Cobs), "Property is required for class CobsVConsultadas.");

            writer.WritePropertyName("parametros");
            JsonSerializer.Serialize(writer, cobsVConsultadas.Parametros, jsonSerializerOptions);
            writer.WritePropertyName("cobs");
            JsonSerializer.Serialize(writer, cobsVConsultadas.Cobs, jsonSerializerOptions);
        }
    }
}
