// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// DadosDevedor
    /// </summary>
    public partial class DadosDevedor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DadosDevedor" /> class.
        /// </summary>
        /// <param name="devedor">devedor</param>
        [JsonConstructor]
        public DadosDevedor(Option<DadosDevedorDevedor?> devedor = default)
        {
            DevedorOption = devedor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Devedor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DadosDevedorDevedor?> DevedorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Devedor
        /// </summary>
        [JsonPropertyName("devedor")]
        public DadosDevedorDevedor? Devedor { get { return this.DevedorOption.Value; } set { this.DevedorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DadosDevedor {\n");
            sb.Append("  Devedor: ").Append(Devedor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DadosDevedor" />
    /// </summary>
    public class DadosDevedorJsonConverter : JsonConverter<DadosDevedor>
    {
        /// <summary>
        /// Deserializes json to <see cref="DadosDevedor" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DadosDevedor Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DadosDevedorDevedor?> devedor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "devedor":
                            devedor = new Option<DadosDevedorDevedor?>(JsonSerializer.Deserialize<DadosDevedorDevedor>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (devedor.IsSet && devedor.Value == null)
                throw new ArgumentNullException(nameof(devedor), "Property is not nullable for class DadosDevedor.");

            return new DadosDevedor(devedor);
        }

        /// <summary>
        /// Serializes a <see cref="DadosDevedor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dadosDevedor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DadosDevedor dadosDevedor, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dadosDevedor, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DadosDevedor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dadosDevedor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DadosDevedor dadosDevedor, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dadosDevedor.DevedorOption.IsSet && dadosDevedor.Devedor == null)
                throw new ArgumentNullException(nameof(dadosDevedor.Devedor), "Property is required for class DadosDevedor.");

            if (dadosDevedor.DevedorOption.IsSet)
            {
                writer.WritePropertyName("devedor");
                JsonSerializer.Serialize(writer, dadosDevedor.Devedor, jsonSerializerOptions);
            }
        }
    }
}
