// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// InformaEsAdicionaisInner
    /// </summary>
    public partial class InformaEsAdicionaisInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InformaEsAdicionaisInner" /> class.
        /// </summary>
        /// <param name="nome">Nome do campo.</param>
        /// <param name="valor">Dados do campo.</param>
        [JsonConstructor]
        public InformaEsAdicionaisInner(string nome, string valor)
        {
            Nome = nome;
            Valor = valor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Nome do campo.
        /// </summary>
        /// <value>Nome do campo.</value>
        [JsonPropertyName("nome")]
        public string Nome { get; set; }

        /// <summary>
        /// Dados do campo.
        /// </summary>
        /// <value>Dados do campo.</value>
        [JsonPropertyName("valor")]
        public string Valor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InformaEsAdicionaisInner {\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Nome (string) maxLength
            if (this.Nome != null && this.Nome.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Nome, length must be less than 50.", new [] { "Nome" });
            }

            // Valor (string) maxLength
            if (this.Valor != null && this.Valor.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Valor, length must be less than 200.", new [] { "Valor" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InformaEsAdicionaisInner" />
    /// </summary>
    public class InformaEsAdicionaisInnerJsonConverter : JsonConverter<InformaEsAdicionaisInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="InformaEsAdicionaisInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InformaEsAdicionaisInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> nome = default;
            Option<string?> valor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nome":
                            nome = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "valor":
                            valor = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!nome.IsSet)
                throw new ArgumentException("Property is required for class InformaEsAdicionaisInner.", nameof(nome));

            if (!valor.IsSet)
                throw new ArgumentException("Property is required for class InformaEsAdicionaisInner.", nameof(valor));

            if (nome.IsSet && nome.Value == null)
                throw new ArgumentNullException(nameof(nome), "Property is not nullable for class InformaEsAdicionaisInner.");

            if (valor.IsSet && valor.Value == null)
                throw new ArgumentNullException(nameof(valor), "Property is not nullable for class InformaEsAdicionaisInner.");

            return new InformaEsAdicionaisInner(nome.Value!, valor.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InformaEsAdicionaisInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="informaEsAdicionaisInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InformaEsAdicionaisInner informaEsAdicionaisInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, informaEsAdicionaisInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InformaEsAdicionaisInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="informaEsAdicionaisInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InformaEsAdicionaisInner informaEsAdicionaisInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (informaEsAdicionaisInner.Nome == null)
                throw new ArgumentNullException(nameof(informaEsAdicionaisInner.Nome), "Property is required for class InformaEsAdicionaisInner.");

            if (informaEsAdicionaisInner.Valor == null)
                throw new ArgumentNullException(nameof(informaEsAdicionaisInner.Valor), "Property is required for class InformaEsAdicionaisInner.");

            writer.WriteString("nome", informaEsAdicionaisInner.Nome);

            writer.WriteString("valor", informaEsAdicionaisInner.Valor);
        }
    }
}
