// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// Informações sobre a rejeição da recorrência
    /// </summary>
    public partial class InformaEsSobreARejeiODaRecorrNcia : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InformaEsSobreARejeiODaRecorrNcia" /> class.
        /// </summary>
        /// <param name="codigo">Código da rejeição. Corresponde ao código de rejeição presente no catálogo de mensagens.</param>
        /// <param name="descricao">Descricao da causa da rejeição</param>
        [JsonConstructor]
        public InformaEsSobreARejeiODaRecorrNcia(CodigoEnum codigo, string descricao)
        {
            Codigo = codigo;
            Descricao = descricao;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Código da rejeição. Corresponde ao código de rejeição presente no catálogo de mensagens.
        /// </summary>
        /// <value>Código da rejeição. Corresponde ao código de rejeição presente no catálogo de mensagens.</value>
        public enum CodigoEnum
        {
            /// <summary>
            /// Enum AP13 for value: AP13
            /// </summary>
            AP13 = 1,

            /// <summary>
            /// Enum AP14 for value: AP14
            /// </summary>
            AP14 = 2
        }

        /// <summary>
        /// Returns a <see cref="CodigoEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CodigoEnum CodigoEnumFromString(string value)
        {
            if (value.Equals("AP13"))
                return CodigoEnum.AP13;

            if (value.Equals("AP14"))
                return CodigoEnum.AP14;

            throw new NotImplementedException($"Could not convert value to type CodigoEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CodigoEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CodigoEnum? CodigoEnumFromStringOrDefault(string value)
        {
            if (value.Equals("AP13"))
                return CodigoEnum.AP13;

            if (value.Equals("AP14"))
                return CodigoEnum.AP14;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CodigoEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CodigoEnumToJsonValue(CodigoEnum value)
        {
            if (value == CodigoEnum.AP13)
                return "AP13";

            if (value == CodigoEnum.AP14)
                return "AP14";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Código da rejeição. Corresponde ao código de rejeição presente no catálogo de mensagens.
        /// </summary>
        /// <value>Código da rejeição. Corresponde ao código de rejeição presente no catálogo de mensagens.</value>
        [JsonPropertyName("codigo")]
        public CodigoEnum Codigo { get; set; }

        /// <summary>
        /// Descricao da causa da rejeição
        /// </summary>
        /// <value>Descricao da causa da rejeição</value>
        [JsonPropertyName("descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InformaEsSobreARejeiODaRecorrNcia {\n");
            sb.Append("  Codigo: ").Append(Codigo).Append("\n");
            sb.Append("  Descricao: ").Append(Descricao).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Descricao (string) maxLength
            if (this.Descricao != null && this.Descricao.Length > 105)
            {
                yield return new ValidationResult("Invalid value for Descricao, length must be less than 105.", new [] { "Descricao" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InformaEsSobreARejeiODaRecorrNcia" />
    /// </summary>
    public class InformaEsSobreARejeiODaRecorrNciaJsonConverter : JsonConverter<InformaEsSobreARejeiODaRecorrNcia>
    {
        /// <summary>
        /// Deserializes json to <see cref="InformaEsSobreARejeiODaRecorrNcia" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InformaEsSobreARejeiODaRecorrNcia Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<InformaEsSobreARejeiODaRecorrNcia.CodigoEnum?> codigo = default;
            Option<string?> descricao = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "codigo":
                            string? codigoRawValue = utf8JsonReader.GetString();
                            if (codigoRawValue != null)
                                codigo = new Option<InformaEsSobreARejeiODaRecorrNcia.CodigoEnum?>(InformaEsSobreARejeiODaRecorrNcia.CodigoEnumFromStringOrDefault(codigoRawValue));
                            break;
                        case "descricao":
                            descricao = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!codigo.IsSet)
                throw new ArgumentException("Property is required for class InformaEsSobreARejeiODaRecorrNcia.", nameof(codigo));

            if (!descricao.IsSet)
                throw new ArgumentException("Property is required for class InformaEsSobreARejeiODaRecorrNcia.", nameof(descricao));

            if (codigo.IsSet && codigo.Value == null)
                throw new ArgumentNullException(nameof(codigo), "Property is not nullable for class InformaEsSobreARejeiODaRecorrNcia.");

            if (descricao.IsSet && descricao.Value == null)
                throw new ArgumentNullException(nameof(descricao), "Property is not nullable for class InformaEsSobreARejeiODaRecorrNcia.");

            return new InformaEsSobreARejeiODaRecorrNcia(codigo.Value!.Value!, descricao.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InformaEsSobreARejeiODaRecorrNcia" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="informaEsSobreARejeiODaRecorrNcia"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InformaEsSobreARejeiODaRecorrNcia informaEsSobreARejeiODaRecorrNcia, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, informaEsSobreARejeiODaRecorrNcia, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InformaEsSobreARejeiODaRecorrNcia" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="informaEsSobreARejeiODaRecorrNcia"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InformaEsSobreARejeiODaRecorrNcia informaEsSobreARejeiODaRecorrNcia, JsonSerializerOptions jsonSerializerOptions)
        {
            if (informaEsSobreARejeiODaRecorrNcia.Descricao == null)
                throw new ArgumentNullException(nameof(informaEsSobreARejeiODaRecorrNcia.Descricao), "Property is required for class InformaEsSobreARejeiODaRecorrNcia.");

            var codigoRawValue = InformaEsSobreARejeiODaRecorrNcia.CodigoEnumToJsonValue(informaEsSobreARejeiODaRecorrNcia.Codigo);
            writer.WriteString("codigo", codigoRawValue);
            writer.WriteString("descricao", informaEsSobreARejeiODaRecorrNcia.Descricao);
        }
    }
}
