// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// LoteCobVConsultado
    /// </summary>
    public partial class LoteCobVConsultado : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoteCobVConsultado" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="descricao">descricao</param>
        /// <param name="criacao">Timestamp que indica o momento em que foi criado o lote. Respeita o formato definido na RFC 3339.</param>
        /// <param name="cobsv">cobsv</param>
        [JsonConstructor]
        public LoteCobVConsultado(long id, string descricao, DateTime criacao, List<LoteCobVConsultadoCobsvInner> cobsv)
        {
            Id = id;
            Descricao = descricao;
            Criacao = criacao;
            Cobsv = cobsv;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Descricao
        /// </summary>
        [JsonPropertyName("descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// Timestamp que indica o momento em que foi criado o lote. Respeita o formato definido na RFC 3339.
        /// </summary>
        /// <value>Timestamp que indica o momento em que foi criado o lote. Respeita o formato definido na RFC 3339.</value>
        [JsonPropertyName("criacao")]
        public DateTime Criacao { get; set; }

        /// <summary>
        /// Gets or Sets Cobsv
        /// </summary>
        [JsonPropertyName("cobsv")]
        public List<LoteCobVConsultadoCobsvInner> Cobsv { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoteCobVConsultado {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Descricao: ").Append(Descricao).Append("\n");
            sb.Append("  Criacao: ").Append(Criacao).Append("\n");
            sb.Append("  Cobsv: ").Append(Cobsv).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LoteCobVConsultado" />
    /// </summary>
    public class LoteCobVConsultadoJsonConverter : JsonConverter<LoteCobVConsultado>
    {
        /// <summary>
        /// The format to use to serialize Criacao
        /// </summary>
        public static string CriacaoFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="LoteCobVConsultado" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LoteCobVConsultado Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<string?> descricao = default;
            Option<DateTime?> criacao = default;
            Option<List<LoteCobVConsultadoCobsvInner>?> cobsv = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "descricao":
                            descricao = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "criacao":
                            criacao = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "cobsv":
                            cobsv = new Option<List<LoteCobVConsultadoCobsvInner>?>(JsonSerializer.Deserialize<List<LoteCobVConsultadoCobsvInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class LoteCobVConsultado.", nameof(id));

            if (!descricao.IsSet)
                throw new ArgumentException("Property is required for class LoteCobVConsultado.", nameof(descricao));

            if (!criacao.IsSet)
                throw new ArgumentException("Property is required for class LoteCobVConsultado.", nameof(criacao));

            if (!cobsv.IsSet)
                throw new ArgumentException("Property is required for class LoteCobVConsultado.", nameof(cobsv));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LoteCobVConsultado.");

            if (descricao.IsSet && descricao.Value == null)
                throw new ArgumentNullException(nameof(descricao), "Property is not nullable for class LoteCobVConsultado.");

            if (criacao.IsSet && criacao.Value == null)
                throw new ArgumentNullException(nameof(criacao), "Property is not nullable for class LoteCobVConsultado.");

            if (cobsv.IsSet && cobsv.Value == null)
                throw new ArgumentNullException(nameof(cobsv), "Property is not nullable for class LoteCobVConsultado.");

            return new LoteCobVConsultado(id.Value!.Value!, descricao.Value!, criacao.Value!.Value!, cobsv.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="LoteCobVConsultado" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loteCobVConsultado"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LoteCobVConsultado loteCobVConsultado, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, loteCobVConsultado, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LoteCobVConsultado" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loteCobVConsultado"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LoteCobVConsultado loteCobVConsultado, JsonSerializerOptions jsonSerializerOptions)
        {
            if (loteCobVConsultado.Descricao == null)
                throw new ArgumentNullException(nameof(loteCobVConsultado.Descricao), "Property is required for class LoteCobVConsultado.");

            if (loteCobVConsultado.Cobsv == null)
                throw new ArgumentNullException(nameof(loteCobVConsultado.Cobsv), "Property is required for class LoteCobVConsultado.");

            writer.WriteNumber("id", loteCobVConsultado.Id);

            writer.WriteString("descricao", loteCobVConsultado.Descricao);

            writer.WriteString("criacao", loteCobVConsultado.Criacao.ToString(CriacaoFormat));

            writer.WritePropertyName("cobsv");
            JsonSerializer.Serialize(writer, loteCobVConsultado.Cobsv, jsonSerializerOptions);
        }
    }
}
