// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// Atributos de Configuração de Recorrência
    /// </summary>
    public partial class RecorrenciaGerada : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecorrenciaGerada" /> class.
        /// </summary>
        /// <param name="vinculo">vinculo</param>
        /// <param name="calendario">calendario</param>
        /// <param name="status">status</param>
        /// <param name="politicaRetentativa">politicaRetentativa</param>
        /// <param name="atualizacao">Histórico das mudanças de status da recorrência.</param>
        /// <param name="valor">valor</param>
        /// <param name="encerramento">encerramento</param>
        /// <param name="ativacao">ativacao</param>
        /// <param name="idRec"># Identificador da Recorrência  Regra de formação: - RAxxxxxxxxyyyyMMddkkkkkkkkkkk (29 caracteres; \&quot;case sensitive\&quot;, isso é, diferencia letras maiúsculas e minúsculas), sendo:   - \&quot;R\&quot;:  fixo (1 caractere). \&quot;R\&quot; para a recorrência criada dentro do Pix;   - \&quot;A\&quot;: identificação da possibilidade de novas tentativas, sendo possíveis os valores \&quot;R\&quot; ou \&quot;N\&quot; (1 caractere). \&quot;R\&quot; caso a recorrência permita novas tentativas de pagamento pós vencimento, ou \&quot;N\&quot; caso não permita novas tentativas.   - \&quot;xxxxxxxx\&quot;:  identificação do agente que presta serviço para o usuário recebedor que gerou o &lt;Id&gt;, podendo ser: o ISPB do participante direto, o ISPB do participante indireto ou os 8 primeiros dígitos do CNPJ do prestador de serviço de iniciação (8 caracteres numéricos [0-9]);   - \&quot;yyyyMMdd\&quot;:  data (8 caracteres) de criação da recorrência;   - \&quot;kkkkkkkkkkk\&quot;: sequencial criado pelo agente que gerou o &lt;Id&gt; (11 caracteres alfanuméricos [a-z|A-Z|0-9]). Deve ser único dentro de cada \&quot;yyyyMMdd\&quot;.  Dessa forma, o ID da recorrência deve ser formado de acordo com um dos tipos a seguir: - \&quot;RRxxxxxxxxyyyyMMddkkkkkkkkkkk\&quot;; para recorrência criada dentro do Pix e que permite novas tentativas de pagamento pós vencimento; ou - \&quot;RNxxxxxxxxyyyyMMddkkkkkkkkkkk\&quot;; para recorrência criada dentro do Pix e que não permite novas tentativas de pagamento pós vencimento.”</param>
        /// <param name="recebedor">recebedor</param>
        /// <param name="pagador">pagador</param>
        /// <param name="autorizacao">autorizacao</param>
        /// <param name="loc">loc</param>
        [JsonConstructor]
        public RecorrenciaGerada(DescriODoObjetoDaRecorrNcia vinculo, InformaEsSobreCalendRioDaRecorrNcia calendario, StatusEnum status, PoliticaRetentativaEnum politicaRetentativa, List<HistRicoDeStatusInner2> atualizacao, Option<RecorrenciaBaseValor?> valor = default, Option<DetalhamentoDoEncerramentoDaRecorrNcia?> encerramento = default, Option<DadosRelacionadosConfirmaODaAtivaODaRecorrNcia?> ativacao = default, Option<string?> idRec = default, Option<RecorrenciaGeradaAllOfRecebedor?> recebedor = default, Option<RecorrenciaGeradaAllOfPagador?> pagador = default, Option<AutorizacaoRecorrenciaGerada?> autorizacao = default, Option<LocationDoPayloadCompleta?> loc = default)
        {
            Vinculo = vinculo;
            Calendario = calendario;
            Status = status;
            PoliticaRetentativa = politicaRetentativa;
            Atualizacao = atualizacao;
            ValorOption = valor;
            EncerramentoOption = encerramento;
            AtivacaoOption = ativacao;
            IdRecOption = idRec;
            RecebedorOption = recebedor;
            PagadorOption = pagador;
            AutorizacaoOption = autorizacao;
            LocOption = loc;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum CRIADA for value: CRIADA
            /// </summary>
            CRIADA = 1,

            /// <summary>
            /// Enum APROVADA for value: APROVADA
            /// </summary>
            APROVADA = 2,

            /// <summary>
            /// Enum REJEITADA for value: REJEITADA
            /// </summary>
            REJEITADA = 3,

            /// <summary>
            /// Enum EXPIRADA for value: EXPIRADA
            /// </summary>
            EXPIRADA = 4,

            /// <summary>
            /// Enum CANCELADA for value: CANCELADA
            /// </summary>
            CANCELADA = 5
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("CRIADA"))
                return StatusEnum.CRIADA;

            if (value.Equals("APROVADA"))
                return StatusEnum.APROVADA;

            if (value.Equals("REJEITADA"))
                return StatusEnum.REJEITADA;

            if (value.Equals("EXPIRADA"))
                return StatusEnum.EXPIRADA;

            if (value.Equals("CANCELADA"))
                return StatusEnum.CANCELADA;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("CRIADA"))
                return StatusEnum.CRIADA;

            if (value.Equals("APROVADA"))
                return StatusEnum.APROVADA;

            if (value.Equals("REJEITADA"))
                return StatusEnum.REJEITADA;

            if (value.Equals("EXPIRADA"))
                return StatusEnum.EXPIRADA;

            if (value.Equals("CANCELADA"))
                return StatusEnum.CANCELADA;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.CRIADA)
                return "CRIADA";

            if (value == StatusEnum.APROVADA)
                return "APROVADA";

            if (value == StatusEnum.REJEITADA)
                return "REJEITADA";

            if (value == StatusEnum.EXPIRADA)
                return "EXPIRADA";

            if (value == StatusEnum.CANCELADA)
                return "CANCELADA";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Defines PoliticaRetentativa
        /// </summary>
        public enum PoliticaRetentativaEnum
        {
            /// <summary>
            /// Enum NAOPERMITE for value: NAO_PERMITE
            /// </summary>
            NAOPERMITE = 1,

            /// <summary>
            /// Enum PERMITE3R7D for value: PERMITE_3R_7D
            /// </summary>
            PERMITE3R7D = 2
        }

        /// <summary>
        /// Returns a <see cref="PoliticaRetentativaEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static PoliticaRetentativaEnum PoliticaRetentativaEnumFromString(string value)
        {
            if (value.Equals("NAO_PERMITE"))
                return PoliticaRetentativaEnum.NAOPERMITE;

            if (value.Equals("PERMITE_3R_7D"))
                return PoliticaRetentativaEnum.PERMITE3R7D;

            throw new NotImplementedException($"Could not convert value to type PoliticaRetentativaEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="PoliticaRetentativaEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PoliticaRetentativaEnum? PoliticaRetentativaEnumFromStringOrDefault(string value)
        {
            if (value.Equals("NAO_PERMITE"))
                return PoliticaRetentativaEnum.NAOPERMITE;

            if (value.Equals("PERMITE_3R_7D"))
                return PoliticaRetentativaEnum.PERMITE3R7D;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PoliticaRetentativaEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string PoliticaRetentativaEnumToJsonValue(PoliticaRetentativaEnum value)
        {
            if (value == PoliticaRetentativaEnum.NAOPERMITE)
                return "NAO_PERMITE";

            if (value == PoliticaRetentativaEnum.PERMITE3R7D)
                return "PERMITE_3R_7D";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets PoliticaRetentativa
        /// </summary>
        [JsonPropertyName("politicaRetentativa")]
        public PoliticaRetentativaEnum PoliticaRetentativa { get; set; }

        /// <summary>
        /// Gets or Sets Vinculo
        /// </summary>
        [JsonPropertyName("vinculo")]
        public DescriODoObjetoDaRecorrNcia Vinculo { get; set; }

        /// <summary>
        /// Gets or Sets Calendario
        /// </summary>
        [JsonPropertyName("calendario")]
        public InformaEsSobreCalendRioDaRecorrNcia Calendario { get; set; }

        /// <summary>
        /// Histórico das mudanças de status da recorrência.
        /// </summary>
        /// <value>Histórico das mudanças de status da recorrência.</value>
        [JsonPropertyName("atualizacao")]
        public List<HistRicoDeStatusInner2> Atualizacao { get; set; }

        /// <summary>
        /// Used to track the state of Valor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RecorrenciaBaseValor?> ValorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Valor
        /// </summary>
        [JsonPropertyName("valor")]
        public RecorrenciaBaseValor? Valor { get { return this.ValorOption.Value; } set { this.ValorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Encerramento
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DetalhamentoDoEncerramentoDaRecorrNcia?> EncerramentoOption { get; private set; }

        /// <summary>
        /// Gets or Sets Encerramento
        /// </summary>
        [JsonPropertyName("encerramento")]
        public DetalhamentoDoEncerramentoDaRecorrNcia? Encerramento { get { return this.EncerramentoOption.Value; } set { this.EncerramentoOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ativacao
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DadosRelacionadosConfirmaODaAtivaODaRecorrNcia?> AtivacaoOption { get; private set; }

        /// <summary>
        /// Gets or Sets Ativacao
        /// </summary>
        [JsonPropertyName("ativacao")]
        public DadosRelacionadosConfirmaODaAtivaODaRecorrNcia? Ativacao { get { return this.AtivacaoOption.Value; } set { this.AtivacaoOption = new(value); } }

        /// <summary>
        /// Used to track the state of IdRec
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdRecOption { get; private set; }

        /// <summary>
        /// # Identificador da Recorrência  Regra de formação: - RAxxxxxxxxyyyyMMddkkkkkkkkkkk (29 caracteres; \&quot;case sensitive\&quot;, isso é, diferencia letras maiúsculas e minúsculas), sendo:   - \&quot;R\&quot;:  fixo (1 caractere). \&quot;R\&quot; para a recorrência criada dentro do Pix;   - \&quot;A\&quot;: identificação da possibilidade de novas tentativas, sendo possíveis os valores \&quot;R\&quot; ou \&quot;N\&quot; (1 caractere). \&quot;R\&quot; caso a recorrência permita novas tentativas de pagamento pós vencimento, ou \&quot;N\&quot; caso não permita novas tentativas.   - \&quot;xxxxxxxx\&quot;:  identificação do agente que presta serviço para o usuário recebedor que gerou o &lt;Id&gt;, podendo ser: o ISPB do participante direto, o ISPB do participante indireto ou os 8 primeiros dígitos do CNPJ do prestador de serviço de iniciação (8 caracteres numéricos [0-9]);   - \&quot;yyyyMMdd\&quot;:  data (8 caracteres) de criação da recorrência;   - \&quot;kkkkkkkkkkk\&quot;: sequencial criado pelo agente que gerou o &lt;Id&gt; (11 caracteres alfanuméricos [a-z|A-Z|0-9]). Deve ser único dentro de cada \&quot;yyyyMMdd\&quot;.  Dessa forma, o ID da recorrência deve ser formado de acordo com um dos tipos a seguir: - \&quot;RRxxxxxxxxyyyyMMddkkkkkkkkkkk\&quot;; para recorrência criada dentro do Pix e que permite novas tentativas de pagamento pós vencimento; ou - \&quot;RNxxxxxxxxyyyyMMddkkkkkkkkkkk\&quot;; para recorrência criada dentro do Pix e que não permite novas tentativas de pagamento pós vencimento.”
        /// </summary>
        /// <value># Identificador da Recorrência  Regra de formação: - RAxxxxxxxxyyyyMMddkkkkkkkkkkk (29 caracteres; \&quot;case sensitive\&quot;, isso é, diferencia letras maiúsculas e minúsculas), sendo:   - \&quot;R\&quot;:  fixo (1 caractere). \&quot;R\&quot; para a recorrência criada dentro do Pix;   - \&quot;A\&quot;: identificação da possibilidade de novas tentativas, sendo possíveis os valores \&quot;R\&quot; ou \&quot;N\&quot; (1 caractere). \&quot;R\&quot; caso a recorrência permita novas tentativas de pagamento pós vencimento, ou \&quot;N\&quot; caso não permita novas tentativas.   - \&quot;xxxxxxxx\&quot;:  identificação do agente que presta serviço para o usuário recebedor que gerou o &lt;Id&gt;, podendo ser: o ISPB do participante direto, o ISPB do participante indireto ou os 8 primeiros dígitos do CNPJ do prestador de serviço de iniciação (8 caracteres numéricos [0-9]);   - \&quot;yyyyMMdd\&quot;:  data (8 caracteres) de criação da recorrência;   - \&quot;kkkkkkkkkkk\&quot;: sequencial criado pelo agente que gerou o &lt;Id&gt; (11 caracteres alfanuméricos [a-z|A-Z|0-9]). Deve ser único dentro de cada \&quot;yyyyMMdd\&quot;.  Dessa forma, o ID da recorrência deve ser formado de acordo com um dos tipos a seguir: - \&quot;RRxxxxxxxxyyyyMMddkkkkkkkkkkk\&quot;; para recorrência criada dentro do Pix e que permite novas tentativas de pagamento pós vencimento; ou - \&quot;RNxxxxxxxxyyyyMMddkkkkkkkkkkk\&quot;; para recorrência criada dentro do Pix e que não permite novas tentativas de pagamento pós vencimento.”</value>
        /* <example>RR1234567820240115abcdefghijk</example> */
        [JsonPropertyName("idRec")]
        public string? IdRec { get { return this.IdRecOption.Value; } set { this.IdRecOption = new(value); } }

        /// <summary>
        /// Used to track the state of Recebedor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RecorrenciaGeradaAllOfRecebedor?> RecebedorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Recebedor
        /// </summary>
        [JsonPropertyName("recebedor")]
        public RecorrenciaGeradaAllOfRecebedor? Recebedor { get { return this.RecebedorOption.Value; } set { this.RecebedorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Pagador
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RecorrenciaGeradaAllOfPagador?> PagadorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pagador
        /// </summary>
        [JsonPropertyName("pagador")]
        public RecorrenciaGeradaAllOfPagador? Pagador { get { return this.PagadorOption.Value; } set { this.PagadorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Autorizacao
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AutorizacaoRecorrenciaGerada?> AutorizacaoOption { get; private set; }

        /// <summary>
        /// Gets or Sets Autorizacao
        /// </summary>
        [JsonPropertyName("autorizacao")]
        public AutorizacaoRecorrenciaGerada? Autorizacao { get { return this.AutorizacaoOption.Value; } set { this.AutorizacaoOption = new(value); } }

        /// <summary>
        /// Used to track the state of Loc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LocationDoPayloadCompleta?> LocOption { get; private set; }

        /// <summary>
        /// Gets or Sets Loc
        /// </summary>
        [JsonPropertyName("loc")]
        public LocationDoPayloadCompleta? Loc { get { return this.LocOption.Value; } set { this.LocOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecorrenciaGerada {\n");
            sb.Append("  Vinculo: ").Append(Vinculo).Append("\n");
            sb.Append("  Calendario: ").Append(Calendario).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  PoliticaRetentativa: ").Append(PoliticaRetentativa).Append("\n");
            sb.Append("  Atualizacao: ").Append(Atualizacao).Append("\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("  Encerramento: ").Append(Encerramento).Append("\n");
            sb.Append("  Ativacao: ").Append(Ativacao).Append("\n");
            sb.Append("  IdRec: ").Append(IdRec).Append("\n");
            sb.Append("  Recebedor: ").Append(Recebedor).Append("\n");
            sb.Append("  Pagador: ").Append(Pagador).Append("\n");
            sb.Append("  Autorizacao: ").Append(Autorizacao).Append("\n");
            sb.Append("  Loc: ").Append(Loc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IdRec (string) maxLength
            if (this.IdRec != null && this.IdRec.Length > 29)
            {
                yield return new ValidationResult("Invalid value for IdRec, length must be less than 29.", new [] { "IdRec" });
            }

            // IdRec (string) minLength
            if (this.IdRec != null && this.IdRec.Length < 29)
            {
                yield return new ValidationResult("Invalid value for IdRec, length must be greater than 29.", new [] { "IdRec" });
            }

            if (this.IdRecOption.Value != null) {
                // IdRec (string) pattern
                Regex regexIdRec = new Regex(@"[a-zA-Z0-9]{29}", RegexOptions.CultureInvariant);

                if (this.IdRecOption.Value != null &&!regexIdRec.Match(this.IdRecOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for IdRec, must match a pattern of " + regexIdRec, new [] { "IdRec" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RecorrenciaGerada" />
    /// </summary>
    public class RecorrenciaGeradaJsonConverter : JsonConverter<RecorrenciaGerada>
    {
        /// <summary>
        /// Deserializes json to <see cref="RecorrenciaGerada" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RecorrenciaGerada Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DescriODoObjetoDaRecorrNcia?> vinculo = default;
            Option<InformaEsSobreCalendRioDaRecorrNcia?> calendario = default;
            Option<RecorrenciaGerada.StatusEnum?> status = default;
            Option<RecorrenciaGerada.PoliticaRetentativaEnum?> politicaRetentativa = default;
            Option<List<HistRicoDeStatusInner2>?> atualizacao = default;
            Option<RecorrenciaBaseValor?> valor = default;
            Option<DetalhamentoDoEncerramentoDaRecorrNcia?> encerramento = default;
            Option<DadosRelacionadosConfirmaODaAtivaODaRecorrNcia?> ativacao = default;
            Option<string?> idRec = default;
            Option<RecorrenciaGeradaAllOfRecebedor?> recebedor = default;
            Option<RecorrenciaGeradaAllOfPagador?> pagador = default;
            Option<AutorizacaoRecorrenciaGerada?> autorizacao = default;
            Option<LocationDoPayloadCompleta?> loc = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "vinculo":
                            vinculo = new Option<DescriODoObjetoDaRecorrNcia?>(JsonSerializer.Deserialize<DescriODoObjetoDaRecorrNcia>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "calendario":
                            calendario = new Option<InformaEsSobreCalendRioDaRecorrNcia?>(JsonSerializer.Deserialize<InformaEsSobreCalendRioDaRecorrNcia>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<RecorrenciaGerada.StatusEnum?>(RecorrenciaGerada.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "politicaRetentativa":
                            string? politicaRetentativaRawValue = utf8JsonReader.GetString();
                            if (politicaRetentativaRawValue != null)
                                politicaRetentativa = new Option<RecorrenciaGerada.PoliticaRetentativaEnum?>(RecorrenciaGerada.PoliticaRetentativaEnumFromStringOrDefault(politicaRetentativaRawValue));
                            break;
                        case "atualizacao":
                            atualizacao = new Option<List<HistRicoDeStatusInner2>?>(JsonSerializer.Deserialize<List<HistRicoDeStatusInner2>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "valor":
                            valor = new Option<RecorrenciaBaseValor?>(JsonSerializer.Deserialize<RecorrenciaBaseValor>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "encerramento":
                            encerramento = new Option<DetalhamentoDoEncerramentoDaRecorrNcia?>(JsonSerializer.Deserialize<DetalhamentoDoEncerramentoDaRecorrNcia>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ativacao":
                            ativacao = new Option<DadosRelacionadosConfirmaODaAtivaODaRecorrNcia?>(JsonSerializer.Deserialize<DadosRelacionadosConfirmaODaAtivaODaRecorrNcia>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "idRec":
                            idRec = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "recebedor":
                            recebedor = new Option<RecorrenciaGeradaAllOfRecebedor?>(JsonSerializer.Deserialize<RecorrenciaGeradaAllOfRecebedor>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "pagador":
                            pagador = new Option<RecorrenciaGeradaAllOfPagador?>(JsonSerializer.Deserialize<RecorrenciaGeradaAllOfPagador>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "autorizacao":
                            autorizacao = new Option<AutorizacaoRecorrenciaGerada?>(JsonSerializer.Deserialize<AutorizacaoRecorrenciaGerada>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "loc":
                            loc = new Option<LocationDoPayloadCompleta?>(JsonSerializer.Deserialize<LocationDoPayloadCompleta>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!vinculo.IsSet)
                throw new ArgumentException("Property is required for class RecorrenciaGerada.", nameof(vinculo));

            if (!calendario.IsSet)
                throw new ArgumentException("Property is required for class RecorrenciaGerada.", nameof(calendario));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class RecorrenciaGerada.", nameof(status));

            if (!politicaRetentativa.IsSet)
                throw new ArgumentException("Property is required for class RecorrenciaGerada.", nameof(politicaRetentativa));

            if (!atualizacao.IsSet)
                throw new ArgumentException("Property is required for class RecorrenciaGerada.", nameof(atualizacao));

            if (vinculo.IsSet && vinculo.Value == null)
                throw new ArgumentNullException(nameof(vinculo), "Property is not nullable for class RecorrenciaGerada.");

            if (calendario.IsSet && calendario.Value == null)
                throw new ArgumentNullException(nameof(calendario), "Property is not nullable for class RecorrenciaGerada.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class RecorrenciaGerada.");

            if (politicaRetentativa.IsSet && politicaRetentativa.Value == null)
                throw new ArgumentNullException(nameof(politicaRetentativa), "Property is not nullable for class RecorrenciaGerada.");

            if (atualizacao.IsSet && atualizacao.Value == null)
                throw new ArgumentNullException(nameof(atualizacao), "Property is not nullable for class RecorrenciaGerada.");

            if (valor.IsSet && valor.Value == null)
                throw new ArgumentNullException(nameof(valor), "Property is not nullable for class RecorrenciaGerada.");

            if (encerramento.IsSet && encerramento.Value == null)
                throw new ArgumentNullException(nameof(encerramento), "Property is not nullable for class RecorrenciaGerada.");

            if (ativacao.IsSet && ativacao.Value == null)
                throw new ArgumentNullException(nameof(ativacao), "Property is not nullable for class RecorrenciaGerada.");

            if (idRec.IsSet && idRec.Value == null)
                throw new ArgumentNullException(nameof(idRec), "Property is not nullable for class RecorrenciaGerada.");

            if (recebedor.IsSet && recebedor.Value == null)
                throw new ArgumentNullException(nameof(recebedor), "Property is not nullable for class RecorrenciaGerada.");

            if (pagador.IsSet && pagador.Value == null)
                throw new ArgumentNullException(nameof(pagador), "Property is not nullable for class RecorrenciaGerada.");

            if (autorizacao.IsSet && autorizacao.Value == null)
                throw new ArgumentNullException(nameof(autorizacao), "Property is not nullable for class RecorrenciaGerada.");

            if (loc.IsSet && loc.Value == null)
                throw new ArgumentNullException(nameof(loc), "Property is not nullable for class RecorrenciaGerada.");

            return new RecorrenciaGerada(vinculo.Value!, calendario.Value!, status.Value!.Value!, politicaRetentativa.Value!.Value!, atualizacao.Value!, valor, encerramento, ativacao, idRec, recebedor, pagador, autorizacao, loc);
        }

        /// <summary>
        /// Serializes a <see cref="RecorrenciaGerada" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recorrenciaGerada"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RecorrenciaGerada recorrenciaGerada, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, recorrenciaGerada, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RecorrenciaGerada" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recorrenciaGerada"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RecorrenciaGerada recorrenciaGerada, JsonSerializerOptions jsonSerializerOptions)
        {
            if (recorrenciaGerada.Vinculo == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Vinculo), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.Calendario == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Calendario), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.Atualizacao == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Atualizacao), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.ValorOption.IsSet && recorrenciaGerada.Valor == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Valor), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.EncerramentoOption.IsSet && recorrenciaGerada.Encerramento == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Encerramento), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.AtivacaoOption.IsSet && recorrenciaGerada.Ativacao == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Ativacao), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.IdRecOption.IsSet && recorrenciaGerada.IdRec == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.IdRec), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.RecebedorOption.IsSet && recorrenciaGerada.Recebedor == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Recebedor), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.PagadorOption.IsSet && recorrenciaGerada.Pagador == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Pagador), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.AutorizacaoOption.IsSet && recorrenciaGerada.Autorizacao == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Autorizacao), "Property is required for class RecorrenciaGerada.");

            if (recorrenciaGerada.LocOption.IsSet && recorrenciaGerada.Loc == null)
                throw new ArgumentNullException(nameof(recorrenciaGerada.Loc), "Property is required for class RecorrenciaGerada.");

            writer.WritePropertyName("vinculo");
            JsonSerializer.Serialize(writer, recorrenciaGerada.Vinculo, jsonSerializerOptions);
            writer.WritePropertyName("calendario");
            JsonSerializer.Serialize(writer, recorrenciaGerada.Calendario, jsonSerializerOptions);
            var statusRawValue = RecorrenciaGerada.StatusEnumToJsonValue(recorrenciaGerada.Status);
            writer.WriteString("status", statusRawValue);
            var politicaRetentativaRawValue = RecorrenciaGerada.PoliticaRetentativaEnumToJsonValue(recorrenciaGerada.PoliticaRetentativa);
            writer.WriteString("politicaRetentativa", politicaRetentativaRawValue);
            writer.WritePropertyName("atualizacao");
            JsonSerializer.Serialize(writer, recorrenciaGerada.Atualizacao, jsonSerializerOptions);
            if (recorrenciaGerada.ValorOption.IsSet)
            {
                writer.WritePropertyName("valor");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Valor, jsonSerializerOptions);
            }
            if (recorrenciaGerada.EncerramentoOption.IsSet)
            {
                writer.WritePropertyName("encerramento");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Encerramento, jsonSerializerOptions);
            }
            if (recorrenciaGerada.AtivacaoOption.IsSet)
            {
                writer.WritePropertyName("ativacao");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Ativacao, jsonSerializerOptions);
            }
            if (recorrenciaGerada.IdRecOption.IsSet)
                writer.WriteString("idRec", recorrenciaGerada.IdRec);

            if (recorrenciaGerada.RecebedorOption.IsSet)
            {
                writer.WritePropertyName("recebedor");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Recebedor, jsonSerializerOptions);
            }
            if (recorrenciaGerada.PagadorOption.IsSet)
            {
                writer.WritePropertyName("pagador");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Pagador, jsonSerializerOptions);
            }
            if (recorrenciaGerada.AutorizacaoOption.IsSet)
            {
                writer.WritePropertyName("autorizacao");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Autorizacao, jsonSerializerOptions);
            }
            if (recorrenciaGerada.LocOption.IsSet)
            {
                writer.WritePropertyName("loc");
                JsonSerializer.Serialize(writer, recorrenciaGerada.Loc, jsonSerializerOptions);
            }
        }
    }
}
