// <auto-generated>
/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.Pix.Client;

namespace Sicoob.Pix.Model
{
    /// <summary>
    /// SolicRecAtualizacao
    /// </summary>
    public partial class SolicRecAtualizacao : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SolicRecAtualizacao" /> class.
        /// </summary>
        /// <param name="atualizacao">atualizacao</param>
        [JsonConstructor]
        public SolicRecAtualizacao(List<HistRicoDeStatusDaSolicitaODeRecorrNciaInner> atualizacao)
        {
            Atualizacao = atualizacao;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Atualizacao
        /// </summary>
        [JsonPropertyName("atualizacao")]
        public List<HistRicoDeStatusDaSolicitaODeRecorrNciaInner> Atualizacao { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SolicRecAtualizacao {\n");
            sb.Append("  Atualizacao: ").Append(Atualizacao).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SolicRecAtualizacao" />
    /// </summary>
    public class SolicRecAtualizacaoJsonConverter : JsonConverter<SolicRecAtualizacao>
    {
        /// <summary>
        /// Deserializes json to <see cref="SolicRecAtualizacao" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SolicRecAtualizacao Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<HistRicoDeStatusDaSolicitaODeRecorrNciaInner>?> atualizacao = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "atualizacao":
                            atualizacao = new Option<List<HistRicoDeStatusDaSolicitaODeRecorrNciaInner>?>(JsonSerializer.Deserialize<List<HistRicoDeStatusDaSolicitaODeRecorrNciaInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!atualizacao.IsSet)
                throw new ArgumentException("Property is required for class SolicRecAtualizacao.", nameof(atualizacao));

            if (atualizacao.IsSet && atualizacao.Value == null)
                throw new ArgumentNullException(nameof(atualizacao), "Property is not nullable for class SolicRecAtualizacao.");

            return new SolicRecAtualizacao(atualizacao.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SolicRecAtualizacao" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="solicRecAtualizacao"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SolicRecAtualizacao solicRecAtualizacao, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, solicRecAtualizacao, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SolicRecAtualizacao" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="solicRecAtualizacao"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SolicRecAtualizacao solicRecAtualizacao, JsonSerializerOptions jsonSerializerOptions)
        {
            if (solicRecAtualizacao.Atualizacao == null)
                throw new ArgumentNullException(nameof(solicRecAtualizacao.Atualizacao), "Property is required for class SolicRecAtualizacao.");

            writer.WritePropertyName("atualizacao");
            JsonSerializer.Serialize(writer, solicRecAtualizacao.Atualizacao, jsonSerializerOptions);
        }
    }
}
