/*
 * SPB Transferências
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/spb/v2 ]</pre> A API tem como propósito fornecer serviços para envio de TEDs.
 *
 * The version of the OpenAPI document: 1.0.4.2
 * Contact: rayana.silva@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;

namespace Sicoob.SpbTransferencias.Client
{
    /// <summary>
    /// Useful for tracking server health
    /// </summary>
    public class ExceptionEventArgs : EventArgs
    {
        /// <summary>
        /// The ApiResponse
        /// </summary>
        public Exception Exception { get; }

        /// <summary>
        /// The ExceptionEventArgs
        /// </summary>
        /// <param name="exception"></param>
        public ExceptionEventArgs(Exception exception)
        {
            Exception = exception;
        }
    }
}
