// <auto-generated>
/*
 * Conta Corrente
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/conta-corrente/v4 ]</pre>  # Conta Corrente API A API de Contas Correntes permite o acesso a dados de conta corrente como Saldo e Extrato. 
 *
 * The version of the OpenAPI document: 2.1.1.43
 * Contact: rafael.alves@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Text.Json;

namespace Sicoob.ContaCorrente.Client
{
    /// <summary>
    /// Provides the JsonSerializerOptions
    /// </summary>
    public class JsonSerializerOptionsProvider
    {
        /// <summary>
        /// the JsonSerializerOptions
        /// </summary>
        public JsonSerializerOptions Options { get; }

        /// <summary>
        /// Instantiates a JsonSerializerOptionsProvider
        /// </summary>
        public JsonSerializerOptionsProvider(JsonSerializerOptions options)
        {
            Options = options;
        }
    }
}
