/*
 * Investimentos
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.Investimentos.Model;
using Sicoob.Investimentos.Client;
using System.Reflection;

namespace Sicoob.Investimentos.Test.Model
{
    /// <summary>
    ///  Class for testing CriterioTaxaRemuneracaoModalidades
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CriterioTaxaRemuneracaoModalidadesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CriterioTaxaRemuneracaoModalidades
        //private CriterioTaxaRemuneracaoModalidades instance;

        public CriterioTaxaRemuneracaoModalidadesTests()
        {
            // TODO uncomment below to create an instance of CriterioTaxaRemuneracaoModalidades
            //instance = new CriterioTaxaRemuneracaoModalidades();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CriterioTaxaRemuneracaoModalidades
        /// </summary>
        [Fact]
        public void CriterioTaxaRemuneracaoModalidadesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CriterioTaxaRemuneracaoModalidades
            //Assert.IsType<CriterioTaxaRemuneracaoModalidades>(instance);
        }

        /// <summary>
        /// Test the property 'Ordinal'
        /// </summary>
        [Fact]
        public void OrdinalTest()
        {
            // TODO unit test for the property 'Ordinal'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
