// <auto-generated>
/*
 * Cobrança Bancária
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.CobrancaV3.Client;

namespace Sicoob.CobrancaV3.Model
{
    /// <summary>
    /// HealthGet200Response
    /// </summary>
    public partial class HealthGet200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthGet200Response" /> class.
        /// </summary>
        /// <param name="status">Status geral da aplicação</param>
        /// <param name="restHealthCheck">restHealthCheck</param>
        [JsonConstructor]
        public HealthGet200Response(Option<string?> status = default, Option<HealthGet200ResponseRestHealthCheck?> restHealthCheck = default)
        {
            StatusOption = status;
            RestHealthCheckOption = restHealthCheck;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Status geral da aplicação
        /// </summary>
        /// <value>Status geral da aplicação</value>
        /* <example>UP</example> */
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of RestHealthCheck
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<HealthGet200ResponseRestHealthCheck?> RestHealthCheckOption { get; private set; }

        /// <summary>
        /// Gets or Sets RestHealthCheck
        /// </summary>
        [JsonPropertyName("RestHealthCheck")]
        public HealthGet200ResponseRestHealthCheck? RestHealthCheck { get { return this.RestHealthCheckOption.Value; } set { this.RestHealthCheckOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HealthGet200Response {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RestHealthCheck: ").Append(RestHealthCheck).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HealthGet200Response" />
    /// </summary>
    public class HealthGet200ResponseJsonConverter : JsonConverter<HealthGet200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="HealthGet200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HealthGet200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<HealthGet200ResponseRestHealthCheck?> restHealthCheck = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "RestHealthCheck":
                            restHealthCheck = new Option<HealthGet200ResponseRestHealthCheck?>(JsonSerializer.Deserialize<HealthGet200ResponseRestHealthCheck>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class HealthGet200Response.");

            if (restHealthCheck.IsSet && restHealthCheck.Value == null)
                throw new ArgumentNullException(nameof(restHealthCheck), "Property is not nullable for class HealthGet200Response.");

            return new HealthGet200Response(status, restHealthCheck);
        }

        /// <summary>
        /// Serializes a <see cref="HealthGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HealthGet200Response healthGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, healthGet200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HealthGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HealthGet200Response healthGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (healthGet200Response.StatusOption.IsSet && healthGet200Response.Status == null)
                throw new ArgumentNullException(nameof(healthGet200Response.Status), "Property is required for class HealthGet200Response.");

            if (healthGet200Response.RestHealthCheckOption.IsSet && healthGet200Response.RestHealthCheck == null)
                throw new ArgumentNullException(nameof(healthGet200Response.RestHealthCheck), "Property is required for class HealthGet200Response.");

            if (healthGet200Response.StatusOption.IsSet)
                writer.WriteString("status", healthGet200Response.Status);

            if (healthGet200Response.RestHealthCheckOption.IsSet)
            {
                writer.WritePropertyName("RestHealthCheck");
                JsonSerializer.Serialize(writer, healthGet200Response.RestHealthCheck, jsonSerializerOptions);
            }
        }
    }
}
