/*
 * Pagamentos PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix-pagamentos/v2 ]</pre> API de pagamentos.
 *
 * The version of the OpenAPI document: 2.0.24.6
 * Contact: eduardod.silva@fornecedores.sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Sicoob.PagamentosPix.Api;
using Sicoob.PagamentosPix.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Sicoob.PagamentosPix.Test.Api
{
    /// <summary>
    ///  Class for testing APIDePagamentosPIXApi
    /// </summary>
    public sealed class APIDePagamentosPIXApiTests : ApiTestsBase
    {
        private readonly IAPIDePagamentosPIXApi _instance;

        public APIDePagamentosPIXApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAPIDePagamentosPIXApi>();
        }

        /// <summary>
        /// Test PagamentosConfirmacaoPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosConfirmacaoPostAsyncTest()
        {
            RequisicaoLancamentoEfetivacao requisicaoLancamentoEfetivacao = default!;
            var response = await _instance.PagamentosConfirmacaoPostAsync(requisicaoLancamentoEfetivacao);
            var model = response.Ok();
            Assert.IsType<RetornoPagamento>(model);
        }

        /// <summary>
        /// Test PagamentosIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosIdGetAsyncTest()
        {
            string id = default!;
            var response = await _instance.PagamentosIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RetornoPagamento>(model);
        }

        /// <summary>
        /// Test PagamentosPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosPostAsyncTest()
        {
            RequisicaoLancamentoIniciacao requisicaoLancamentoIniciacao = default!;
            var response = await _instance.PagamentosPostAsync(requisicaoLancamentoIniciacao);
            var model = response.Ok();
            Assert.IsType<PagamentoIniciadoDict>(model);
        }

        /// <summary>
        /// Test PagamentosQrcodePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosQrcodePostAsyncTest()
        {
            PagamentoIniciadoQRCodeBody pagamentoIniciadoQRCodeBody = default!;
            var response = await _instance.PagamentosQrcodePostAsync(pagamentoIniciadoQRCodeBody);
            var model = response.Ok();
            Assert.IsType<PagamentoIniciadoQRCodeResponse>(model);
        }

        /// <summary>
        /// Test PagamentosWebhookDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosWebhookDeleteAsyncTest()
        {
            await _instance.PagamentosWebhookDeleteAsync();
        }

        /// <summary>
        /// Test PagamentosWebhookGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosWebhookGetAsyncTest()
        {
            var response = await _instance.PagamentosWebhookGetAsync();
            var model = response.Ok();
            Assert.IsType<WebhookCompleto>(model);
        }

        /// <summary>
        /// Test PagamentosWebhookPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PagamentosWebhookPutAsyncTest()
        {
            WebhookSolicitado webhookSolicitado = default!;
            await _instance.PagamentosWebhookPutAsync(webhookSolicitado);
        }
    }
}
