/*
 *  Open Finance - Iniciação de Pagamento 
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/payments/v2/itp ]</pre> A API tem como propósito viabiliza a criação, consulta e autorização dos consentimentos para pagamento entre bancos, instituições financeiras e é acessível também à estabelecimentos comerciais participantes do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.1.2.0
 * Contact: tiago.santos@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.OpenFinance.Model;
using Sicoob.OpenFinance.Client;
using System.Reflection;

namespace Sicoob.OpenFinance.Test.Model
{
    /// <summary>
    ///  Class for testing AgendamentoUnico
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgendamentoUnicoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgendamentoUnico
        //private AgendamentoUnico instance;

        public AgendamentoUnicoTests()
        {
            // TODO uncomment below to create an instance of AgendamentoUnico
            //instance = new AgendamentoUnico();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgendamentoUnico
        /// </summary>
        [Fact]
        public void AgendamentoUnicoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgendamentoUnico
            //Assert.IsType<AgendamentoUnico>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
    }
}
