/*
 *  Open Finance - Iniciação de Pagamento 
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/payments/v2/itp ]</pre> A API tem como propósito viabiliza a criação, consulta e autorização dos consentimentos para pagamento entre bancos, instituições financeiras e é acessível também à estabelecimentos comerciais participantes do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.1.2.0
 * Contact: tiago.santos@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.OpenFinance.Model;
using Sicoob.OpenFinance.Client;
using System.Reflection;

namespace Sicoob.OpenFinance.Test.Model
{
    /// <summary>
    ///  Class for testing Pageable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PageableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Pageable
        //private Pageable instance;

        public PageableTests()
        {
            // TODO uncomment below to create an instance of Pageable
            //instance = new Pageable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Pageable
        /// </summary>
        [Fact]
        public void PageableInstanceTest()
        {
            // TODO uncomment below to test "IsType" Pageable
            //Assert.IsType<Pageable>(instance);
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Paged'
        /// </summary>
        [Fact]
        public void PagedTest()
        {
            // TODO unit test for the property 'Paged'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'Unpaged'
        /// </summary>
        [Fact]
        public void UnpagedTest()
        {
            // TODO unit test for the property 'Unpaged'
        }
    }
}
