/*
 * Cobrança Bancária Pagamentos
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pagamentos/v3 ]</pre> Esta API disponibiliza funcionalidades para realização de pagamentos de boletos de Cobrança Bancária.
 *
 * The version of the OpenAPI document: 3.0.2.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.PagamentosV3.Model;
using Sicoob.PagamentosV3.Client;
using System.Reflection;

namespace Sicoob.PagamentosV3.Test.Model
{
    /// <summary>
    ///  Class for testing SicoobMensagem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SicoobMensagemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SicoobMensagem
        //private SicoobMensagem instance;

        public SicoobMensagemTests()
        {
            // TODO uncomment below to create an instance of SicoobMensagem
            //instance = new SicoobMensagem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SicoobMensagem
        /// </summary>
        [Fact]
        public void SicoobMensagemInstanceTest()
        {
            // TODO uncomment below to test "IsType" SicoobMensagem
            //Assert.IsType<SicoobMensagem>(instance);
        }

        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Fact]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }

        /// <summary>
        /// Test the property 'Codigo'
        /// </summary>
        [Fact]
        public void CodigoTest()
        {
            // TODO unit test for the property 'Codigo'
        }
    }
}
