/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.Pix.Model;
using Sicoob.Pix.Client;
using System.Reflection;

namespace Sicoob.Pix.Test.Model
{
    /// <summary>
    ///  Class for testing HistRicoDeTentativasDeCobranAInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HistRicoDeTentativasDeCobranAInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HistRicoDeTentativasDeCobranAInner
        //private HistRicoDeTentativasDeCobranAInner instance;

        public HistRicoDeTentativasDeCobranAInnerTests()
        {
            // TODO uncomment below to create an instance of HistRicoDeTentativasDeCobranAInner
            //instance = new HistRicoDeTentativasDeCobranAInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HistRicoDeTentativasDeCobranAInner
        /// </summary>
        [Fact]
        public void HistRicoDeTentativasDeCobranAInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" HistRicoDeTentativasDeCobranAInner
            //Assert.IsType<HistRicoDeTentativasDeCobranAInner>(instance);
        }

        /// <summary>
        /// Test the property 'DataLiquidacao'
        /// </summary>
        [Fact]
        public void DataLiquidacaoTest()
        {
            // TODO unit test for the property 'DataLiquidacao'
        }

        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Fact]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'EndToEndId'
        /// </summary>
        [Fact]
        public void EndToEndIdTest()
        {
            // TODO unit test for the property 'EndToEndId'
        }

        /// <summary>
        /// Test the property 'Rejeicao'
        /// </summary>
        [Fact]
        public void RejeicaoTest()
        {
            // TODO unit test for the property 'Rejeicao'
        }

        /// <summary>
        /// Test the property 'Atualizacao'
        /// </summary>
        [Fact]
        public void AtualizacaoTest()
        {
            // TODO unit test for the property 'Atualizacao'
        }
    }
}
