/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.Pix.Model;
using Sicoob.Pix.Client;
using System.Reflection;

namespace Sicoob.Pix.Test.Model
{
    /// <summary>
    ///  Class for testing InformaEsSobreOCancelamentoDaCobranA
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InformaEsSobreOCancelamentoDaCobranATests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InformaEsSobreOCancelamentoDaCobranA
        //private InformaEsSobreOCancelamentoDaCobranA instance;

        public InformaEsSobreOCancelamentoDaCobranATests()
        {
            // TODO uncomment below to create an instance of InformaEsSobreOCancelamentoDaCobranA
            //instance = new InformaEsSobreOCancelamentoDaCobranA();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InformaEsSobreOCancelamentoDaCobranA
        /// </summary>
        [Fact]
        public void InformaEsSobreOCancelamentoDaCobranAInstanceTest()
        {
            // TODO uncomment below to test "IsType" InformaEsSobreOCancelamentoDaCobranA
            //Assert.IsType<InformaEsSobreOCancelamentoDaCobranA>(instance);
        }

        /// <summary>
        /// Test the property 'Solicitante'
        /// </summary>
        [Fact]
        public void SolicitanteTest()
        {
            // TODO unit test for the property 'Solicitante'
        }

        /// <summary>
        /// Test the property 'Codigo'
        /// </summary>
        [Fact]
        public void CodigoTest()
        {
            // TODO unit test for the property 'Codigo'
        }

        /// <summary>
        /// Test the property 'Descricao'
        /// </summary>
        [Fact]
        public void DescricaoTest()
        {
            // TODO unit test for the property 'Descricao'
        }
    }
}
