/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sicoob.Pix.Model;
using Sicoob.Pix.Client;
using System.Reflection;

namespace Sicoob.Pix.Test.Model
{
    /// <summary>
    ///  Class for testing Violacao
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ViolacaoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Violacao
        //private Violacao instance;

        public ViolacaoTests()
        {
            // TODO uncomment below to create an instance of Violacao
            //instance = new Violacao();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Violacao
        /// </summary>
        [Fact]
        public void ViolacaoInstanceTest()
        {
            // TODO uncomment below to test "IsType" Violacao
            //Assert.IsType<Violacao>(instance);
        }

        /// <summary>
        /// Test the property 'Razao'
        /// </summary>
        [Fact]
        public void RazaoTest()
        {
            // TODO unit test for the property 'Razao'
        }

        /// <summary>
        /// Test the property 'Propriedade'
        /// </summary>
        [Fact]
        public void PropriedadeTest()
        {
            // TODO unit test for the property 'Propriedade'
        }

        /// <summary>
        /// Test the property 'Valor'
        /// </summary>
        [Fact]
        public void ValorTest()
        {
            // TODO unit test for the property 'Valor'
        }
    }
}
