// <auto-generated>
/*
 * Investimentos
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/investimentos/v2 ]</pre> API dedicada a retornar os investimentos de um determinado cliente em várias etapas. Primeira a partir apenas do CPF, depois por carteira e por fim por modalidade
 *
 * The version of the OpenAPI document: 1.0.3.3
 * Contact: tiago.emerick@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Sicoob.Investimentos.Client
{
    /// <summary>
    /// A token constructed with OAuth.
    /// </summary>
    public class OAuthToken : TokenBase
    {
        private string _raw;

        /// <summary>
        /// Consturcts an OAuthToken object.
        /// </summary>
        /// <param name="value"></param>
        /// <param name="timeout"></param>
        public OAuthToken(string value, TimeSpan? timeout = null) : base(timeout)
        {
            _raw = value;
        }

        /// <summary>
        /// Places the token in the header.
        /// </summary>
        /// <param name="request"></param>
        /// <param name="headerName"></param>
        public virtual void UseInHeader(global::System.Net.Http.HttpRequestMessage request, string headerName)
        {
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _raw);
        }
    }
}
