// <auto-generated>
/*
 *  Open Finance - Iniciação de Pagamento 
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/payments/v2/itp ]</pre> A API tem como propósito viabiliza a criação, consulta e autorização dos consentimentos para pagamento entre bancos, instituições financeiras e é acessível também à estabelecimentos comerciais participantes do Open Finance Brasil.
 *
 * The version of the OpenAPI document: 2.1.2.0
 * Contact: tiago.santos@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Sicoob.OpenFinance.Client;

namespace Sicoob.OpenFinance.Model
{
    /// <summary>
    /// Pagamento
    /// </summary>
    public partial class Pagamento : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Pagamento" /> class.
        /// </summary>
        /// <param name="amount">amount</param>
        /// <param name="currency">currency</param>
        /// <param name="details">details</param>
        /// <param name="type">type</param>
        /// <param name="date">date</param>
        /// <param name="ibgeTownCode">ibgeTownCode</param>
        /// <param name="paymentDescription">paymentDescription</param>
        /// <param name="schedule">schedule</param>
        [JsonConstructor]
        public Pagamento(string amount, CurrencyEnum currency, InfoPagamentoDetalhes details, TypeEnum type, Option<string?> date = default, Option<string?> ibgeTownCode = default, Option<string?> paymentDescription = default, Option<Agendamento?> schedule = default)
        {
            Amount = amount;
            Currency = currency;
            Details = details;
            Type = type;
            DateOption = date;
            IbgeTownCodeOption = ibgeTownCode;
            PaymentDescriptionOption = paymentDescription;
            ScheduleOption = schedule;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Currency
        /// </summary>
        public enum CurrencyEnum
        {
            /// <summary>
            /// Enum AED for value: AED
            /// </summary>
            AED = 1,

            /// <summary>
            /// Enum AFN for value: AFN
            /// </summary>
            AFN = 2,

            /// <summary>
            /// Enum ALL for value: ALL
            /// </summary>
            ALL = 3,

            /// <summary>
            /// Enum AMD for value: AMD
            /// </summary>
            AMD = 4,

            /// <summary>
            /// Enum ANG for value: ANG
            /// </summary>
            ANG = 5,

            /// <summary>
            /// Enum AOA for value: AOA
            /// </summary>
            AOA = 6,

            /// <summary>
            /// Enum ARS for value: ARS
            /// </summary>
            ARS = 7,

            /// <summary>
            /// Enum AUD for value: AUD
            /// </summary>
            AUD = 8,

            /// <summary>
            /// Enum AWG for value: AWG
            /// </summary>
            AWG = 9,

            /// <summary>
            /// Enum AZN for value: AZN
            /// </summary>
            AZN = 10,

            /// <summary>
            /// Enum BAM for value: BAM
            /// </summary>
            BAM = 11,

            /// <summary>
            /// Enum BBD for value: BBD
            /// </summary>
            BBD = 12,

            /// <summary>
            /// Enum BDT for value: BDT
            /// </summary>
            BDT = 13,

            /// <summary>
            /// Enum BGN for value: BGN
            /// </summary>
            BGN = 14,

            /// <summary>
            /// Enum BHD for value: BHD
            /// </summary>
            BHD = 15,

            /// <summary>
            /// Enum BIF for value: BIF
            /// </summary>
            BIF = 16,

            /// <summary>
            /// Enum BMD for value: BMD
            /// </summary>
            BMD = 17,

            /// <summary>
            /// Enum BND for value: BND
            /// </summary>
            BND = 18,

            /// <summary>
            /// Enum BOB for value: BOB
            /// </summary>
            BOB = 19,

            /// <summary>
            /// Enum BRL for value: BRL
            /// </summary>
            BRL = 20,

            /// <summary>
            /// Enum BSD for value: BSD
            /// </summary>
            BSD = 21,

            /// <summary>
            /// Enum BTN for value: BTN
            /// </summary>
            BTN = 22,

            /// <summary>
            /// Enum BWP for value: BWP
            /// </summary>
            BWP = 23,

            /// <summary>
            /// Enum BYR for value: BYR
            /// </summary>
            BYR = 24,

            /// <summary>
            /// Enum BZD for value: BZD
            /// </summary>
            BZD = 25,

            /// <summary>
            /// Enum CAD for value: CAD
            /// </summary>
            CAD = 26,

            /// <summary>
            /// Enum CDF for value: CDF
            /// </summary>
            CDF = 27,

            /// <summary>
            /// Enum CHF for value: CHF
            /// </summary>
            CHF = 28,

            /// <summary>
            /// Enum CLP for value: CLP
            /// </summary>
            CLP = 29,

            /// <summary>
            /// Enum CNY for value: CNY
            /// </summary>
            CNY = 30,

            /// <summary>
            /// Enum COP for value: COP
            /// </summary>
            COP = 31,

            /// <summary>
            /// Enum CRC for value: CRC
            /// </summary>
            CRC = 32,

            /// <summary>
            /// Enum CUC for value: CUC
            /// </summary>
            CUC = 33,

            /// <summary>
            /// Enum CUP for value: CUP
            /// </summary>
            CUP = 34,

            /// <summary>
            /// Enum CVE for value: CVE
            /// </summary>
            CVE = 35,

            /// <summary>
            /// Enum CZK for value: CZK
            /// </summary>
            CZK = 36,

            /// <summary>
            /// Enum DJF for value: DJF
            /// </summary>
            DJF = 37,

            /// <summary>
            /// Enum DKK for value: DKK
            /// </summary>
            DKK = 38,

            /// <summary>
            /// Enum DOP for value: DOP
            /// </summary>
            DOP = 39,

            /// <summary>
            /// Enum DZD for value: DZD
            /// </summary>
            DZD = 40,

            /// <summary>
            /// Enum EGP for value: EGP
            /// </summary>
            EGP = 41,

            /// <summary>
            /// Enum ERN for value: ERN
            /// </summary>
            ERN = 42,

            /// <summary>
            /// Enum ETB for value: ETB
            /// </summary>
            ETB = 43,

            /// <summary>
            /// Enum EUR for value: EUR
            /// </summary>
            EUR = 44,

            /// <summary>
            /// Enum FJD for value: FJD
            /// </summary>
            FJD = 45,

            /// <summary>
            /// Enum FKP for value: FKP
            /// </summary>
            FKP = 46,

            /// <summary>
            /// Enum GBP for value: GBP
            /// </summary>
            GBP = 47,

            /// <summary>
            /// Enum GEL for value: GEL
            /// </summary>
            GEL = 48,

            /// <summary>
            /// Enum GGP for value: GGP
            /// </summary>
            GGP = 49,

            /// <summary>
            /// Enum GHS for value: GHS
            /// </summary>
            GHS = 50,

            /// <summary>
            /// Enum GIP for value: GIP
            /// </summary>
            GIP = 51,

            /// <summary>
            /// Enum GMD for value: GMD
            /// </summary>
            GMD = 52,

            /// <summary>
            /// Enum GNF for value: GNF
            /// </summary>
            GNF = 53,

            /// <summary>
            /// Enum GTQ for value: GTQ
            /// </summary>
            GTQ = 54,

            /// <summary>
            /// Enum GYD for value: GYD
            /// </summary>
            GYD = 55,

            /// <summary>
            /// Enum HKD for value: HKD
            /// </summary>
            HKD = 56,

            /// <summary>
            /// Enum HNL for value: HNL
            /// </summary>
            HNL = 57,

            /// <summary>
            /// Enum HRK for value: HRK
            /// </summary>
            HRK = 58,

            /// <summary>
            /// Enum HTG for value: HTG
            /// </summary>
            HTG = 59,

            /// <summary>
            /// Enum HUF for value: HUF
            /// </summary>
            HUF = 60,

            /// <summary>
            /// Enum IDR for value: IDR
            /// </summary>
            IDR = 61,

            /// <summary>
            /// Enum ILS for value: ILS
            /// </summary>
            ILS = 62,

            /// <summary>
            /// Enum IMP for value: IMP
            /// </summary>
            IMP = 63,

            /// <summary>
            /// Enum INR for value: INR
            /// </summary>
            INR = 64,

            /// <summary>
            /// Enum IQD for value: IQD
            /// </summary>
            IQD = 65,

            /// <summary>
            /// Enum IRR for value: IRR
            /// </summary>
            IRR = 66,

            /// <summary>
            /// Enum ISK for value: ISK
            /// </summary>
            ISK = 67,

            /// <summary>
            /// Enum JEP for value: JEP
            /// </summary>
            JEP = 68,

            /// <summary>
            /// Enum JMD for value: JMD
            /// </summary>
            JMD = 69,

            /// <summary>
            /// Enum JOD for value: JOD
            /// </summary>
            JOD = 70,

            /// <summary>
            /// Enum JPY for value: JPY
            /// </summary>
            JPY = 71,

            /// <summary>
            /// Enum KES for value: KES
            /// </summary>
            KES = 72,

            /// <summary>
            /// Enum KGS for value: KGS
            /// </summary>
            KGS = 73,

            /// <summary>
            /// Enum KHR for value: KHR
            /// </summary>
            KHR = 74,

            /// <summary>
            /// Enum KMF for value: KMF
            /// </summary>
            KMF = 75,

            /// <summary>
            /// Enum KPW for value: KPW
            /// </summary>
            KPW = 76,

            /// <summary>
            /// Enum KRW for value: KRW
            /// </summary>
            KRW = 77,

            /// <summary>
            /// Enum KWD for value: KWD
            /// </summary>
            KWD = 78,

            /// <summary>
            /// Enum KYD for value: KYD
            /// </summary>
            KYD = 79,

            /// <summary>
            /// Enum KZT for value: KZT
            /// </summary>
            KZT = 80,

            /// <summary>
            /// Enum LAK for value: LAK
            /// </summary>
            LAK = 81,

            /// <summary>
            /// Enum LBP for value: LBP
            /// </summary>
            LBP = 82,

            /// <summary>
            /// Enum LKR for value: LKR
            /// </summary>
            LKR = 83,

            /// <summary>
            /// Enum LRD for value: LRD
            /// </summary>
            LRD = 84,

            /// <summary>
            /// Enum LSL for value: LSL
            /// </summary>
            LSL = 85,

            /// <summary>
            /// Enum LYD for value: LYD
            /// </summary>
            LYD = 86,

            /// <summary>
            /// Enum MAD for value: MAD
            /// </summary>
            MAD = 87,

            /// <summary>
            /// Enum MDL for value: MDL
            /// </summary>
            MDL = 88,

            /// <summary>
            /// Enum MGA for value: MGA
            /// </summary>
            MGA = 89,

            /// <summary>
            /// Enum MKD for value: MKD
            /// </summary>
            MKD = 90,

            /// <summary>
            /// Enum MMK for value: MMK
            /// </summary>
            MMK = 91,

            /// <summary>
            /// Enum MNT for value: MNT
            /// </summary>
            MNT = 92,

            /// <summary>
            /// Enum MOP for value: MOP
            /// </summary>
            MOP = 93,

            /// <summary>
            /// Enum MRO for value: MRO
            /// </summary>
            MRO = 94,

            /// <summary>
            /// Enum MUR for value: MUR
            /// </summary>
            MUR = 95,

            /// <summary>
            /// Enum MVR for value: MVR
            /// </summary>
            MVR = 96,

            /// <summary>
            /// Enum MWK for value: MWK
            /// </summary>
            MWK = 97,

            /// <summary>
            /// Enum MXN for value: MXN
            /// </summary>
            MXN = 98,

            /// <summary>
            /// Enum MYR for value: MYR
            /// </summary>
            MYR = 99,

            /// <summary>
            /// Enum MZN for value: MZN
            /// </summary>
            MZN = 100,

            /// <summary>
            /// Enum NAD for value: NAD
            /// </summary>
            NAD = 101,

            /// <summary>
            /// Enum NGN for value: NGN
            /// </summary>
            NGN = 102,

            /// <summary>
            /// Enum NIO for value: NIO
            /// </summary>
            NIO = 103,

            /// <summary>
            /// Enum NOK for value: NOK
            /// </summary>
            NOK = 104,

            /// <summary>
            /// Enum NPR for value: NPR
            /// </summary>
            NPR = 105,

            /// <summary>
            /// Enum NZD for value: NZD
            /// </summary>
            NZD = 106,

            /// <summary>
            /// Enum OMR for value: OMR
            /// </summary>
            OMR = 107,

            /// <summary>
            /// Enum PAB for value: PAB
            /// </summary>
            PAB = 108,

            /// <summary>
            /// Enum PEN for value: PEN
            /// </summary>
            PEN = 109,

            /// <summary>
            /// Enum PGK for value: PGK
            /// </summary>
            PGK = 110,

            /// <summary>
            /// Enum PHP for value: PHP
            /// </summary>
            PHP = 111,

            /// <summary>
            /// Enum PKR for value: PKR
            /// </summary>
            PKR = 112,

            /// <summary>
            /// Enum PLN for value: PLN
            /// </summary>
            PLN = 113,

            /// <summary>
            /// Enum PYG for value: PYG
            /// </summary>
            PYG = 114,

            /// <summary>
            /// Enum QAR for value: QAR
            /// </summary>
            QAR = 115,

            /// <summary>
            /// Enum RON for value: RON
            /// </summary>
            RON = 116,

            /// <summary>
            /// Enum RSD for value: RSD
            /// </summary>
            RSD = 117,

            /// <summary>
            /// Enum RUB for value: RUB
            /// </summary>
            RUB = 118,

            /// <summary>
            /// Enum RWF for value: RWF
            /// </summary>
            RWF = 119,

            /// <summary>
            /// Enum SAR for value: SAR
            /// </summary>
            SAR = 120,

            /// <summary>
            /// Enum SBD for value: SBD
            /// </summary>
            SBD = 121,

            /// <summary>
            /// Enum SCR for value: SCR
            /// </summary>
            SCR = 122,

            /// <summary>
            /// Enum SDG for value: SDG
            /// </summary>
            SDG = 123,

            /// <summary>
            /// Enum SEK for value: SEK
            /// </summary>
            SEK = 124,

            /// <summary>
            /// Enum SGD for value: SGD
            /// </summary>
            SGD = 125,

            /// <summary>
            /// Enum SHP for value: SHP
            /// </summary>
            SHP = 126,

            /// <summary>
            /// Enum SLL for value: SLL
            /// </summary>
            SLL = 127,

            /// <summary>
            /// Enum SOS for value: SOS
            /// </summary>
            SOS = 128,

            /// <summary>
            /// Enum SPL for value: SPL
            /// </summary>
            SPL = 129,

            /// <summary>
            /// Enum SRD for value: SRD
            /// </summary>
            SRD = 130,

            /// <summary>
            /// Enum STD for value: STD
            /// </summary>
            STD = 131,

            /// <summary>
            /// Enum SVC for value: SVC
            /// </summary>
            SVC = 132,

            /// <summary>
            /// Enum SYP for value: SYP
            /// </summary>
            SYP = 133,

            /// <summary>
            /// Enum SZL for value: SZL
            /// </summary>
            SZL = 134,

            /// <summary>
            /// Enum THB for value: THB
            /// </summary>
            THB = 135,

            /// <summary>
            /// Enum TJS for value: TJS
            /// </summary>
            TJS = 136,

            /// <summary>
            /// Enum TMT for value: TMT
            /// </summary>
            TMT = 137,

            /// <summary>
            /// Enum TND for value: TND
            /// </summary>
            TND = 138,

            /// <summary>
            /// Enum TOP for value: TOP
            /// </summary>
            TOP = 139,

            /// <summary>
            /// Enum TRY for value: TRY
            /// </summary>
            TRY = 140,

            /// <summary>
            /// Enum TTD for value: TTD
            /// </summary>
            TTD = 141,

            /// <summary>
            /// Enum TVD for value: TVD
            /// </summary>
            TVD = 142,

            /// <summary>
            /// Enum TWD for value: TWD
            /// </summary>
            TWD = 143,

            /// <summary>
            /// Enum TZS for value: TZS
            /// </summary>
            TZS = 144,

            /// <summary>
            /// Enum UAH for value: UAH
            /// </summary>
            UAH = 145,

            /// <summary>
            /// Enum UGX for value: UGX
            /// </summary>
            UGX = 146,

            /// <summary>
            /// Enum USD for value: USD
            /// </summary>
            USD = 147,

            /// <summary>
            /// Enum UYU for value: UYU
            /// </summary>
            UYU = 148,

            /// <summary>
            /// Enum UZS for value: UZS
            /// </summary>
            UZS = 149,

            /// <summary>
            /// Enum VEF for value: VEF
            /// </summary>
            VEF = 150,

            /// <summary>
            /// Enum VND for value: VND
            /// </summary>
            VND = 151,

            /// <summary>
            /// Enum VUV for value: VUV
            /// </summary>
            VUV = 152,

            /// <summary>
            /// Enum WST for value: WST
            /// </summary>
            WST = 153,

            /// <summary>
            /// Enum XAF for value: XAF
            /// </summary>
            XAF = 154,

            /// <summary>
            /// Enum XCD for value: XCD
            /// </summary>
            XCD = 155,

            /// <summary>
            /// Enum XDR for value: XDR
            /// </summary>
            XDR = 156,

            /// <summary>
            /// Enum XOF for value: XOF
            /// </summary>
            XOF = 157,

            /// <summary>
            /// Enum XPF for value: XPF
            /// </summary>
            XPF = 158,

            /// <summary>
            /// Enum YER for value: YER
            /// </summary>
            YER = 159,

            /// <summary>
            /// Enum ZAR for value: ZAR
            /// </summary>
            ZAR = 160,

            /// <summary>
            /// Enum ZMW for value: ZMW
            /// </summary>
            ZMW = 161,

            /// <summary>
            /// Enum ZWD for value: ZWD
            /// </summary>
            ZWD = 162
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CurrencyEnum CurrencyEnumFromString(string value)
        {
            if (value.Equals("AED"))
                return CurrencyEnum.AED;

            if (value.Equals("AFN"))
                return CurrencyEnum.AFN;

            if (value.Equals("ALL"))
                return CurrencyEnum.ALL;

            if (value.Equals("AMD"))
                return CurrencyEnum.AMD;

            if (value.Equals("ANG"))
                return CurrencyEnum.ANG;

            if (value.Equals("AOA"))
                return CurrencyEnum.AOA;

            if (value.Equals("ARS"))
                return CurrencyEnum.ARS;

            if (value.Equals("AUD"))
                return CurrencyEnum.AUD;

            if (value.Equals("AWG"))
                return CurrencyEnum.AWG;

            if (value.Equals("AZN"))
                return CurrencyEnum.AZN;

            if (value.Equals("BAM"))
                return CurrencyEnum.BAM;

            if (value.Equals("BBD"))
                return CurrencyEnum.BBD;

            if (value.Equals("BDT"))
                return CurrencyEnum.BDT;

            if (value.Equals("BGN"))
                return CurrencyEnum.BGN;

            if (value.Equals("BHD"))
                return CurrencyEnum.BHD;

            if (value.Equals("BIF"))
                return CurrencyEnum.BIF;

            if (value.Equals("BMD"))
                return CurrencyEnum.BMD;

            if (value.Equals("BND"))
                return CurrencyEnum.BND;

            if (value.Equals("BOB"))
                return CurrencyEnum.BOB;

            if (value.Equals("BRL"))
                return CurrencyEnum.BRL;

            if (value.Equals("BSD"))
                return CurrencyEnum.BSD;

            if (value.Equals("BTN"))
                return CurrencyEnum.BTN;

            if (value.Equals("BWP"))
                return CurrencyEnum.BWP;

            if (value.Equals("BYR"))
                return CurrencyEnum.BYR;

            if (value.Equals("BZD"))
                return CurrencyEnum.BZD;

            if (value.Equals("CAD"))
                return CurrencyEnum.CAD;

            if (value.Equals("CDF"))
                return CurrencyEnum.CDF;

            if (value.Equals("CHF"))
                return CurrencyEnum.CHF;

            if (value.Equals("CLP"))
                return CurrencyEnum.CLP;

            if (value.Equals("CNY"))
                return CurrencyEnum.CNY;

            if (value.Equals("COP"))
                return CurrencyEnum.COP;

            if (value.Equals("CRC"))
                return CurrencyEnum.CRC;

            if (value.Equals("CUC"))
                return CurrencyEnum.CUC;

            if (value.Equals("CUP"))
                return CurrencyEnum.CUP;

            if (value.Equals("CVE"))
                return CurrencyEnum.CVE;

            if (value.Equals("CZK"))
                return CurrencyEnum.CZK;

            if (value.Equals("DJF"))
                return CurrencyEnum.DJF;

            if (value.Equals("DKK"))
                return CurrencyEnum.DKK;

            if (value.Equals("DOP"))
                return CurrencyEnum.DOP;

            if (value.Equals("DZD"))
                return CurrencyEnum.DZD;

            if (value.Equals("EGP"))
                return CurrencyEnum.EGP;

            if (value.Equals("ERN"))
                return CurrencyEnum.ERN;

            if (value.Equals("ETB"))
                return CurrencyEnum.ETB;

            if (value.Equals("EUR"))
                return CurrencyEnum.EUR;

            if (value.Equals("FJD"))
                return CurrencyEnum.FJD;

            if (value.Equals("FKP"))
                return CurrencyEnum.FKP;

            if (value.Equals("GBP"))
                return CurrencyEnum.GBP;

            if (value.Equals("GEL"))
                return CurrencyEnum.GEL;

            if (value.Equals("GGP"))
                return CurrencyEnum.GGP;

            if (value.Equals("GHS"))
                return CurrencyEnum.GHS;

            if (value.Equals("GIP"))
                return CurrencyEnum.GIP;

            if (value.Equals("GMD"))
                return CurrencyEnum.GMD;

            if (value.Equals("GNF"))
                return CurrencyEnum.GNF;

            if (value.Equals("GTQ"))
                return CurrencyEnum.GTQ;

            if (value.Equals("GYD"))
                return CurrencyEnum.GYD;

            if (value.Equals("HKD"))
                return CurrencyEnum.HKD;

            if (value.Equals("HNL"))
                return CurrencyEnum.HNL;

            if (value.Equals("HRK"))
                return CurrencyEnum.HRK;

            if (value.Equals("HTG"))
                return CurrencyEnum.HTG;

            if (value.Equals("HUF"))
                return CurrencyEnum.HUF;

            if (value.Equals("IDR"))
                return CurrencyEnum.IDR;

            if (value.Equals("ILS"))
                return CurrencyEnum.ILS;

            if (value.Equals("IMP"))
                return CurrencyEnum.IMP;

            if (value.Equals("INR"))
                return CurrencyEnum.INR;

            if (value.Equals("IQD"))
                return CurrencyEnum.IQD;

            if (value.Equals("IRR"))
                return CurrencyEnum.IRR;

            if (value.Equals("ISK"))
                return CurrencyEnum.ISK;

            if (value.Equals("JEP"))
                return CurrencyEnum.JEP;

            if (value.Equals("JMD"))
                return CurrencyEnum.JMD;

            if (value.Equals("JOD"))
                return CurrencyEnum.JOD;

            if (value.Equals("JPY"))
                return CurrencyEnum.JPY;

            if (value.Equals("KES"))
                return CurrencyEnum.KES;

            if (value.Equals("KGS"))
                return CurrencyEnum.KGS;

            if (value.Equals("KHR"))
                return CurrencyEnum.KHR;

            if (value.Equals("KMF"))
                return CurrencyEnum.KMF;

            if (value.Equals("KPW"))
                return CurrencyEnum.KPW;

            if (value.Equals("KRW"))
                return CurrencyEnum.KRW;

            if (value.Equals("KWD"))
                return CurrencyEnum.KWD;

            if (value.Equals("KYD"))
                return CurrencyEnum.KYD;

            if (value.Equals("KZT"))
                return CurrencyEnum.KZT;

            if (value.Equals("LAK"))
                return CurrencyEnum.LAK;

            if (value.Equals("LBP"))
                return CurrencyEnum.LBP;

            if (value.Equals("LKR"))
                return CurrencyEnum.LKR;

            if (value.Equals("LRD"))
                return CurrencyEnum.LRD;

            if (value.Equals("LSL"))
                return CurrencyEnum.LSL;

            if (value.Equals("LYD"))
                return CurrencyEnum.LYD;

            if (value.Equals("MAD"))
                return CurrencyEnum.MAD;

            if (value.Equals("MDL"))
                return CurrencyEnum.MDL;

            if (value.Equals("MGA"))
                return CurrencyEnum.MGA;

            if (value.Equals("MKD"))
                return CurrencyEnum.MKD;

            if (value.Equals("MMK"))
                return CurrencyEnum.MMK;

            if (value.Equals("MNT"))
                return CurrencyEnum.MNT;

            if (value.Equals("MOP"))
                return CurrencyEnum.MOP;

            if (value.Equals("MRO"))
                return CurrencyEnum.MRO;

            if (value.Equals("MUR"))
                return CurrencyEnum.MUR;

            if (value.Equals("MVR"))
                return CurrencyEnum.MVR;

            if (value.Equals("MWK"))
                return CurrencyEnum.MWK;

            if (value.Equals("MXN"))
                return CurrencyEnum.MXN;

            if (value.Equals("MYR"))
                return CurrencyEnum.MYR;

            if (value.Equals("MZN"))
                return CurrencyEnum.MZN;

            if (value.Equals("NAD"))
                return CurrencyEnum.NAD;

            if (value.Equals("NGN"))
                return CurrencyEnum.NGN;

            if (value.Equals("NIO"))
                return CurrencyEnum.NIO;

            if (value.Equals("NOK"))
                return CurrencyEnum.NOK;

            if (value.Equals("NPR"))
                return CurrencyEnum.NPR;

            if (value.Equals("NZD"))
                return CurrencyEnum.NZD;

            if (value.Equals("OMR"))
                return CurrencyEnum.OMR;

            if (value.Equals("PAB"))
                return CurrencyEnum.PAB;

            if (value.Equals("PEN"))
                return CurrencyEnum.PEN;

            if (value.Equals("PGK"))
                return CurrencyEnum.PGK;

            if (value.Equals("PHP"))
                return CurrencyEnum.PHP;

            if (value.Equals("PKR"))
                return CurrencyEnum.PKR;

            if (value.Equals("PLN"))
                return CurrencyEnum.PLN;

            if (value.Equals("PYG"))
                return CurrencyEnum.PYG;

            if (value.Equals("QAR"))
                return CurrencyEnum.QAR;

            if (value.Equals("RON"))
                return CurrencyEnum.RON;

            if (value.Equals("RSD"))
                return CurrencyEnum.RSD;

            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            if (value.Equals("RWF"))
                return CurrencyEnum.RWF;

            if (value.Equals("SAR"))
                return CurrencyEnum.SAR;

            if (value.Equals("SBD"))
                return CurrencyEnum.SBD;

            if (value.Equals("SCR"))
                return CurrencyEnum.SCR;

            if (value.Equals("SDG"))
                return CurrencyEnum.SDG;

            if (value.Equals("SEK"))
                return CurrencyEnum.SEK;

            if (value.Equals("SGD"))
                return CurrencyEnum.SGD;

            if (value.Equals("SHP"))
                return CurrencyEnum.SHP;

            if (value.Equals("SLL"))
                return CurrencyEnum.SLL;

            if (value.Equals("SOS"))
                return CurrencyEnum.SOS;

            if (value.Equals("SPL"))
                return CurrencyEnum.SPL;

            if (value.Equals("SRD"))
                return CurrencyEnum.SRD;

            if (value.Equals("STD"))
                return CurrencyEnum.STD;

            if (value.Equals("SVC"))
                return CurrencyEnum.SVC;

            if (value.Equals("SYP"))
                return CurrencyEnum.SYP;

            if (value.Equals("SZL"))
                return CurrencyEnum.SZL;

            if (value.Equals("THB"))
                return CurrencyEnum.THB;

            if (value.Equals("TJS"))
                return CurrencyEnum.TJS;

            if (value.Equals("TMT"))
                return CurrencyEnum.TMT;

            if (value.Equals("TND"))
                return CurrencyEnum.TND;

            if (value.Equals("TOP"))
                return CurrencyEnum.TOP;

            if (value.Equals("TRY"))
                return CurrencyEnum.TRY;

            if (value.Equals("TTD"))
                return CurrencyEnum.TTD;

            if (value.Equals("TVD"))
                return CurrencyEnum.TVD;

            if (value.Equals("TWD"))
                return CurrencyEnum.TWD;

            if (value.Equals("TZS"))
                return CurrencyEnum.TZS;

            if (value.Equals("UAH"))
                return CurrencyEnum.UAH;

            if (value.Equals("UGX"))
                return CurrencyEnum.UGX;

            if (value.Equals("USD"))
                return CurrencyEnum.USD;

            if (value.Equals("UYU"))
                return CurrencyEnum.UYU;

            if (value.Equals("UZS"))
                return CurrencyEnum.UZS;

            if (value.Equals("VEF"))
                return CurrencyEnum.VEF;

            if (value.Equals("VND"))
                return CurrencyEnum.VND;

            if (value.Equals("VUV"))
                return CurrencyEnum.VUV;

            if (value.Equals("WST"))
                return CurrencyEnum.WST;

            if (value.Equals("XAF"))
                return CurrencyEnum.XAF;

            if (value.Equals("XCD"))
                return CurrencyEnum.XCD;

            if (value.Equals("XDR"))
                return CurrencyEnum.XDR;

            if (value.Equals("XOF"))
                return CurrencyEnum.XOF;

            if (value.Equals("XPF"))
                return CurrencyEnum.XPF;

            if (value.Equals("YER"))
                return CurrencyEnum.YER;

            if (value.Equals("ZAR"))
                return CurrencyEnum.ZAR;

            if (value.Equals("ZMW"))
                return CurrencyEnum.ZMW;

            if (value.Equals("ZWD"))
                return CurrencyEnum.ZWD;

            throw new NotImplementedException($"Could not convert value to type CurrencyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CurrencyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CurrencyEnum? CurrencyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("AED"))
                return CurrencyEnum.AED;

            if (value.Equals("AFN"))
                return CurrencyEnum.AFN;

            if (value.Equals("ALL"))
                return CurrencyEnum.ALL;

            if (value.Equals("AMD"))
                return CurrencyEnum.AMD;

            if (value.Equals("ANG"))
                return CurrencyEnum.ANG;

            if (value.Equals("AOA"))
                return CurrencyEnum.AOA;

            if (value.Equals("ARS"))
                return CurrencyEnum.ARS;

            if (value.Equals("AUD"))
                return CurrencyEnum.AUD;

            if (value.Equals("AWG"))
                return CurrencyEnum.AWG;

            if (value.Equals("AZN"))
                return CurrencyEnum.AZN;

            if (value.Equals("BAM"))
                return CurrencyEnum.BAM;

            if (value.Equals("BBD"))
                return CurrencyEnum.BBD;

            if (value.Equals("BDT"))
                return CurrencyEnum.BDT;

            if (value.Equals("BGN"))
                return CurrencyEnum.BGN;

            if (value.Equals("BHD"))
                return CurrencyEnum.BHD;

            if (value.Equals("BIF"))
                return CurrencyEnum.BIF;

            if (value.Equals("BMD"))
                return CurrencyEnum.BMD;

            if (value.Equals("BND"))
                return CurrencyEnum.BND;

            if (value.Equals("BOB"))
                return CurrencyEnum.BOB;

            if (value.Equals("BRL"))
                return CurrencyEnum.BRL;

            if (value.Equals("BSD"))
                return CurrencyEnum.BSD;

            if (value.Equals("BTN"))
                return CurrencyEnum.BTN;

            if (value.Equals("BWP"))
                return CurrencyEnum.BWP;

            if (value.Equals("BYR"))
                return CurrencyEnum.BYR;

            if (value.Equals("BZD"))
                return CurrencyEnum.BZD;

            if (value.Equals("CAD"))
                return CurrencyEnum.CAD;

            if (value.Equals("CDF"))
                return CurrencyEnum.CDF;

            if (value.Equals("CHF"))
                return CurrencyEnum.CHF;

            if (value.Equals("CLP"))
                return CurrencyEnum.CLP;

            if (value.Equals("CNY"))
                return CurrencyEnum.CNY;

            if (value.Equals("COP"))
                return CurrencyEnum.COP;

            if (value.Equals("CRC"))
                return CurrencyEnum.CRC;

            if (value.Equals("CUC"))
                return CurrencyEnum.CUC;

            if (value.Equals("CUP"))
                return CurrencyEnum.CUP;

            if (value.Equals("CVE"))
                return CurrencyEnum.CVE;

            if (value.Equals("CZK"))
                return CurrencyEnum.CZK;

            if (value.Equals("DJF"))
                return CurrencyEnum.DJF;

            if (value.Equals("DKK"))
                return CurrencyEnum.DKK;

            if (value.Equals("DOP"))
                return CurrencyEnum.DOP;

            if (value.Equals("DZD"))
                return CurrencyEnum.DZD;

            if (value.Equals("EGP"))
                return CurrencyEnum.EGP;

            if (value.Equals("ERN"))
                return CurrencyEnum.ERN;

            if (value.Equals("ETB"))
                return CurrencyEnum.ETB;

            if (value.Equals("EUR"))
                return CurrencyEnum.EUR;

            if (value.Equals("FJD"))
                return CurrencyEnum.FJD;

            if (value.Equals("FKP"))
                return CurrencyEnum.FKP;

            if (value.Equals("GBP"))
                return CurrencyEnum.GBP;

            if (value.Equals("GEL"))
                return CurrencyEnum.GEL;

            if (value.Equals("GGP"))
                return CurrencyEnum.GGP;

            if (value.Equals("GHS"))
                return CurrencyEnum.GHS;

            if (value.Equals("GIP"))
                return CurrencyEnum.GIP;

            if (value.Equals("GMD"))
                return CurrencyEnum.GMD;

            if (value.Equals("GNF"))
                return CurrencyEnum.GNF;

            if (value.Equals("GTQ"))
                return CurrencyEnum.GTQ;

            if (value.Equals("GYD"))
                return CurrencyEnum.GYD;

            if (value.Equals("HKD"))
                return CurrencyEnum.HKD;

            if (value.Equals("HNL"))
                return CurrencyEnum.HNL;

            if (value.Equals("HRK"))
                return CurrencyEnum.HRK;

            if (value.Equals("HTG"))
                return CurrencyEnum.HTG;

            if (value.Equals("HUF"))
                return CurrencyEnum.HUF;

            if (value.Equals("IDR"))
                return CurrencyEnum.IDR;

            if (value.Equals("ILS"))
                return CurrencyEnum.ILS;

            if (value.Equals("IMP"))
                return CurrencyEnum.IMP;

            if (value.Equals("INR"))
                return CurrencyEnum.INR;

            if (value.Equals("IQD"))
                return CurrencyEnum.IQD;

            if (value.Equals("IRR"))
                return CurrencyEnum.IRR;

            if (value.Equals("ISK"))
                return CurrencyEnum.ISK;

            if (value.Equals("JEP"))
                return CurrencyEnum.JEP;

            if (value.Equals("JMD"))
                return CurrencyEnum.JMD;

            if (value.Equals("JOD"))
                return CurrencyEnum.JOD;

            if (value.Equals("JPY"))
                return CurrencyEnum.JPY;

            if (value.Equals("KES"))
                return CurrencyEnum.KES;

            if (value.Equals("KGS"))
                return CurrencyEnum.KGS;

            if (value.Equals("KHR"))
                return CurrencyEnum.KHR;

            if (value.Equals("KMF"))
                return CurrencyEnum.KMF;

            if (value.Equals("KPW"))
                return CurrencyEnum.KPW;

            if (value.Equals("KRW"))
                return CurrencyEnum.KRW;

            if (value.Equals("KWD"))
                return CurrencyEnum.KWD;

            if (value.Equals("KYD"))
                return CurrencyEnum.KYD;

            if (value.Equals("KZT"))
                return CurrencyEnum.KZT;

            if (value.Equals("LAK"))
                return CurrencyEnum.LAK;

            if (value.Equals("LBP"))
                return CurrencyEnum.LBP;

            if (value.Equals("LKR"))
                return CurrencyEnum.LKR;

            if (value.Equals("LRD"))
                return CurrencyEnum.LRD;

            if (value.Equals("LSL"))
                return CurrencyEnum.LSL;

            if (value.Equals("LYD"))
                return CurrencyEnum.LYD;

            if (value.Equals("MAD"))
                return CurrencyEnum.MAD;

            if (value.Equals("MDL"))
                return CurrencyEnum.MDL;

            if (value.Equals("MGA"))
                return CurrencyEnum.MGA;

            if (value.Equals("MKD"))
                return CurrencyEnum.MKD;

            if (value.Equals("MMK"))
                return CurrencyEnum.MMK;

            if (value.Equals("MNT"))
                return CurrencyEnum.MNT;

            if (value.Equals("MOP"))
                return CurrencyEnum.MOP;

            if (value.Equals("MRO"))
                return CurrencyEnum.MRO;

            if (value.Equals("MUR"))
                return CurrencyEnum.MUR;

            if (value.Equals("MVR"))
                return CurrencyEnum.MVR;

            if (value.Equals("MWK"))
                return CurrencyEnum.MWK;

            if (value.Equals("MXN"))
                return CurrencyEnum.MXN;

            if (value.Equals("MYR"))
                return CurrencyEnum.MYR;

            if (value.Equals("MZN"))
                return CurrencyEnum.MZN;

            if (value.Equals("NAD"))
                return CurrencyEnum.NAD;

            if (value.Equals("NGN"))
                return CurrencyEnum.NGN;

            if (value.Equals("NIO"))
                return CurrencyEnum.NIO;

            if (value.Equals("NOK"))
                return CurrencyEnum.NOK;

            if (value.Equals("NPR"))
                return CurrencyEnum.NPR;

            if (value.Equals("NZD"))
                return CurrencyEnum.NZD;

            if (value.Equals("OMR"))
                return CurrencyEnum.OMR;

            if (value.Equals("PAB"))
                return CurrencyEnum.PAB;

            if (value.Equals("PEN"))
                return CurrencyEnum.PEN;

            if (value.Equals("PGK"))
                return CurrencyEnum.PGK;

            if (value.Equals("PHP"))
                return CurrencyEnum.PHP;

            if (value.Equals("PKR"))
                return CurrencyEnum.PKR;

            if (value.Equals("PLN"))
                return CurrencyEnum.PLN;

            if (value.Equals("PYG"))
                return CurrencyEnum.PYG;

            if (value.Equals("QAR"))
                return CurrencyEnum.QAR;

            if (value.Equals("RON"))
                return CurrencyEnum.RON;

            if (value.Equals("RSD"))
                return CurrencyEnum.RSD;

            if (value.Equals("RUB"))
                return CurrencyEnum.RUB;

            if (value.Equals("RWF"))
                return CurrencyEnum.RWF;

            if (value.Equals("SAR"))
                return CurrencyEnum.SAR;

            if (value.Equals("SBD"))
                return CurrencyEnum.SBD;

            if (value.Equals("SCR"))
                return CurrencyEnum.SCR;

            if (value.Equals("SDG"))
                return CurrencyEnum.SDG;

            if (value.Equals("SEK"))
                return CurrencyEnum.SEK;

            if (value.Equals("SGD"))
                return CurrencyEnum.SGD;

            if (value.Equals("SHP"))
                return CurrencyEnum.SHP;

            if (value.Equals("SLL"))
                return CurrencyEnum.SLL;

            if (value.Equals("SOS"))
                return CurrencyEnum.SOS;

            if (value.Equals("SPL"))
                return CurrencyEnum.SPL;

            if (value.Equals("SRD"))
                return CurrencyEnum.SRD;

            if (value.Equals("STD"))
                return CurrencyEnum.STD;

            if (value.Equals("SVC"))
                return CurrencyEnum.SVC;

            if (value.Equals("SYP"))
                return CurrencyEnum.SYP;

            if (value.Equals("SZL"))
                return CurrencyEnum.SZL;

            if (value.Equals("THB"))
                return CurrencyEnum.THB;

            if (value.Equals("TJS"))
                return CurrencyEnum.TJS;

            if (value.Equals("TMT"))
                return CurrencyEnum.TMT;

            if (value.Equals("TND"))
                return CurrencyEnum.TND;

            if (value.Equals("TOP"))
                return CurrencyEnum.TOP;

            if (value.Equals("TRY"))
                return CurrencyEnum.TRY;

            if (value.Equals("TTD"))
                return CurrencyEnum.TTD;

            if (value.Equals("TVD"))
                return CurrencyEnum.TVD;

            if (value.Equals("TWD"))
                return CurrencyEnum.TWD;

            if (value.Equals("TZS"))
                return CurrencyEnum.TZS;

            if (value.Equals("UAH"))
                return CurrencyEnum.UAH;

            if (value.Equals("UGX"))
                return CurrencyEnum.UGX;

            if (value.Equals("USD"))
                return CurrencyEnum.USD;

            if (value.Equals("UYU"))
                return CurrencyEnum.UYU;

            if (value.Equals("UZS"))
                return CurrencyEnum.UZS;

            if (value.Equals("VEF"))
                return CurrencyEnum.VEF;

            if (value.Equals("VND"))
                return CurrencyEnum.VND;

            if (value.Equals("VUV"))
                return CurrencyEnum.VUV;

            if (value.Equals("WST"))
                return CurrencyEnum.WST;

            if (value.Equals("XAF"))
                return CurrencyEnum.XAF;

            if (value.Equals("XCD"))
                return CurrencyEnum.XCD;

            if (value.Equals("XDR"))
                return CurrencyEnum.XDR;

            if (value.Equals("XOF"))
                return CurrencyEnum.XOF;

            if (value.Equals("XPF"))
                return CurrencyEnum.XPF;

            if (value.Equals("YER"))
                return CurrencyEnum.YER;

            if (value.Equals("ZAR"))
                return CurrencyEnum.ZAR;

            if (value.Equals("ZMW"))
                return CurrencyEnum.ZMW;

            if (value.Equals("ZWD"))
                return CurrencyEnum.ZWD;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CurrencyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CurrencyEnumToJsonValue(CurrencyEnum value)
        {
            if (value == CurrencyEnum.AED)
                return "AED";

            if (value == CurrencyEnum.AFN)
                return "AFN";

            if (value == CurrencyEnum.ALL)
                return "ALL";

            if (value == CurrencyEnum.AMD)
                return "AMD";

            if (value == CurrencyEnum.ANG)
                return "ANG";

            if (value == CurrencyEnum.AOA)
                return "AOA";

            if (value == CurrencyEnum.ARS)
                return "ARS";

            if (value == CurrencyEnum.AUD)
                return "AUD";

            if (value == CurrencyEnum.AWG)
                return "AWG";

            if (value == CurrencyEnum.AZN)
                return "AZN";

            if (value == CurrencyEnum.BAM)
                return "BAM";

            if (value == CurrencyEnum.BBD)
                return "BBD";

            if (value == CurrencyEnum.BDT)
                return "BDT";

            if (value == CurrencyEnum.BGN)
                return "BGN";

            if (value == CurrencyEnum.BHD)
                return "BHD";

            if (value == CurrencyEnum.BIF)
                return "BIF";

            if (value == CurrencyEnum.BMD)
                return "BMD";

            if (value == CurrencyEnum.BND)
                return "BND";

            if (value == CurrencyEnum.BOB)
                return "BOB";

            if (value == CurrencyEnum.BRL)
                return "BRL";

            if (value == CurrencyEnum.BSD)
                return "BSD";

            if (value == CurrencyEnum.BTN)
                return "BTN";

            if (value == CurrencyEnum.BWP)
                return "BWP";

            if (value == CurrencyEnum.BYR)
                return "BYR";

            if (value == CurrencyEnum.BZD)
                return "BZD";

            if (value == CurrencyEnum.CAD)
                return "CAD";

            if (value == CurrencyEnum.CDF)
                return "CDF";

            if (value == CurrencyEnum.CHF)
                return "CHF";

            if (value == CurrencyEnum.CLP)
                return "CLP";

            if (value == CurrencyEnum.CNY)
                return "CNY";

            if (value == CurrencyEnum.COP)
                return "COP";

            if (value == CurrencyEnum.CRC)
                return "CRC";

            if (value == CurrencyEnum.CUC)
                return "CUC";

            if (value == CurrencyEnum.CUP)
                return "CUP";

            if (value == CurrencyEnum.CVE)
                return "CVE";

            if (value == CurrencyEnum.CZK)
                return "CZK";

            if (value == CurrencyEnum.DJF)
                return "DJF";

            if (value == CurrencyEnum.DKK)
                return "DKK";

            if (value == CurrencyEnum.DOP)
                return "DOP";

            if (value == CurrencyEnum.DZD)
                return "DZD";

            if (value == CurrencyEnum.EGP)
                return "EGP";

            if (value == CurrencyEnum.ERN)
                return "ERN";

            if (value == CurrencyEnum.ETB)
                return "ETB";

            if (value == CurrencyEnum.EUR)
                return "EUR";

            if (value == CurrencyEnum.FJD)
                return "FJD";

            if (value == CurrencyEnum.FKP)
                return "FKP";

            if (value == CurrencyEnum.GBP)
                return "GBP";

            if (value == CurrencyEnum.GEL)
                return "GEL";

            if (value == CurrencyEnum.GGP)
                return "GGP";

            if (value == CurrencyEnum.GHS)
                return "GHS";

            if (value == CurrencyEnum.GIP)
                return "GIP";

            if (value == CurrencyEnum.GMD)
                return "GMD";

            if (value == CurrencyEnum.GNF)
                return "GNF";

            if (value == CurrencyEnum.GTQ)
                return "GTQ";

            if (value == CurrencyEnum.GYD)
                return "GYD";

            if (value == CurrencyEnum.HKD)
                return "HKD";

            if (value == CurrencyEnum.HNL)
                return "HNL";

            if (value == CurrencyEnum.HRK)
                return "HRK";

            if (value == CurrencyEnum.HTG)
                return "HTG";

            if (value == CurrencyEnum.HUF)
                return "HUF";

            if (value == CurrencyEnum.IDR)
                return "IDR";

            if (value == CurrencyEnum.ILS)
                return "ILS";

            if (value == CurrencyEnum.IMP)
                return "IMP";

            if (value == CurrencyEnum.INR)
                return "INR";

            if (value == CurrencyEnum.IQD)
                return "IQD";

            if (value == CurrencyEnum.IRR)
                return "IRR";

            if (value == CurrencyEnum.ISK)
                return "ISK";

            if (value == CurrencyEnum.JEP)
                return "JEP";

            if (value == CurrencyEnum.JMD)
                return "JMD";

            if (value == CurrencyEnum.JOD)
                return "JOD";

            if (value == CurrencyEnum.JPY)
                return "JPY";

            if (value == CurrencyEnum.KES)
                return "KES";

            if (value == CurrencyEnum.KGS)
                return "KGS";

            if (value == CurrencyEnum.KHR)
                return "KHR";

            if (value == CurrencyEnum.KMF)
                return "KMF";

            if (value == CurrencyEnum.KPW)
                return "KPW";

            if (value == CurrencyEnum.KRW)
                return "KRW";

            if (value == CurrencyEnum.KWD)
                return "KWD";

            if (value == CurrencyEnum.KYD)
                return "KYD";

            if (value == CurrencyEnum.KZT)
                return "KZT";

            if (value == CurrencyEnum.LAK)
                return "LAK";

            if (value == CurrencyEnum.LBP)
                return "LBP";

            if (value == CurrencyEnum.LKR)
                return "LKR";

            if (value == CurrencyEnum.LRD)
                return "LRD";

            if (value == CurrencyEnum.LSL)
                return "LSL";

            if (value == CurrencyEnum.LYD)
                return "LYD";

            if (value == CurrencyEnum.MAD)
                return "MAD";

            if (value == CurrencyEnum.MDL)
                return "MDL";

            if (value == CurrencyEnum.MGA)
                return "MGA";

            if (value == CurrencyEnum.MKD)
                return "MKD";

            if (value == CurrencyEnum.MMK)
                return "MMK";

            if (value == CurrencyEnum.MNT)
                return "MNT";

            if (value == CurrencyEnum.MOP)
                return "MOP";

            if (value == CurrencyEnum.MRO)
                return "MRO";

            if (value == CurrencyEnum.MUR)
                return "MUR";

            if (value == CurrencyEnum.MVR)
                return "MVR";

            if (value == CurrencyEnum.MWK)
                return "MWK";

            if (value == CurrencyEnum.MXN)
                return "MXN";

            if (value == CurrencyEnum.MYR)
                return "MYR";

            if (value == CurrencyEnum.MZN)
                return "MZN";

            if (value == CurrencyEnum.NAD)
                return "NAD";

            if (value == CurrencyEnum.NGN)
                return "NGN";

            if (value == CurrencyEnum.NIO)
                return "NIO";

            if (value == CurrencyEnum.NOK)
                return "NOK";

            if (value == CurrencyEnum.NPR)
                return "NPR";

            if (value == CurrencyEnum.NZD)
                return "NZD";

            if (value == CurrencyEnum.OMR)
                return "OMR";

            if (value == CurrencyEnum.PAB)
                return "PAB";

            if (value == CurrencyEnum.PEN)
                return "PEN";

            if (value == CurrencyEnum.PGK)
                return "PGK";

            if (value == CurrencyEnum.PHP)
                return "PHP";

            if (value == CurrencyEnum.PKR)
                return "PKR";

            if (value == CurrencyEnum.PLN)
                return "PLN";

            if (value == CurrencyEnum.PYG)
                return "PYG";

            if (value == CurrencyEnum.QAR)
                return "QAR";

            if (value == CurrencyEnum.RON)
                return "RON";

            if (value == CurrencyEnum.RSD)
                return "RSD";

            if (value == CurrencyEnum.RUB)
                return "RUB";

            if (value == CurrencyEnum.RWF)
                return "RWF";

            if (value == CurrencyEnum.SAR)
                return "SAR";

            if (value == CurrencyEnum.SBD)
                return "SBD";

            if (value == CurrencyEnum.SCR)
                return "SCR";

            if (value == CurrencyEnum.SDG)
                return "SDG";

            if (value == CurrencyEnum.SEK)
                return "SEK";

            if (value == CurrencyEnum.SGD)
                return "SGD";

            if (value == CurrencyEnum.SHP)
                return "SHP";

            if (value == CurrencyEnum.SLL)
                return "SLL";

            if (value == CurrencyEnum.SOS)
                return "SOS";

            if (value == CurrencyEnum.SPL)
                return "SPL";

            if (value == CurrencyEnum.SRD)
                return "SRD";

            if (value == CurrencyEnum.STD)
                return "STD";

            if (value == CurrencyEnum.SVC)
                return "SVC";

            if (value == CurrencyEnum.SYP)
                return "SYP";

            if (value == CurrencyEnum.SZL)
                return "SZL";

            if (value == CurrencyEnum.THB)
                return "THB";

            if (value == CurrencyEnum.TJS)
                return "TJS";

            if (value == CurrencyEnum.TMT)
                return "TMT";

            if (value == CurrencyEnum.TND)
                return "TND";

            if (value == CurrencyEnum.TOP)
                return "TOP";

            if (value == CurrencyEnum.TRY)
                return "TRY";

            if (value == CurrencyEnum.TTD)
                return "TTD";

            if (value == CurrencyEnum.TVD)
                return "TVD";

            if (value == CurrencyEnum.TWD)
                return "TWD";

            if (value == CurrencyEnum.TZS)
                return "TZS";

            if (value == CurrencyEnum.UAH)
                return "UAH";

            if (value == CurrencyEnum.UGX)
                return "UGX";

            if (value == CurrencyEnum.USD)
                return "USD";

            if (value == CurrencyEnum.UYU)
                return "UYU";

            if (value == CurrencyEnum.UZS)
                return "UZS";

            if (value == CurrencyEnum.VEF)
                return "VEF";

            if (value == CurrencyEnum.VND)
                return "VND";

            if (value == CurrencyEnum.VUV)
                return "VUV";

            if (value == CurrencyEnum.WST)
                return "WST";

            if (value == CurrencyEnum.XAF)
                return "XAF";

            if (value == CurrencyEnum.XCD)
                return "XCD";

            if (value == CurrencyEnum.XDR)
                return "XDR";

            if (value == CurrencyEnum.XOF)
                return "XOF";

            if (value == CurrencyEnum.XPF)
                return "XPF";

            if (value == CurrencyEnum.YER)
                return "YER";

            if (value == CurrencyEnum.ZAR)
                return "ZAR";

            if (value == CurrencyEnum.ZMW)
                return "ZMW";

            if (value == CurrencyEnum.ZWD)
                return "ZWD";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public CurrencyEnum Currency { get; set; }

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum PIX for value: PIX
            /// </summary>
            PIX = 1,

            /// <summary>
            /// Enum TED for value: TED
            /// </summary>
            TED = 2,

            /// <summary>
            /// Enum TEF for value: TEF
            /// </summary>
            TEF = 3
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("PIX"))
                return TypeEnum.PIX;

            if (value.Equals("TED"))
                return TypeEnum.TED;

            if (value.Equals("TEF"))
                return TypeEnum.TEF;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("PIX"))
                return TypeEnum.PIX;

            if (value.Equals("TED"))
                return TypeEnum.TED;

            if (value.Equals("TEF"))
                return TypeEnum.TEF;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.PIX)
                return "PIX";

            if (value == TypeEnum.TED)
                return "TED";

            if (value == TypeEnum.TEF)
                return "TEF";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [JsonPropertyName("details")]
        public InfoPagamentoDetalhes Details { get; set; }

        /// <summary>
        /// Used to track the state of Date
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateOption { get; private set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public string? Date { get { return this.DateOption.Value; } set { this.DateOption = new(value); } }

        /// <summary>
        /// Used to track the state of IbgeTownCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IbgeTownCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets IbgeTownCode
        /// </summary>
        [JsonPropertyName("ibgeTownCode")]
        public string? IbgeTownCode { get { return this.IbgeTownCodeOption.Value; } set { this.IbgeTownCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentDescription
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaymentDescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentDescription
        /// </summary>
        [JsonPropertyName("paymentDescription")]
        public string? PaymentDescription { get { return this.PaymentDescriptionOption.Value; } set { this.PaymentDescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schedule
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Agendamento?> ScheduleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [JsonPropertyName("schedule")]
        public Agendamento? Schedule { get { return this.ScheduleOption.Value; } set { this.ScheduleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Pagamento {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  IbgeTownCode: ").Append(IbgeTownCode).Append("\n");
            sb.Append("  PaymentDescription: ").Append(PaymentDescription).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Amount != null) {
                // Amount (string) pattern
                Regex regexAmount = new Regex(@"^((\d{1,16}\.\d{2}))$", RegexOptions.CultureInvariant);

                if (!regexAmount.Match(this.Amount).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Amount, must match a pattern of " + regexAmount, new [] { "Amount" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Pagamento" />
    /// </summary>
    public class PagamentoJsonConverter : JsonConverter<Pagamento>
    {
        /// <summary>
        /// Deserializes json to <see cref="Pagamento" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Pagamento Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> amount = default;
            Option<Pagamento.CurrencyEnum?> currency = default;
            Option<InfoPagamentoDetalhes?> details = default;
            Option<Pagamento.TypeEnum?> type = default;
            Option<string?> date = default;
            Option<string?> ibgeTownCode = default;
            Option<string?> paymentDescription = default;
            Option<Agendamento?> schedule = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "amount":
                            amount = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "currency":
                            string? currencyRawValue = utf8JsonReader.GetString();
                            if (currencyRawValue != null)
                                currency = new Option<Pagamento.CurrencyEnum?>(Pagamento.CurrencyEnumFromStringOrDefault(currencyRawValue));
                            break;
                        case "details":
                            details = new Option<InfoPagamentoDetalhes?>(JsonSerializer.Deserialize<InfoPagamentoDetalhes>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<Pagamento.TypeEnum?>(Pagamento.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ibgeTownCode":
                            ibgeTownCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paymentDescription":
                            paymentDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schedule":
                            schedule = new Option<Agendamento?>(JsonSerializer.Deserialize<Agendamento>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!amount.IsSet)
                throw new ArgumentException("Property is required for class Pagamento.", nameof(amount));

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class Pagamento.", nameof(currency));

            if (!details.IsSet)
                throw new ArgumentException("Property is required for class Pagamento.", nameof(details));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class Pagamento.", nameof(type));

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class Pagamento.");

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class Pagamento.");

            if (details.IsSet && details.Value == null)
                throw new ArgumentNullException(nameof(details), "Property is not nullable for class Pagamento.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class Pagamento.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class Pagamento.");

            if (ibgeTownCode.IsSet && ibgeTownCode.Value == null)
                throw new ArgumentNullException(nameof(ibgeTownCode), "Property is not nullable for class Pagamento.");

            if (paymentDescription.IsSet && paymentDescription.Value == null)
                throw new ArgumentNullException(nameof(paymentDescription), "Property is not nullable for class Pagamento.");

            if (schedule.IsSet && schedule.Value == null)
                throw new ArgumentNullException(nameof(schedule), "Property is not nullable for class Pagamento.");

            return new Pagamento(amount.Value!, currency.Value!.Value!, details.Value!, type.Value!.Value!, date, ibgeTownCode, paymentDescription, schedule);
        }

        /// <summary>
        /// Serializes a <see cref="Pagamento" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagamento"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Pagamento pagamento, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pagamento, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Pagamento" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagamento"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Pagamento pagamento, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pagamento.Amount == null)
                throw new ArgumentNullException(nameof(pagamento.Amount), "Property is required for class Pagamento.");

            if (pagamento.Details == null)
                throw new ArgumentNullException(nameof(pagamento.Details), "Property is required for class Pagamento.");

            if (pagamento.DateOption.IsSet && pagamento.Date == null)
                throw new ArgumentNullException(nameof(pagamento.Date), "Property is required for class Pagamento.");

            if (pagamento.IbgeTownCodeOption.IsSet && pagamento.IbgeTownCode == null)
                throw new ArgumentNullException(nameof(pagamento.IbgeTownCode), "Property is required for class Pagamento.");

            if (pagamento.PaymentDescriptionOption.IsSet && pagamento.PaymentDescription == null)
                throw new ArgumentNullException(nameof(pagamento.PaymentDescription), "Property is required for class Pagamento.");

            if (pagamento.ScheduleOption.IsSet && pagamento.Schedule == null)
                throw new ArgumentNullException(nameof(pagamento.Schedule), "Property is required for class Pagamento.");

            writer.WriteString("amount", pagamento.Amount);

            var currencyRawValue = Pagamento.CurrencyEnumToJsonValue(pagamento.Currency);
            writer.WriteString("currency", currencyRawValue);
            writer.WritePropertyName("details");
            JsonSerializer.Serialize(writer, pagamento.Details, jsonSerializerOptions);
            var typeRawValue = Pagamento.TypeEnumToJsonValue(pagamento.Type);
            writer.WriteString("type", typeRawValue);
            if (pagamento.DateOption.IsSet)
                writer.WriteString("date", pagamento.Date);

            if (pagamento.IbgeTownCodeOption.IsSet)
                writer.WriteString("ibgeTownCode", pagamento.IbgeTownCode);

            if (pagamento.PaymentDescriptionOption.IsSet)
                writer.WriteString("paymentDescription", pagamento.PaymentDescription);

            if (pagamento.ScheduleOption.IsSet)
            {
                writer.WritePropertyName("schedule");
                JsonSerializer.Serialize(writer, pagamento.Schedule, jsonSerializerOptions);
            }
        }
    }
}
