/*
 * API PIX
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/pix/api/v2 ]</pre> A API Pix Sicoob é uma forma fácil e segura dos associados gerenciarem os seus recebimentos Pix. Ela permite criar cobranças e validar a situação do pagamento, bem como verificar os Pix recebidos.  Seguindo os padrões definidos pelo Bacen, esta API utiliza as melhores práticas de segurança e possui autenticação com TLS mútuo, como uma medida adicional de proteção.
 *
 * The version of the OpenAPI document: 2.0.23.28
 * Contact: suporte.pix@bcb.gov.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Sicoob.Pix.Model;
using System.Runtime.CompilerServices;
using System.Net.Http.Headers;

[assembly: InternalsVisibleTo("Sicoob.Pix.Test")]

namespace Sicoob.Pix.Client
{
    /// <summary>
    /// Utility functions providing some benefit to API client consumers.
    /// </summary>
    public static partial class ClientUtils
    {

        /// <summary>
        /// A delegate for events.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        /// <returns></returns>
        public delegate void EventHandler<T>(object sender, T e) where T : EventArgs;

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="json"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(string json, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(json, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="reader"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(ref Utf8JsonReader reader, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(ref reader, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// If parameter is DateTime, output in a formatted string (default ISO 8601), customizable with Configuration.DateTime.
        /// If parameter is a list, join the list with ",".
        /// Otherwise just return the string.
        /// </summary>
        /// <param name="obj">The parameter (header, path, query, form).</param>
        /// <param name="format">The DateTime serialization format.</param>
        /// <returns>Formatted string.</returns>
        public static string? ParameterToString(object? obj, string? format = ISO8601_DATETIME_FORMAT)
        {
            if (obj is DateTime dateTime)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTime.ToString(format);
            if (obj is DateTimeOffset dateTimeOffset)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTimeOffset.ToString(format);
            if (obj is DateOnly dateOnly)
                return dateOnly.ToString(format);
            if (obj is bool boolean)
                return boolean
                    ? "true"
                    : "false";
            if (obj is CobCompleta.StatusEnum cobCompletaStatusEnum)
                return CobCompleta.StatusEnumToJsonValue(cobCompletaStatusEnum);
            if (obj is CobGerada.StatusEnum cobGeradaStatusEnum)
                return CobGerada.StatusEnumToJsonValue(cobGeradaStatusEnum);
            if (obj is CobPayload.StatusEnum cobPayloadStatusEnum)
                return CobPayload.StatusEnumToJsonValue(cobPayloadStatusEnum);
            if (obj is CobRevisada.StatusEnum cobRevisadaStatusEnum)
                return CobRevisada.StatusEnumToJsonValue(cobRevisadaStatusEnum);
            if (obj is CobVCompleta.StatusEnum cobVCompletaStatusEnum)
                return CobVCompleta.StatusEnumToJsonValue(cobVCompletaStatusEnum);
            if (obj is CobVGerada.StatusEnum cobVGeradaStatusEnum)
                return CobVGerada.StatusEnumToJsonValue(cobVGeradaStatusEnum);
            if (obj is CobVPayload.StatusEnum cobVPayloadStatusEnum)
                return CobVPayload.StatusEnumToJsonValue(cobVPayloadStatusEnum);
            if (obj is CobVRevisada.StatusEnum cobVRevisadaStatusEnum)
                return CobVRevisada.StatusEnumToJsonValue(cobVRevisadaStatusEnum);
            if (obj is CobrancaRecorrenteCompleta.StatusEnum cobrancaRecorrenteCompletaStatusEnum)
                return CobrancaRecorrenteCompleta.StatusEnumToJsonValue(cobrancaRecorrenteCompletaStatusEnum);
            if (obj is CobrancaRecorrenteGerada.StatusEnum cobrancaRecorrenteGeradaStatusEnum)
                return CobrancaRecorrenteGerada.StatusEnumToJsonValue(cobrancaRecorrenteGeradaStatusEnum);
            if (obj is CobrancaRecorrenteSolicitadaRecebedor.TipoContaEnum cobrancaRecorrenteSolicitadaRecebedorTipoContaEnum)
                return CobrancaRecorrenteSolicitadaRecebedor.TipoContaEnumToJsonValue(cobrancaRecorrenteSolicitadaRecebedorTipoContaEnum);
            if (obj is CobrancaRecorrenteStatus.StatusEnum cobrancaRecorrenteStatusStatusEnum)
                return CobrancaRecorrenteStatus.StatusEnumToJsonValue(cobrancaRecorrenteStatusStatusEnum);
            if (obj is DadosBancariosRecebedor.TipoContaEnum dadosBancariosRecebedorTipoContaEnum)
                return DadosBancariosRecebedor.TipoContaEnumToJsonValue(dadosBancariosRecebedorTipoContaEnum);
            if (obj is Devolucao.StatusEnum devolucaoStatusEnum)
                return Devolucao.StatusEnumToJsonValue(devolucaoStatusEnum);
            if (obj is DevolucaoNatureza devolucaoNatureza)
                return DevolucaoNaturezaValueConverter.ToJsonValue(devolucaoNatureza);
            if (obj is DevolucaoSolicitadaNatureza devolucaoSolicitadaNatureza)
                return DevolucaoSolicitadaNaturezaValueConverter.ToJsonValue(devolucaoSolicitadaNatureza);
            if (obj is HistRicoDeStatusDaSolicitaODeRecorrNciaInner.StatusEnum histRicoDeStatusDaSolicitaODeRecorrNciaInnerStatusEnum)
                return HistRicoDeStatusDaSolicitaODeRecorrNciaInner.StatusEnumToJsonValue(histRicoDeStatusDaSolicitaODeRecorrNciaInnerStatusEnum);
            if (obj is HistRicoDeStatusInner.StatusEnum histRicoDeStatusInnerStatusEnum)
                return HistRicoDeStatusInner.StatusEnumToJsonValue(histRicoDeStatusInnerStatusEnum);
            if (obj is HistRicoDeStatusInner1.StatusEnum histRicoDeStatusInner1StatusEnum)
                return HistRicoDeStatusInner1.StatusEnumToJsonValue(histRicoDeStatusInner1StatusEnum);
            if (obj is HistRicoDeStatusInner2.StatusEnum histRicoDeStatusInner2StatusEnum)
                return HistRicoDeStatusInner2.StatusEnumToJsonValue(histRicoDeStatusInner2StatusEnum);
            if (obj is HistRicoDeTentativasDeCobranAInner.TipoEnum histRicoDeTentativasDeCobranAInnerTipoEnum)
                return HistRicoDeTentativasDeCobranAInner.TipoEnumToJsonValue(histRicoDeTentativasDeCobranAInnerTipoEnum);
            if (obj is HistRicoDeTentativasDeCobranAInner.StatusEnum histRicoDeTentativasDeCobranAInnerStatusEnum)
                return HistRicoDeTentativasDeCobranAInner.StatusEnumToJsonValue(histRicoDeTentativasDeCobranAInnerStatusEnum);
            if (obj is InformaEsSobreARejeiODaCobranA.CodigoEnum informaEsSobreARejeiODaCobranACodigoEnum)
                return InformaEsSobreARejeiODaCobranA.CodigoEnumToJsonValue(informaEsSobreARejeiODaCobranACodigoEnum);
            if (obj is InformaEsSobreARejeiODaRecorrNcia.CodigoEnum informaEsSobreARejeiODaRecorrNciaCodigoEnum)
                return InformaEsSobreARejeiODaRecorrNcia.CodigoEnumToJsonValue(informaEsSobreARejeiODaRecorrNciaCodigoEnum);
            if (obj is InformaEsSobreARejeiODaTentativaDaCobranA.CodigoEnum informaEsSobreARejeiODaTentativaDaCobranACodigoEnum)
                return InformaEsSobreARejeiODaTentativaDaCobranA.CodigoEnumToJsonValue(informaEsSobreARejeiODaTentativaDaCobranACodigoEnum);
            if (obj is InformaEsSobreCalendRioDaRecorrNcia.PeriodicidadeEnum informaEsSobreCalendRioDaRecorrNciaPeriodicidadeEnum)
                return InformaEsSobreCalendRioDaRecorrNcia.PeriodicidadeEnumToJsonValue(informaEsSobreCalendRioDaRecorrNciaPeriodicidadeEnum);
            if (obj is InformaEsSobreCalendRioDaRecorrNcia1.PeriodicidadeEnum informaEsSobreCalendRioDaRecorrNcia1PeriodicidadeEnum)
                return InformaEsSobreCalendRioDaRecorrNcia1.PeriodicidadeEnumToJsonValue(informaEsSobreCalendRioDaRecorrNcia1PeriodicidadeEnum);
            if (obj is InformaEsSobreOCancelamentoDaCobranA.SolicitanteEnum informaEsSobreOCancelamentoDaCobranASolicitanteEnum)
                return InformaEsSobreOCancelamentoDaCobranA.SolicitanteEnumToJsonValue(informaEsSobreOCancelamentoDaCobranASolicitanteEnum);
            if (obj is InformaEsSobreOCancelamentoDaCobranA.CodigoEnum informaEsSobreOCancelamentoDaCobranACodigoEnum)
                return InformaEsSobreOCancelamentoDaCobranA.CodigoEnumToJsonValue(informaEsSobreOCancelamentoDaCobranACodigoEnum);
            if (obj is InformaEsSobreOCancelamentoDaRecorrNcia.SolicitanteEnum informaEsSobreOCancelamentoDaRecorrNciaSolicitanteEnum)
                return InformaEsSobreOCancelamentoDaRecorrNcia.SolicitanteEnumToJsonValue(informaEsSobreOCancelamentoDaRecorrNciaSolicitanteEnum);
            if (obj is InformaEsSobreOCancelamentoDaRecorrNcia.CodigoEnum informaEsSobreOCancelamentoDaRecorrNciaCodigoEnum)
                return InformaEsSobreOCancelamentoDaRecorrNcia.CodigoEnumToJsonValue(informaEsSobreOCancelamentoDaRecorrNciaCodigoEnum);
            if (obj is LoteCobVConsultadoCobsvInner.StatusEnum loteCobVConsultadoCobsvInnerStatusEnum)
                return LoteCobVConsultadoCobsvInner.StatusEnumToJsonValue(loteCobVConsultadoCobsvInnerStatusEnum);
            if (obj is LotecobvIdPatchRequestCobsvInner.StatusEnum lotecobvIdPatchRequestCobsvInnerStatusEnum)
                return LotecobvIdPatchRequestCobsvInner.StatusEnumToJsonValue(lotecobvIdPatchRequestCobsvInnerStatusEnum);
            if (obj is ParametrosConsultaPayloadLocation.TipoCobEnum parametrosConsultaPayloadLocationTipoCobEnum)
                return ParametrosConsultaPayloadLocation.TipoCobEnumToJsonValue(parametrosConsultaPayloadLocationTipoCobEnum);
            if (obj is PayloadLocation.TipoCobEnum payloadLocationTipoCobEnum)
                return PayloadLocation.TipoCobEnumToJsonValue(payloadLocationTipoCobEnum);
            if (obj is PayloadLocationCompleta.TipoCobEnum payloadLocationCompletaTipoCobEnum)
                return PayloadLocationCompleta.TipoCobEnumToJsonValue(payloadLocationCompletaTipoCobEnum);
            if (obj is PayloadLocationSolicitada.TipoCobEnum payloadLocationSolicitadaTipoCobEnum)
                return PayloadLocationSolicitada.TipoCobEnumToJsonValue(payloadLocationSolicitadaTipoCobEnum);
            if (obj is RecorrenciaConfiguracao.PoliticaRetentativaEnum recorrenciaConfiguracaoPoliticaRetentativaEnum)
                return RecorrenciaConfiguracao.PoliticaRetentativaEnumToJsonValue(recorrenciaConfiguracaoPoliticaRetentativaEnum);
            if (obj is RecorrenciaGerada.StatusEnum recorrenciaGeradaStatusEnum)
                return RecorrenciaGerada.StatusEnumToJsonValue(recorrenciaGeradaStatusEnum);
            if (obj is RecorrenciaGerada.PoliticaRetentativaEnum recorrenciaGeradaPoliticaRetentativaEnum)
                return RecorrenciaGerada.PoliticaRetentativaEnumToJsonValue(recorrenciaGeradaPoliticaRetentativaEnum);
            if (obj is RecorrenciaPayload.PoliticaRetentativaEnum recorrenciaPayloadPoliticaRetentativaEnum)
                return RecorrenciaPayload.PoliticaRetentativaEnumToJsonValue(recorrenciaPayloadPoliticaRetentativaEnum);
            if (obj is RecorrenciaSolicitada.PoliticaRetentativaEnum recorrenciaSolicitadaPoliticaRetentativaEnum)
                return RecorrenciaSolicitada.PoliticaRetentativaEnumToJsonValue(recorrenciaSolicitadaPoliticaRetentativaEnum);
            if (obj is RecorrenciaStatus.StatusEnum recorrenciaStatusStatusEnum)
                return RecorrenciaStatus.StatusEnumToJsonValue(recorrenciaStatusStatusEnum);
            if (obj is Saque.ModalidadeAgenteEnum saqueModalidadeAgenteEnum)
                return Saque.ModalidadeAgenteEnumToJsonValue(saqueModalidadeAgenteEnum);
            if (obj is Saque1.ModalidadeAgenteEnum saque1ModalidadeAgenteEnum)
                return Saque1.ModalidadeAgenteEnumToJsonValue(saque1ModalidadeAgenteEnum);
            if (obj is SolicRecCompleta.StatusEnum solicRecCompletaStatusEnum)
                return SolicRecCompleta.StatusEnumToJsonValue(solicRecCompletaStatusEnum);
            if (obj is SolicRecRevisada.StatusEnum solicRecRevisadaStatusEnum)
                return SolicRecRevisada.StatusEnumToJsonValue(solicRecRevisadaStatusEnum);
            if (obj is SolicRecorrenciaStatus.StatusEnum solicRecorrenciaStatusStatusEnum)
                return SolicRecorrenciaStatus.StatusEnumToJsonValue(solicRecorrenciaStatusStatusEnum);
            if (obj is TipoJornada tipoJornada)
                return TipoJornadaValueConverter.ToJsonValue(tipoJornada);
            if (obj is Troco.ModalidadeAgenteEnum trocoModalidadeAgenteEnum)
                return Troco.ModalidadeAgenteEnumToJsonValue(trocoModalidadeAgenteEnum);
            if (obj is Troco1.ModalidadeAgenteEnum troco1ModalidadeAgenteEnum)
                return Troco1.ModalidadeAgenteEnumToJsonValue(troco1ModalidadeAgenteEnum);
            if (obj is ICollection collection)
            {
                List<string?> entries = new();
                foreach (var entry in collection)
                    entries.Add(ParameterToString(entry));
                return string.Join(",", entries);
            }

            return Convert.ToString(obj, System.Globalization.CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// URL encode a string
        /// Credit/Ref: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Extensions/StringExtensions.cs#L50
        /// </summary>
        /// <param name="input">string to be URL encoded</param>
        /// <returns>Byte array</returns>
        public static string UrlEncode(string input)
        {
            const int maxLength = 32766;

            if (input == null)
            {
                throw new ArgumentNullException("input");
            }

            if (input.Length <= maxLength)
            {
                return Uri.EscapeDataString(input);
            }

            StringBuilder sb = new StringBuilder(input.Length * 2);
            int index = 0;

            while (index < input.Length)
            {
                int length = Math.Min(input.Length - index, maxLength);
                string subString = input.Substring(index, length);

                sb.Append(Uri.EscapeDataString(subString));
                index += subString.Length;
            }

            return sb.ToString();
        }

        /// <summary>
        /// Encode string in base64 format.
        /// </summary>
        /// <param name="text">string to be encoded.</param>
        /// <returns>Encoded string.</returns>
        public static string Base64Encode(string text)
        {
            return Convert.ToBase64String(global::System.Text.Encoding.UTF8.GetBytes(text));
        }

        /// <summary>
        /// Convert stream to byte array
        /// </summary>
        /// <param name="inputStream">Input stream to be converted</param>
        /// <returns>Byte array</returns>
        public static byte[] ReadAsBytes(Stream inputStream)
        {
            using (var ms = new MemoryStream())
            {
                inputStream.CopyTo(ms);
                return ms.ToArray();
            }
        }

        /// <summary>
        /// Select the Content-Type header's value from the given content-type array:
        /// if JSON type exists in the given array, use it;
        /// otherwise use the first one defined in 'consumes'
        /// </summary>
        /// <param name="contentTypes">The Content-Type array to select from.</param>
        /// <returns>The Content-Type header to use.</returns>
        public static string? SelectHeaderContentType(string[] contentTypes)
        {
            if (contentTypes.Length == 0)
                return null;

            foreach (var contentType in contentTypes)
            {
                if (IsJsonMime(contentType))
                    return contentType;
            }

            return contentTypes[0]; // use the first content type specified in 'consumes'
        }

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them (joining into a string)
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header to use.</returns>
        public static string? SelectHeaderAccept(string[] accepts)
        {
            if (accepts.Length == 0)
                return null;

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                return "application/json";

            return string.Join(",", accepts);
        }

        

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them.
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header values to use.</returns>
        public static IEnumerable<MediaTypeWithQualityHeaderValue> SelectHeaderAcceptArray(string[] accepts)
        {
            if (accepts.Length == 0)
                    return [];

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                    return [MediaTypeWithQualityHeaderValue.Parse("application/json")];

            return accepts.Select(MediaTypeWithQualityHeaderValue.Parse);
        }

        /// <summary>
        /// Provides a case-insensitive check that a provided content type is a known JSON-like content type.
        /// </summary>
        [GeneratedRegex("(?i)^(application/json|[^;/ \t]+/[^;/ \t]+[+]json)[ \t]*(;.*)?$")]
        private static partial Regex JsonRegex();

        /// <summary>
        /// Check if the given MIME is a JSON MIME.
        /// JSON MIME examples:
        ///    application/json
        ///    application/json; charset=UTF8
        ///    APPLICATION/JSON
        ///    application/vnd.company+json
        /// </summary>
        /// <param name="mime">MIME</param>
        /// <returns>Returns True if MIME type is json.</returns>
        public static bool IsJsonMime(string mime)
        {
            if (string.IsNullOrWhiteSpace(mime)) return false;

            return JsonRegex().IsMatch(mime) || mime.Equals("application/json-patch+json");
        }

        /// <summary>
        /// Get the discriminator
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="discriminator"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public static string? GetDiscriminator(Utf8JsonReader utf8JsonReader, string discriminator)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    if (localVarJsonPropertyName != null && localVarJsonPropertyName.Equals(discriminator))
                        return utf8JsonReader.GetString();
                }
            }

            throw new JsonException("The specified discriminator was not found.");
        }

        /// <summary>
        /// The base path of the API
        /// </summary>
        public const string BASE_ADDRESS = "https://api.sicoob.com.br/pix/api/v2";

        /// <summary>
        /// The scheme of the API
        /// </summary>
        public const string SCHEME = "https";

        /// <summary>
        /// The context path of the API
        /// </summary>
        public const string CONTEXT_PATH = "/pix/api/v2";

        /// <summary>
        /// The host of the API
        /// </summary>
        public const string HOST = "api.sicoob.com.br";

        /// <summary>
        /// The format to use for DateTime serialization
        /// </summary>
        public const string ISO8601_DATETIME_FORMAT = "o";

        /// <summary>
        /// Unwraps the "resultado" property from the JSON if the type doesn't expect it.
        /// </summary>
        public static string UnwrapResultado(string rawContent, Type type)
        {
            if (string.IsNullOrWhiteSpace(rawContent)) return rawContent;
            if (type.Name.Contains("Response") || type.Name.Contains("Resposta"))
                return rawContent;
            try
            {
                using (var document = System.Text.Json.JsonDocument.Parse(rawContent))
                {
                    if (document.RootElement.ValueKind == System.Text.Json.JsonValueKind.Object &&
                        document.RootElement.TryGetProperty("resultado", out var resultado) &&
                        resultado.ValueKind != System.Text.Json.JsonValueKind.Null)
                    {
                        return resultado.GetRawText();
                    }
                }
            }
            catch { }
            return rawContent;
        }
    }
}
