// <auto-generated>
/*
 * Poupança
 *
 * <pre>[ Base URL: https://api.sicoob.com.br/poupanca/v3 ]</pre> # Poupança API Sistema que faz a gestão das contas de poupança através de transãções como Aplicação, Resgate, Saldo, Extrato e Controle de Rentabilidade. 
 *
 * The version of the OpenAPI document: 3.0.4.0
 * Contact: marco.martins@sicoob.com.br
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Sicoob.Poupanca.Client;
using Sicoob.Poupanca.Model;
using System.Diagnostics.CodeAnalysis;

namespace Sicoob.Poupanca.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IAplicacaoPoupancaApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        AplicacaoPoupancaApiEvents Events { get; }

        /// <summary>
        /// Aplicação de uma conta vinculada
        /// </summary>
        /// <remarks>
        /// Realiza uma aplicacao de uma conta corrente vinculada para uma conta conta poupança com os parametros informados.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">ClientId utilizado na utilização do TOKEN</param>
        /// <param name="aplicacao">Parametros a serem preenchidos com os dados da aplicacao</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAplicacaoApiResponse"/>&gt;</returns>
        Task<IAplicacaoApiResponse> AplicacaoAsync(string clientId, Transferencia aplicacao, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Aplicação de uma conta vinculada
        /// </summary>
        /// <remarks>
        /// Realiza uma aplicacao de uma conta corrente vinculada para uma conta conta poupança com os parametros informados.
        /// </remarks>
        /// <param name="clientId">ClientId utilizado na utilização do TOKEN</param>
        /// <param name="aplicacao">Parametros a serem preenchidos com os dados da aplicacao</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAplicacaoApiResponse"/>?&gt;</returns>
        Task<IAplicacaoApiResponse?> AplicacaoOrDefaultAsync(string clientId, Transferencia aplicacao, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IAplicacaoApiResponse"/>
    /// </summary>
    public interface IAplicacaoApiResponse : Sicoob.Poupanca.Client.IApiResponse, ICreated<Sicoob.Poupanca.Model.RetornoTransferencia?>, IBadRequest<Sicoob.Poupanca.Model.MensagensErro?>, IInternalServerError<Sicoob.Poupanca.Model.MensagensErro?>
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class AplicacaoPoupancaApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnAplicacao;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorAplicacao;

        internal void ExecuteOnAplicacao(AplicacaoPoupancaApi.AplicacaoApiResponse apiResponse)
        {
            OnAplicacao?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorAplicacao(Exception exception)
        {
            OnErrorAplicacao?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class AplicacaoPoupancaApi : IAplicacaoPoupancaApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<AplicacaoPoupancaApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public AplicacaoPoupancaApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="OauthTokenProvider"/>
        /// </summary>
        public TokenProvider<OAuthToken> OauthTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AplicacaoPoupancaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AplicacaoPoupancaApi(ILogger<AplicacaoPoupancaApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, AplicacaoPoupancaApiEvents aplicacaoPoupancaApiEvents,
            TokenProvider<OAuthToken> oauthTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<AplicacaoPoupancaApi>();
            HttpClient = httpClient;
            Events = aplicacaoPoupancaApiEvents;
            OauthTokenProvider = oauthTokenProvider;
        }

        partial void FormatAplicacao(ref string clientId, Transferencia aplicacao);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="clientId"></param>
        /// <param name="aplicacao"></param>
        /// <returns></returns>
        private void ValidateAplicacao(string clientId, Transferencia aplicacao)
        {
            if (clientId == null)
                throw new ArgumentNullException(nameof(clientId));

            if (aplicacao == null)
                throw new ArgumentNullException(nameof(aplicacao));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="clientId"></param>
        /// <param name="aplicacao"></param>
        private void AfterAplicacaoDefaultImplementation(IAplicacaoApiResponse apiResponseLocalVar, string clientId, Transferencia aplicacao)
        {
            bool suppressDefaultLog = false;
            AfterAplicacao(ref suppressDefaultLog, apiResponseLocalVar, clientId, aplicacao);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="clientId"></param>
        /// <param name="aplicacao"></param>
        partial void AfterAplicacao(ref bool suppressDefaultLog, IAplicacaoApiResponse apiResponseLocalVar, string clientId, Transferencia aplicacao);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="clientId"></param>
        /// <param name="aplicacao"></param>
        private void OnErrorAplicacaoDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string clientId, Transferencia aplicacao)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorAplicacao(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, clientId, aplicacao);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="clientId"></param>
        /// <param name="aplicacao"></param>
        partial void OnErrorAplicacao(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string clientId, Transferencia aplicacao);

        /// <summary>
        /// Aplicação de uma conta vinculada Realiza uma aplicacao de uma conta corrente vinculada para uma conta conta poupança com os parametros informados.
        /// </summary>
        /// <param name="clientId">ClientId utilizado na utilização do TOKEN</param>
        /// <param name="aplicacao">Parametros a serem preenchidos com os dados da aplicacao</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAplicacaoApiResponse"/>&gt;</returns>
        public async Task<IAplicacaoApiResponse?> AplicacaoOrDefaultAsync(string clientId, Transferencia aplicacao, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await AplicacaoAsync(clientId, aplicacao, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Aplicação de uma conta vinculada Realiza uma aplicacao de uma conta corrente vinculada para uma conta conta poupança com os parametros informados.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">ClientId utilizado na utilização do TOKEN</param>
        /// <param name="aplicacao">Parametros a serem preenchidos com os dados da aplicacao</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAplicacaoApiResponse"/>&gt;</returns>
        public async Task<IAplicacaoApiResponse> AplicacaoAsync(string clientId, Transferencia aplicacao, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateAplicacao(clientId, aplicacao);

                FormatAplicacao(ref clientId, aplicacao);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/aplicacoes"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/aplicacoes");

                    httpRequestMessageLocalVar.Headers.Add("client_id", ClientUtils.ParameterToString(clientId));

                    httpRequestMessageLocalVar.Content = (aplicacao as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(aplicacao, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    OAuthToken oauthTokenLocalVar1 = (OAuthToken) await OauthTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(oauthTokenLocalVar1);

                    oauthTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<AplicacaoApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<AplicacaoApiResponse>();
                        AplicacaoApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/aplicacoes", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterAplicacaoDefaultImplementation(apiResponseLocalVar, clientId, aplicacao);

                        Events.ExecuteOnAplicacao(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorAplicacaoDefaultImplementation(e, "/aplicacoes", uriBuilderLocalVar.Path, clientId, aplicacao);
                Events.ExecuteOnErrorAplicacao(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="AplicacaoApiResponse"/>
        /// </summary>
        public partial class AplicacaoApiResponse : Sicoob.Poupanca.Client.ApiResponse, IAplicacaoApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<AplicacaoApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="AplicacaoApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public AplicacaoApiResponse(ILogger<AplicacaoApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="AplicacaoApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public AplicacaoApiResponse(ILogger<AplicacaoApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public Sicoob.Poupanca.Model.RetornoTransferencia? Created()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsCreated
                    ? System.Text.Json.JsonSerializer.Deserialize<Sicoob.Poupanca.Model.RetornoTransferencia>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 201 Created and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryCreated([NotNullWhen(true)]out Sicoob.Poupanca.Model.RetornoTransferencia? result)
            {
                result = null;

                try
                {
                    result = Created();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)201);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public Sicoob.Poupanca.Model.MensagensErro? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<Sicoob.Poupanca.Model.MensagensErro>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out Sicoob.Poupanca.Model.MensagensErro? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public Sicoob.Poupanca.Model.MensagensErro? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<Sicoob.Poupanca.Model.MensagensErro>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out Sicoob.Poupanca.Model.MensagensErro? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
